canonical/microk8s

microk8s-resources/default-args/etcd, microk8s-resources/default-args/kube-apiserver
This will reduce the clashes we may have with already running etcd deployments using the 2379 port.
=> Use a unix socket for etcd<->apiserver conncetion

microk8s-resources/wrappers/run-with-config-args
This PR adds proper paths to the run-with-config-args wrapper
Dockerd was spawning containerd and was using the locally installed binary (/usr/bin/ in the host). When containerd was removed from the host dockerd was not staring giving this error:
```
May 14 12:03:40 jackal-VGN-FZ11M systemd[1]: snap.microk8s.daemon-docker.service: Main process exited, code=exited, status=1/FAILURE
May 14 12:03:40 jackal-VGN-FZ11M microk8s.daemon-docker[13698]: time="2018-05-14T12:03:39.995163511+03:00" level=debug msg="docker group found. gid: 127"
May 14 12:03:40 jackal-VGN-FZ11M microk8s.daemon-docker[13698]: time="2018-05-14T12:03:39.995822690+03:00" level=debug msg="Listener created for HTTP on unix (/var/snap/microk8s/x1/docker.sock)"
May 14 12:03:40 jackal-VGN-FZ11M microk8s.daemon-docker[13698]: …
```
=> Set proper paths and libs in run-with-config-args wrapper

build-scripts/create-install-hook.sh, build-scripts/create-remove-hook.sh, microk8s-resources/docker-profile, microk8s-resources/wrappers/run-docker-with-args, snapcraft.yaml
With this PR we apply the docker-default profile right before we start the docker daemon. We also use a template profile in case it is not already present in /etc/apparmor.d/ .
Docker is discussing means to expose this default profile so we should handle patching it in a more elegant way in the future.
=> Move the docker profile patch to docker startup

snapcraft.yaml
iptables loads extensions from /lib/xtables.
This causes issues when running on bionic, as the snap iptables binary (from xenial) attempts to load extensions which where built using a later iptables version, and hence fail.
By building iptables from source, and using static linking, we avoid the need to load extensions from the filesystem, and the snap binary is fully independent of the host even in classic mode.
This ensures that the snap works on 16.04 and 18.04.
=> Build iptables statically to avoid classic/host pollution

microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper
exec will replace the executing process not leaving the option for another process to spawn. This will not work if we want to queue actions.
=> Remove exec from actions so actions can be queued

microk8s-resources/wrappers/microk8s-config.wrapper, snapcraft.yaml
```
microk8s.config [-l]
```
This converts the endpoint to use the IP of the default network interface by default, with the option to drop back to using the loopback address.  Otherwise, this is the same as (but shorter than):
```
microk8s.kubectl config view --raw
```
=> Add config action to dump client config

microk8s-resources/actions/dashboard.yaml
This PR enables graphs on the dashboard and grafana. To access grafana just `microk8s.kubectl cluster-info` and click the grafana link.
=> Dashboard update with heapster and grafana

microk8s-resources/default-args/kube-apiserver
Based on https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
=> Update admission-plugins based on upstream recommendations for 1.10

.travis.yml, README.md, microk8s-resources/actions/disable.dns.sh, microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/enable.dns.sh, microk8s-resources/actions/enable.storage.sh, microk8s-resources/default-args/kube-proxy, microk8s-resources/wrappers/microk8s-config.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/run-docker-with-args, snap/hooks/configure, snap/hooks/remove, snapcraft.yaml, tests/smoke-test.sh, tests/templates/bbox.yaml, tests/templates/pvc.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/utils.py, tests/validators.py
A basic set of test, one for each addon we have. We can call the "validators" on a running microk8s by either enabling/disabling the addons or expecting the addons to be already there. The later case will be used when working on testing the upgrade paths.
A few fixes that were made while testing on travis (trusty).
-  util-linux are needed by kubenet
- sed needed to be installed
- gawk should be the one we package. 
Also adding a reset command to clean pods. Should be used before removing snap. Fixes: https://github.com/juju-solutions/microk8s/issues/23
=> Adding addon tests and testing in trusty/travis

microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper
This provides a way to see at runtime what addons are available, instead of having to go to the repo and look at the README (which could be out of date).
Example output:
```
$ microk8s.enable --help
Usage: microk8s.enable ADDON...
Enable one or more ADDON included with microk8s
Example: microk8s.enable dns storage
Available addons:
dashboard
dns
ingress
storage
```
=> Add --help option to microk8s.{enable,disable}

.travis.yml, tests/test-upgrade.py, tests/utils.py
This PR adds a test to verify that the upgrade of a snap is not broken.
We first deploy the snap from UPGRADE_MICROK8S_FROM channel. Then we go through the validators to see which ones apply for that charm. We then upgrade to UPGRADE_MICROK8S_TO and we need the same validators to be passing.
The upgrade path that is tested is the one on the edge channel (see travis.yaml) and eventually we will need to run the same upgrade path validation on the cross channel promotion (ie release a revision tested on edge to beta).
=> Upgrade test linked to travis

README.md, build-scripts/prepare-env.sh, snapcraft.yaml
This PR introduces a environment variable called KUBE_TARCK. Setting KUBE_TRACK to the desired k8s series (eg 1.10) allows for building the latest stable k8s from that release series (eg 1.10.5 at the time of this writting).
This PR is needed for releasing microk8s into snap tracks (eg 1.10/edge)
=> Build option to follow the latest stable on a release series/track

README.md
Added section on fixing "pods can't access internet" problem.
=> Update Troubleshooting guide in readme

tests/test-addons.py, tests/utils.py
Our tests enable and disable dns multiple times. For some reason k8s freaks out and keeps a "Terminating" dns-pod entry for too long. Our tests wait for that dns pod to be deleted and travis sees no output for 10 minutes and kills the tests.
With this PR we make sure that at the end of each test we do a proper job in cleaning up all pods so that the next test will spawn dns-pod without k8s freaking out.
=> Fix travis flakiness with more frequent cluster resets

snapcraft.yaml, tests/templates/nginx-pod.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/test-upgrade.py, tests/validators.py
This fixes the following error:
```
ubuntu@ip-172-31-52-95:~/microk8s$ microk8s.kubectl port-forward pod/microbot-55d84d48c-8lth9 8000:80                                                                                                               
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
E0817 11:39:15.683666    1239 portforward.go:331] an error occurred forwarding 8000 -> 80: error forwarding port 80 to pod 8ffaeb0889cdc05ef2167ed74e3c7420becdf77b1e5bfb3c6b6bba3c58550a6b, uid : unable to do port forwarding: socat not found.
```
As a workaround you can `apt-get install socat`.
=> Add socat package

tests/lxc/install-deps/ubuntu:16.04, tests/lxc/install-deps/ubuntu:18.04, tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile, tests/test-distro.sh, tests/test-upgrade.py
With this PR we add a test that would start an lxc container, run an sistribution specific `install-deps.sh` script and then run the tests and checn the upgrade path.
We should wire this to our CI to automate the releases to beta.
=> Test on other distributions

README.md, docs/dockerd.md, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/run-docker-with-args
This mitigates https://github.com/ubuntu/microk8s/issues/101
We reload the right docker-default profile upon dockerd restart and microk8s.reset.
Also documenting the issue with multiple dockerds and AppArmor.
=> Reset and docker restart will load the right docker-default profile

snap/hooks/configure
Fixes: https://github.com/ubuntu/microk8s/issues/121
First we make sure we use  ${SNAP_DATA} to point to `certs/ca.crt` and then we fix any occurrences we find in `${SNAP_DATA}/args/kube-apiserver` where the full path is used.
=> Use {SNAP_DATA} to point to client-ca-cert instead of a full path

tests/patch-kube-proxy.sh, tests/test-distro.sh, tests/test-upgrade.py
Our CI cross-distro tests on LXC on top of GCE instances are failing with kube-proxy not starting after a `micrk8s.enable dns`.
This is a workaround (or not?) where the we tell kube-proxy not to update the conntrack hashsize during tests. The issue https://github.com/ubuntu/microk8s/issues/119 is here to further investigate this behavior.
=> Kube proxy not touching conntrack hashsize in virtual envs

.travis.yml, tests/verify-branches.py
Assuming upstream stable k8s release is v1.12.x, there has to be a 1.11 github branch used be the respective LP builders for building the v1.11.y.
This indicates that we have not setup the LP builders for new k8s releases.
=> Place a guard to test for the right branches

tests/test-distro.sh
Seems CI slave do not have a tty and script will create one for us.
https://github.com/lxc/lxd/issues/1724#issuecomment-194416774
=> Use script to trigger pytest. CI slaves need this.

tests/test-distro.sh
Add a comment in case we forget why `script` was needed here.
=> remember why we're using 'script' to launch pytest

microk8s-resources/wrappers/run-with-config-args, snapcraft.yaml
This PR will cause kube-proxy and kube-api wait for a default route to appear. 
Fixes: https://github.com/ubuntu/microk8s/issues/149, https://github.com/ubuntu/microk8s/issues/73
Unfortunately this is a blind fix as I was not able to reproduce the issue. My intention is to have this merged and get @wallyworld to give it a try :) as soon as it gets to edge.
=> Fix missing network during restart

scripts/inspect.sh
In response to issue #160, this PR adds a default limit of 100,00 entries to dump for the inspect report.
=> Add a default limit to journalctl

microk8s-resources/certs/csr.conf
- fix "KeyUsage does not allow digital signatures" error when
connecting to api manager with Java based https client
=> Enable digitalSignature key usage for CA

docs/registry.md
Well at least on my system (`bento/ubuntu-18.04` in Vagrant) this is the path the socket ends up at.
Thanks for microk8s, it's great!
=> Fix Docker docker path in docs

tests/test-upgrade.py, tests/utils.py, tests/validators.py
Add retries when talking to xip.io and the snapstore.
Longer waits while enabling addons.
=> Increase timeouts, and http retries

tests/utils.py
We increased the timeouts so our CI will not timeout, but travis fails if the tests run for more than 2 hours.
This PR will cause gpu tests to be aborted quickly in case no nvidia drivers are loaded.
=> Faster nvidia test abort

docs/build_from_source.md
This adds the 'building from source' documentation as a standalone page.
* rewritten as steps
* added link to Snapcraft docs
@ktsakalozos my intention here is to add some standalone pages (one PR at a time) and then adapt the readme to take them into account.
The readme and the final website docs will be slightly different (we don't have side navigation in the readme) but not too much. Making the changes here should improve the docs in this repo and make it easier to sync with the published docs online
=> Add building from source doc

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-istioctl.wrapper, snapcraft.yaml
This is a fix for the distros that do not have dpkg. Since we are using it to get the architecture we have to have it in our snap.
=> Call dpkg from the snap

README.md, snapcraft.yaml
This PR fixes the re-usability of istio binaries.
The bug was that we were moving the binaries during the first build instead of copying them, so reusing them was not possible.
=> Fix reuse istio binaries

microk8s-resources/actions/ingress.yaml
The containerPort in the default-http-backend deployment is defined as 8080, but the service definition is pointing to 80. When I deployed this, I kept getting unreachable upstream errors from nginx. Making this change corrected the problem, which given the container definition, makes sense.
=> Adjust default backend targetPort for ingress.yaml

microk8s-resources/actions/ingress.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/222
Ingress tries to get an external IP so it reports no address in `microk8s.kubectl get ingress`. With this PR we tell ingress to report 127.0.0.1.
=> Ingress to report 127.0.0.1 as address of endpoints

README.md
I'm migrating my application from docker-compose to kubernetes. While i was doing that i wanted to add efk stack to the mix. I spent some hours before i realized that i was trying to collect logs from an irrelevant docker daemon :)
I wanted to add this to troubleshooting section so that other people can save this time
=> Add troubleshooting section about log collectors

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-with-config-args
The script that runs detection of new IP addresses fails under Ubuntu 18.04 with the message:
```
microk8s.daemon-apiserver-kicker[29730]: link: error fetching interface information: Device not found
```
In one place, `netstat` is used, and the other two `ip` is. `netstat` appears to work, so use that instead.
=> Use netstat to get the default interface name

.travis.yml
snapcraft docker image is too old. We use the one from beta to get a newer.
=> Use snapcraft docker image from beta tag as it builds more often

microk8s-resources/actions/ingress.yaml
By default, the ingress installation seems to use a non-existing ConfigMap and having another one that exists but isn't used is confusing. This switches the controller to use the one that microk8s creates.
=> Use the correct ConfigMap for nginx ingress

microk8s-resources/actions/ingress.yaml
The nginx ingress pod is created with `hostNet: true`. This means that
it does not, by default, have access to kuebdns. We need that so that
the ingress controller can map things like ExternalName services to
internal services.
This fixes the problem by setting the dnsPolicy to
ClusterFirstWithHostNet.
Fixes #339
=> Use ClusterFirstWithHostNet for nginx dnsPolicy

.travis.yml, build-scripts/prepare-env.sh, docs/community.md, microk8s-resources/actions/disable.ingress.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml
This change uses a newer containerd and runc mainly so that we have the fix for CVE-2019-5736.
=> Use newer containerd and runc versions

microk8s-resources/wrappers/microk8s-reset.wrapper
This change removes installed CRDs when microk8s.reset is executed. I find it useful, particularly for people playing with CRDs and Custom Operators, like myself.
See #261
=> fix: delete CRDs on reset

snapcraft.yaml
These libraries if pot patchelfed use libraries from the host and may fail if the used libs are missing. 
Fixes: https://github.com/ubuntu/microk8s/issues/370
We need to investigate if the rest of the libraries need to be patchelfed: https://github.com/ubuntu/microk8s/issues/371
=> Fix packages that need patchelf

tests/lxc/install-deps/images:archlinux
This gets the registry test passing on archlinux. We install a docker client to push to the registry.
=> Installing docker client on archlinux to have the registry test passing

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-config.wrapper, microk8s-resources/wrappers/run-with-config-args
Seems ifconfig output is locale sensitive so we use ip to extract the IP.
We also improve the case where no IP is detected.
Fixes: https://github.com/ubuntu/microk8s/issues/402 https://github.com/ubuntu/microk8s/issues/395 https://github.com/ubuntu/microk8s/issues/400
=> Use ip and not ifconfig for IP detection

microk8s-resources/default-args/containerd-env
Fixes https://github.com/ubuntu/microk8s/issues/253
=> Set the maximum number of open file descriptors to 65k for containers

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove
This PR fixes two issues.
- The remove will hang incase a pod has mounted a filesystem that cannot be umounted. For example an nfs server is down
- The start/stop commands will uncordon/cordon, this way any mounted PVCs will be released and we will be able to remove the snap when microk8s is stopped.
We also pave the way to handle daemon restarts during new releases.
=> Drain node before stopping it

snapcraft.yaml
On Fedora 29, when using port forward, socat failed with:
error while loading shared libraries: libnsl.so.1:
cannot open shared object file: No such file or directory
=> Fix socat needing patchelf (ubuntu/microk8s#286)

README.md, scripts/inspect.sh
I just got bit by this the other day.  It looked like a DNS issue that other users had in the past, so I geared up to diagnose DNS issues (2hr because I was quite rusty with docker).  Then I realized that it was a complete network issue after pinging 8.8.8.8 and getting nothing which luckily reminded me of a blog post where a guy lost tons of time diagnosing the issue.  I hope there weren't technical reasons why this package wasn't added to the readme.
=> adds command to make iptables -P FORWARD ACCEPT save

docs/community.md
There's a short guide in the Cilium docs about how to bootstrap microk8s with Cilium providing the networking/security as a CNI. Add it to the community links.
=> Add link to Cilium MicroK8s guide

microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper
Fixes: https://github.com/ubuntu/microk8s/issues/468
The user will have to drain the node himself if he wished to right before stopping MicroK8s.
=> Start/stop will not drain/uncordon the node

README.md, microk8s-resources/actions/disable.rbac.sh, microk8s-resources/actions/enable.rbac.sh, microk8s-resources/wrappers/microk8s-status.wrapper, tests/test-addons.py, tests/utils.py, tests/validators.py
This PR will add a RBAC addon.
When enabled, the kube-apiserver `authorization-mode` will be set to `RBAC`. Kubernetes will then automatically add all default (cluster-)roles and (cluster-)rolebindings.
When disabled, the `authorization-mode` will be reset to `AlwaysAllow`, and all the (cluster-)roles and (cluster-)rolebindings labeled `kubernetes.io/bootstrapping=rbac-defaults` will be removed.
This PR is based on feature/containerd-access at this time since it needs the added features of PR #323.
Todo:
- ~Add label when finding resources to delete.~
- Provide warning if user is using insecure port as per comment from @ktsakalozos in #323.
- ~Add tests.~
- ~Disabling addin works first time, then fails.~
=> RBAC addon

microk8s-resources/wrappers/microk8s-start.wrapper
This handles the case where the user has the node stopped. The upgrade happened and he does a `microk8s.start`. In this case the node was drained so we need to uncordon.
=> Uncordon node when starting it

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-with-config-args, snap/hooks/configure, snap/hooks/install, snapcraft.yaml
creates a csr.conf.rendered and compare it with csr.conf.
Forces the apiserver-kicker to recreate and reload the certificates when changes are detected.
=> update the csr.conf when csr.conf.template changed.

microk8s-resources/actions/coredns.yaml, microk8s-resources/actions/disable.dns.sh, microk8s-resources/actions/dns.yaml, microk8s-resources/actions/enable.dns.sh, microk8s-resources/wrappers/microk8s-status.wrapper
The 'dns' addon has been changed to use CoreDNS by default instead of kube-dns. This brings it in line with CoreDNS being the default from Kubernetes v1.13:
https://kubernetes.io/docs/tasks/administer-cluster/coredns/
Relates to: #271
=> Updated to use CoreDNS

microk8s-resources/default-args/kube-proxy, tests/utils.py
Use used userspace proxy mode because it was the oldest proxy mode and displayed better compatibility (in our tests on VMs containers). However, we had reports with:
degraded performance, non-standard behavior (https://github.com/kubernetes/kubernetes/issues/76645) and failing deployments in some platforms (https://github.com/ubuntu/microk8s/issues/140) so we are moving to iptables which is the default.
=> Do iptables by default

tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
Needed because of this upstream PR https://github.com/kubernetes/kubernetes/commit/b2ce446a8811ff65044a30173081df13696d1cce
=> Allow lxc to reach /dev/kmsg

microk8s-resources/actions/coredns.yaml
This makes coredns work if you have RBAC disabled.
This fixes #523
=> Add clusterrole for coredns

snap/hooks/remove
This is a workaround suggested in https://forum.snapcraft.io/t/automatic-snapshot-opt-out/12131/8
Users reported removal takes a lot of time and space. In a quick test on a cluster with istio enabled removal time dropped from 3+ minutes to 38 seconds.
=> Delete containers before removing snap

microk8s-resources/actions/disable.knative.sh
Without this the knative namespaces will stay terminating.
=> Better knative cleanup

microk8s-resources/actions/storage.yaml
When RBAC has been enabled under v1.15.1, persistent volumes can be created using persistentvolumeclaims.
However after the persistentvolumeclaim is deleted, hostpath provisioner deletes the backing directory, but fails to delete the persistent volume due to a 'forbidden' error, e.g.
```
I0730 03:13:43.616042       1 controller.go:869] volume "pvc-0621280e-d5dc-4640-b232-38021643fb65" deleted
I0730 03:13:43.617107       1 controller.go:876] failed to delete volume "pvc-0621280e-d5dc-4640-b232-38021643fb65" from database: persistentvolumes "pvc-0621280e-d5dc-4640-b232-38021643fb65" is forbidden: User "system:serviceaccount:kube-system:microk8s-hostpath" cannot delete resource "persistentvolumes" in API group "" at the cluster scope
```
I was able to work around this by adding the `delete` …
=> allow hostpath provisioner to delete persistent volumes

microk8s-resources/default-args/kube-apiserver
Starting from k8s 1.10 default plugins are enabled unless disabled by "disable-admission-plugins" so "enable-admission-plugins" can be removed.
> For Kubernetes version 1.10 and later, the recommended admission controllers are enabled by default (shown here), so you do not need to explicitly specify them. You can enable additional admission controllers beyond the default set using the --enable-admission-plugins flag (order doesn’t matter).
Links:
- https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
- https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options
=> "enable-admission-plugins" is not needed anymore

microk8s-resources/actions/metrics-server.yaml
Commits:
* Add system:aggregated-metrics-reader Cluster Role
* Bind proxy client user to admin role
Together with #579 fixes #560
Links:
- https://github.com/kubernetes-incubator/metrics-server/blob/v0.3.3/deploy/1.8+/aggregated-metrics-reader.yaml
=> RBAC metrics rolebinding

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.cilium.sh, microk8s-resources/actions/disable.dns.sh, microk8s-resources/actions/disable.helm.sh, microk8s-resources/actions/enable.cilium.sh, microk8s-resources/actions/enable.helm.sh, microk8s-resources/wrappers/microk8s-cilium.wrapper, microk8s-resources/wrappers/microk8s-helm.wrapper, microk8s-resources/wrappers/microk8s-status.wrapper, microk8s-resources/wrappers/run-containerd-with-args, snapcraft.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/test-upgrade.py, tests/validators.py
Add support for enabling/disabling Cilium directly from microk8s. This should greatly simplify the instructions in the current [Cilium getting started guide](http://docs.cilium.io/en/latest/gettingstarted/microk8s/) to just:
1. `snap install microk8s --classic`
1. `microk8s.enable cilium`
This also provides a useful wrapper, `microk8s.cilium` which provides direct CLI access to Cilium without needing to open a shell into the Cilium container.
To install cilium, there are helm charts provided by the Cilium repository. So this PR also provides a way to install helm within the microk8s environment for use from Cilium.
```
$ sudo snap run --shell  microk8s.enable
Enabling Helm
Helm is enabled
Restarting kube-apiserver
Enabling Cilium
Fetching cilium version v1.6.
% Total    % Received % Xferd …
```
=> Add helm, cilium addons

build-scripts/set-env-variables.sh, snapcraft.yaml
These commits improve build caching:
* Don't depend on the microk8s tree for the containerd build, so the part can be cached
* Support specifying `KUBE_SNAP_BINS` to a non-existent directory, in which case the build will create the directory and cache k8s artifacts there. Previously a developer would first have to come up with the cached artifacts somehow, and ensure they weren't deleted, then keep them somewhere safe and specify `KUBE_SNAP_BINS`. This makes the process a bit easier for new developers.
=> Improve build caching

microk8s-resources/wrappers/microk8s-cilium.wrapper
This defines the correct `cilium-health` socket for contacting the
`cilium-health` cluster connectivity API for the output of `cilium status`.
Previously:
```
$ cilium status
KVStore:                Ok   Disabled
ContainerRuntime:       Ok   containerD events watcher: Ok; cri-containerd client: Ok - cri daemon: Ok
Kubernetes:             Ok   1.15 (v1.15.2) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
Cilium:                 Ok   OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPAM:                   IPv4: 2/65535 allocated from 10.244.0.0/16, …
```
=> Fix cilium health cluster status check

microk8s-resources/default-args/etcd, microk8s-resources/default-args/kube-apiserver, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-containerd-with-args, microk8s-resources/wrappers/run-with-config-args, snapcraft.yaml
This is a first pass at getting the microk8s basic services to work in strict mode. As of this time, there are several TODOs to make various snap commands work under strict mode:
* stop use of sudo (grep -r sudo ./microk8s-resources/). Eg, check for root uid and exit if non-root
* stop use of systemctl (grep -r systemctl ./microk8s-resources/, but also meta/hooks). use snapctl instead
* don't run /snap/bin/... commands. Use $SNAP/path/to/thing instead
There are likely other things that should be done. Eg, you may also want to update to not require the use of layouts.
That said, with these changes, I was able to install microk8s in strict mode, create, use and delete a pod (see https://people.canonical.com/~jamie/microk8s/README) and have it all work after reboot. Testing was performed on …
=> miscellaneous updates for strict mode

README.md, microk8s-resources/actions/common/utils.sh, snap/hooks/configure, snap/hooks/install
This PR is based on your feedback @balchua (on slack), @amozoss (on https://github.com/ubuntu/microk8s/issues/606) and @alexmurray. Thank you all.
~~If the *microk8s* group is present at installation time users of that group will be granted access to `microk8s.*` commands.
If the *microk8s* group is not present at installation time, the administrator can later set a group with trusted users with: `sudo snap set microk8s user.group=<GROUP_NAME>`.~~ 
(Updated due to the strict confinement we want to ultimately reach)
The *microk8s* group is created during installation or upgrade of the snap. Users in that group have access to `microks.*` commands. To add users you normally do a `sudo usermod -a -G microk8s $USER`.
Sudo users are always allowed to access MicroK8s.
Let me know what you think.
=> Allow users to be in a group instead of using sudo

scripts/inspect.sh
We accidentally removed the network stats gathering in the latest refactoring. Re-adding it now.
=> Re-instroducing network stats in the inspect script

microk8s-resources/actions/enable.cilium.sh, snap/hooks/configure
@joestringer the cilium addon will not upgrade as expected. To see what happens deploy microk8s from beta enable some addons and cilium and then upgrade refresh to edge:
```
sudo snap install microk8s --classic --beta
sudo microk8s.status --wait-ready
sudo microk8s.enable dns dashboard
sudo microk8s.enable cilium
sudo snap refresh microk8s --channel edge
```
The cilium socket seems to be missing, but I was not able to revive it in an "elegant" way.
This PR will detect if cilium is enabled and and then force a re-enabling/re-installation. Not that pretty but I believe it works.
As this blocks our release cycle (failing upgrades will stop any new releases) I would like to merge it soon and perhaps do a proper fix at a later stage based on your feedback. Many thanks.
=> Re-enable cilium when upgrading

microk8s-resources/wrappers/microk8s-reset.wrapper, tests/test-addons.py
This got broken accidentally as mentioned here https://github.com/ubuntu/microk8s/commit/8173dce3189d376bd0267b9f2d62ef11193d5ada#r34854580 . Thank you @rzr.
=> Fix the reset wrapper - do a proper reset

microk8s-resources/actions/common/utils.sh
Multiple IP addresses causes etcd failed to start.
Some logs
```bash
sudo journalctl -u snap.microk8s.daemon-etcd.service -l --no-pager| tail -n 100
```
Replaced ip address to 555.555.555.555 & 10.10.10.10
> Sep 07 00:33:59 test-server systemd[1]: Started Service for snap application microk8s.daemon-etcd.
> Sep 07 00:33:59 test-server microk8s.daemon-etcd[17830]: + export PATH=/snap/microk8s/825/usr/sbin:/snap/microk8s/825/usr/bin:/snap/microk8s/825/sbin:/snap/microk8s/825/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> Sep 07 00:33:59 test-server microk8s.daemon-etcd[17830]: + PATH=/snap/microk8s/825/usr/sbin:/snap/microk8s/825/usr/bin:/snap/microk8s/825/sbin:/snap/microk8s/825/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> Sep 07 00:33:59 …
=> Return single IP from get_default_ip().

microk8s-resources/actions/common/utils.sh
Multiple IP addresses causes etcd failed to start.
This fixes #440 .
=> Return single IP from get_default_ip(). (#636)

microk8s-resources/actions/enable.linkerd.sh
Some times enabling linkerd fails with: 
```
Enabling Linkerd2
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
DNS is enabled
Unable to install the Linkerd control plane. It appears that there is an existing installation:
Get https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterroles?labelSelector=linkerd.io%2Fcontrol-plane-ns: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
Get https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=linkerd.io%2Fcontrol-plane-ns: …
```
=> Allow for some time slack between dns and linkerd

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.cilium.sh, snap/hooks/configure
Three fixes:
- Problem with cilium where a user in the microk8s group cannot enable it.
```
touch: cannot touch '/var/snap/microk8s/x1/var/lock/no-flanneld': Permission denied
```
- Cleans the cilium installation even if it half done. So we do not get into a broken state.
- sudo use when deleting vxlan links
=> Fixes on cilium

microk8s-resources/actions/dashboard.yaml, microk8s-resources/actions/dns.yaml, microk8s-resources/actions/gpu.yaml, microk8s-resources/actions/ingress.yaml, microk8s-resources/actions/metrics-server.yaml, microk8s-resources/actions/prometheus/0prometheus-operator-deployment.yaml, microk8s-resources/actions/prometheus/grafana-deployment.yaml, microk8s-resources/actions/prometheus/kube-state-metrics-deployment.yaml, microk8s-resources/actions/prometheus/node-exporter-daemonset.yaml, microk8s-resources/actions/prometheus/prometheus-adapter-deployment.yaml, microk8s-resources/actions/registry.yaml, microk8s-resources/actions/storage.yaml, tests/templates/bookinfo.yaml, tests/templates/emojivoto.yaml, tests/templates/ingress.yaml
- Address api version deprications: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
- Fixes: https://github.com/ubuntu/microk8s/issues/632
=> Updates on manifests, depricated apiVersion, hostpath from 1.0.0

microk8s-resources/wrappers/run-flanneld-with-args, snap/hooks/configure
Fixes https://github.com/ubuntu/microk8s/issues/641
Upgrading from 1.13 to 1.16 is failing with: 
```
+ cp -r /snap/microk8s/860/default-args/cni-network/flannel.conflist /var/snap/microk8s/860/args/cni-network/
cp: cannot create regular file '/var/snap/microk8s/860/args/cni-network/': Not a directory
-----)
```
Although this upgrade is not recommended (see https://github.com/ubuntu/microk8s/issues/641) it has to work.
Other fixes
- Use snapctl to restart services in configure hook.
- Flanneld wait for config files before starting.
=> Fixes to allow refresh from 1.13

build-scripts/fetch-other-binaries.sh, microk8s-resources/actions/enable.knative.sh, tests/test-addons.py, tests/utils.py
Two hacks had to go in:
- patch the monitoring.yaml manifest after getting it from the official repo
- cleanup of the `knative-serving` namespace stays in terminating for too long so we introduced some delays.
=> Hacks to get knative 0.9.0 in 1.16 working

microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper
This is most obvious when on a fresh install we do `microk8s.enable dns dashboard`. If the first addon restarts services the second addon may find the cluster in an unresponsive state. With this PR we make sure the cluster is up before enabling each addon. 
Fixes: https://github.com/ubuntu/microk8s/issues/674 and https://github.com/ubuntu/microk8s/issues/513
=> Wait for cluster to be up before we enable/disable addons

microk8s-resources/wrappers/microk8s-enable.wrapper
coredns.yaml is not an addon, it is used as template by the dns addon. We should not be showing it in the list of addons.
Fixes: https://github.com/ubuntu/microk8s/issues/675
=> Filter out coredns from the list of addons

microk8s-resources/actions/common/utils.sh, snap/hooks/install
In issue #686  a user wasn't able to install microk8s in Cent OS 7
due to the openssl config being located in another directory than
Ubuntu. Now it will use the openssl included in the snap making it
that way system independent.
=> Changing Openssl to be system independet

microk8s-resources/actions/common/utils.sh
Redirect these user warnings to stderr so that they can be clearly
interpreted by users (or redirected to ignore separately from command output).
When running as user with insufficient permissions:
```
$ microk8s.status >/dev/null
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user factorio to the 'microk8s' group:
sudo usermod -a -G microk8s factorio
The new group will be available on the user's next login.
$
```
When running as user with sufficient permissions:
```
$ microk8s.status >/dev/null
$
```
In some Cilium developer make targets we use the success of the command to determine whether microk8s is properly set up, and it's useful to get a warning if it failed due to privileges like this.
=> Trivial: Print user-facing errors to stderr

microk8s-resources/wrappers/microk8s-status.wrapper
Hi, this is a fix for #699 so helm shows up the the `.status` command. I built a development snap using the contribution instructions and it was working as expected.
I held off adding it to the addon array on L:34 because it wasn't possible to determine the helm install status by keying off the namespaces or clusterroles. There may be another `kubectl` command that shows the status that I'm not aware of though.
=> add helm to microk8s.status command

microk8s-resources/actions/disable.linkerd.sh, microk8s-resources/actions/enable.linkerd.sh
@balchua, now that we have a separate CA for front-proxy certs and 2.6.0 linkerd. Do you think we could remove the hack of requestheader-allowed-names set to 127.0.0.1.
Thanks.
=> Use the default front-proxy-client cert in linkerd

microk8s-resources/default-args/ctr
Without this patch, `microk8s.ctr` is unable to list any containers on the system because it's looking in the wrong namespace. With this patch, the containers show up when running commands like `microk8s.ctr containers list`.
Fixes: #738
=> Fix default namespace for ctr

microk8s-resources/actions/enable.helm.sh
2.15.1 fixes a regression (https://github.com/helm/helm/issues/6708)  that broke various charts, e.g. stable/redis (https://github.com/helm/charts/issues/18141)
=> Upgrade Helm to v2.15.1

build-scripts/set-env-variables.sh, microk8s-resources/default-args/containerd-template.toml, microk8s-resources/default-args/flannel-template.conflist, snap/hooks/configure, tests/templates/ingress.yaml
Take note of the change in the `containerd-template.toml`.  This new containerd-cri requires that the name must match the image name.
For example:
```
image: 192.169.1.12:32000/my-busybox:1.0
```
In the `containerd-template.toml` the mirror definition must match the registry mirror.
```
[plugins.cri.registry.mirrors."192.168.1.12:32000"]
endpoint = ["http://192.168.1.12:32000"]
```
Addresses issue https://github.com/ubuntu/microk8s/issues/702
=> upgrade containerd to 1.3.0

.travis.yml, docs/build.md, snapcraft.yaml
Allows building on non-xenial hosts without having to run cleanbuild. Cuts rebuild times significantly.
=> Switch snapcraft.yml to base: core

microk8s-resources/actions/enable.helm.sh
Helm 2.x stable is now pinned to 2.16.0. The new version contains some
important fixes that were too large for a patch version bump.
Release notes: https://github.com/helm/helm/releases/tag/v2.16.0
Signed-off-by: Oleg Sidorov <me@whitebox.io>
=> Updated Helm version to v2.16.0

scripts/cluster/join.py, snap/hooks/configure
Currently `args/flanneld` is being created with a the fixed path of the currently installed snap. Ex: 
```
--iface=""
--etcd-endpoints https://10.0.0.28:12379
--etcd-cafile /var/snap/microk8s/982/certs/ca.remote.crt
--etcd-certfile /var/snap/microk8s/982/certs/server.remote.crt
--etcd-keyfile ${SNAP_DATA}/certs/server.key
--subnet-file=${SNAP_COMMON}/run/flannel/subnet.env
```
The paths for `--etcd-cafile` and `--etcd-certfile` become invalid after the snap upgrades and flanneld fails to start.
=> Create flanneld config file with using SNAP_DATA env variables

scripts/cluster/join.py, snap/hooks/configure
* Create flanneld config file with using SNAP_DATA env variables as to not
break during snap upgrades.
* Handle upgrade of clustered flannel
* Remove old config before adding it again
=> Create flanneld config file with using SNAP_DATA env variables (#797)

microk8s-resources/wrappers/microk8s-reset.wrapper
These non-namespaced objects were left behind after a reset.
=> Reset StorageClasses and PriorityClasses

snapcraft.yaml
Reverts ubuntu/microk8s#795
We need to wait for the snapstore to accept slots in classic snaps.
=> Revert "Add content interface slot for Juju to plug to;"

scripts/inspect.sh
Extra checks for Fedora as since Fedora 31 Cgroups v1 support is not enabled and Docker does not support Cgroups v2 yet 
Relates to: #822
=> cgroups v1 check

microk8s-resources/actions/enable.kubeflow.sh
To prevent issues when someone has a folder named `kubeflow` in their working directory.
Fixes #859
=> Include charm store in bundle name

snapcraft.yaml
Reapply the PR https://github.com/ubuntu/microk8s/pull/795 now that the snapstore allows interfaces for classic snaps.
=> Add content interface slot for Juju to plug to;

microk8s-resources/default-args/containerd-env
Juju controllers need a higher memlock limit.
Setting to 16384 (from a default of 64) fixes the issue.
=> Add ulimit -l 16384 to containerd-env

microk8s-resources/actions/ingress.yaml
ingerss-nginx needs configmap create permission.
> Namespace Permissions
> These permissions are granted specific to the nginx-ingress namespace. These permissions are granted to the Role named nginx-ingress-role
> ...
> configmaps: get, update (for resourceName ingress-controller-leader-nginx)
> configmaps: create
>
> https://kubernetes.github.io/ingress-nginx/deploy/rbac/
Otherwise, ingress-nginx cannot create ` ingress-controller-leader-nginx` configmap and gives error per twenty seconds.
```
$ kubectl logs -n ingress  nginx-ingress-microk8s-controller-2hkqj nginx-ingress-microk8s
...
E0131 16:46:46.042945       6 leaderelection.go:328] error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:ingress:nginx-ingress-microk8s-serviceaccount" …
```
=> Allow nginx-ingress-microk8s-role to create configmaps

microk8s-resources/default-args/kubelet
This flag is deprecated [at least since 2017 Dec](https://github.com/kubernetes/kubernetes/commit/8ec1958667e66fb3da2a1f1428998f59f8b027f2#diff-48b7d75949f67a9adceea2ba834c8e35), but is still needed to tell cAdvisor the containerd socket path. As things stand, with cAdvisor enabled, we can get more memory stats about containers (e.g. `/stats/summary` endpoint).
```json
$ curl http://localhost:10255/stats/summary
{
...
"pods": [
...
{
"podRef": {
"name": "nginx-deployment-7f5f4c6d4b-vh764",
...
},
"startTime": "2020-01-30T18:22:04Z",
"containers": [
{
"name": "nginx",
"startTime": "2020-01-30T18:22:05Z",
"memory": {
"time": "2020-01-30T18:27:21Z",
"workingSetBytes": 2183168
},
},
...
],
...
}
]
}
```
```json
$ curl http://localhost:10255/stats/summary
{
...
"pods": [
...
{
"podRef": { …
```
=> Add  --containerd flag to work cAdvisor correctly

microk8s-resources/actions/enable.cilium.sh
Cilium addon uses helm for inflating YAML. This PR updates dependency to new helm version (helm3).
```console
Enabling Helm 3
Fetching helm version v3.0.2.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0  5241k      0  0:00:02  0:00:02 --:--:-- 5242k
Helm 3 is enabled
Restarting kube-apiserver
Restarting kubelet
Restarting containerd
Enabling Cilium
Fetching cilium version v1.6.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    237      0 --:--:-- --:--:-- --:--:--   237
100 22.6M    0 22.6M    0     0  5512k      0 --:--:--  0:00:04 --:--:-- 7473k
Deploying …
```
=> Use helm3 instead of helm2 to enable cillium

microk8s-resources/wrappers/microk8s-enable.wrapper, snap/hooks/configure
We cannot call microk8s.enable on an already enabled addon. Cilium needs to be re-enabled every time we upgrade.
=> Upgrading cilium while it is already enabled

microk8s-resources/actions/enable.metallb.sh
Allows other scripts such as kubeflow to lazily ensure it's enabled.
=> Check if metallb is already enabled when enabling it

snapcraft.yaml
Fails fast instead of waiting for a Juju bootstrap to fail without a great error message.
Fixes #943
=> Check machine architecture before enabling Kubeflow

installer/windows/microk8s.iss
Tested on the laptop.  We now offer a tick box to setup (i.e. `microk8s install`), after install.  Then also automatically clean up at uninstall.
=> Automatically setup and tear down MicroK8s VM in Windows installer

microk8s-resources/default-args/containerd-template.toml, microk8s-resources/wrappers/run-containerd-with-args
This is a workaround to allow microk8s to run on ZFS systems.
See issue: #401
Using the zfs snapshotter would be another option, but currently
it seems that the zfs snapshotter requires it's own dedicated filesystem
and is still missing features such as Usage().
https://github.com/containerd/zfs/issues/17
=> Use native containerd snapshotter if ZFS is detected

microk8s-resources/actions/common/utils.sh
When users start using MicroK8s with sudo ~/.kube is created with root permissions. If they later join the microk8s group accessing the ~/.kube directory is blocked and the interaction with the cli is is very slow to the point many report commands not working. With this PR we ask users to grant access to their user when switching to the microk8s group.
Fixes: https://github.com/ubuntu/microk8s/issues/1023
=> Ask users to get ownership of their .kube when joining the microk8s group

microk8s-resources/actions/enable.metallb.sh, microk8s-resources/actions/metallb.yaml
See #1017 - metallb fails to enable correctly due to privilege escalation on Xenial.
Note that this fix is similar to #551 which fixed a similar privilege escalation issue for coredns on Xenial.
=> Fix privilege escalation of metallb on xenial

microk8s-resources/wrappers/addon-lists.yaml
This PR introduces some minor updates to the yaml list of addons:
- remove the ":" causing non valid yaml output
- update the linkerd version
- juju is not an addon anymore
=> Fixes and updates in addons yaml

scripts/wrappers/status.py
With this PR we maintain the old CLI interface and out put for `microk8s.status` and `microk8s.status --yaml`. 
We introduce a `--format` argument with which you can select a human readable `pretty` output format (that includes the addon descriptions) or select the new yaml format with `yaml`
Fixes: https://github.com/ubuntu/microk8s/issues/1041 and https://github.com/eclipse/che/issues/16408
=> Keep the existing interface in microk8s.status

tests/test-distro.sh
Two things we improve:
- Do the upgrade test before the testing of addons. The upgrade test fails more often so we try to fail fast.
- The clusters test part was a place holder for future tests but it was not providing an value. We remove it. Proper cluster testing is in https://github.com/ubuntu/microk8s/tree/feature/cluster-test and needs multipass.
=> Improve distributions tests

microk8s-resources/actions/enable.kubeflow.sh
It will be required eventually, but for now it's causing issues with Juju and 1.18.
=> Don't enable RBAC for kubeflow deployments

microk8s-resources/wrappers/run-cluster-agent-with-args
When using the /configure REST endpoint of cluster-agent, the subprocess for calling the microk8s-enable-wrapper command was timing out due to $HOME env var not being injected. By setting the HOME env var in run-cluster-agent-with-args script, the issue is fixed.
Testing
Set the callback-token:
`sudo echo "xyztoken" > /var/snap/microk8s/current/credentials/callback-token.txt`
and test with curl:
`curl -k -v -d '{"callback":"xyztoken","addon":[{"name":"dns", "enable":true}]}' -H "Content-Type: application/json" -X POST https://127.0.0.1:25000/cluster/api/v1.0/configure`
Fixes: https://github.com/ubuntu/microk8s/issues/937
=> Fix configuring addons

microk8s-resources/actions/enable.registry.sh, microk8s-resources/actions/registry.yaml, tests/validators.py
fixes #926 
Description
feat: 
Add an option to the `microk8s.enable registry` command to customize the size of the container registry the default value is still set to 20Gi and the pvc cannot be lower than 20Gi
Add a test to assert that the value is equal or higher to 20Gi
=> feat: Add an option to customize the size of the container registry

microk8s-resources/wrappers/microk8s-enable.wrapper
In microk8s-enable-wrapper script, two if conditions we checking for same thing: "if an addon is already enabled"
Kept the latest one committed.
Screenshot from testing local build:
=> Keep only one if-condition for checking when an addon is enabled

installer/build-linux.sh, installer/cli/microk8s.py, installer/common/definitions.py, installer/vm_providers/_base_provider.py
This PR adds the `--channel` option to `microk8s install` eg
```
microk8s install --cpu 2 --mem 4 --channel 1.18/stable
```
Fixes: https://github.com/ubuntu/microk8s/issues/1072
=> Accept --channel in microk8s install

installer/vm_providers/_base_provider.py
This PR sets the VM name created by the installers to `microk8s-vm`. There are two reasons:
- When RBAC is enabled the capital letters of `MicroK8sVM` render the k8s node inaccessible. The error reported by kubelet is:
```
Apr 18 13:17:23 MicroK8sVM microk8s.daemon-kubelet[3556]: E0418 13:17:23.302029    3556 reflector.go:178] object-"kube-system"/"default-token-zdmcr": Failed to list *v1.Secret: secrets "default-token-zdmcr" is forbidden: User "system:node:MicroK8sVM" cannot list resource "secrets" in API group "" in the namespace "kube-system": no relationship found between node "MicroK8sVM" and this object
```  
See https://github.com/ubuntu/microk8s/issues/902
- Stay consistent with the current instructions. See issue https://github.com/ubuntu/microk8s/issues/1085
=> Change VM name of installers to lowercase

installer/cli/microk8s.py, installer/common/definitions.py
Two minor fixes in the output of `microk8s --help`:
1. Added the description of helm3
1. Filtered out the `microk8s` command
=> Fixes in --help in installer

snapcraft.yaml
This is was requested for the juju integration.
=> Rename microk8s-info slot for juju

microk8s-resources/actions/ingress.yaml
#1149 
Adds the ingress controller arguments and ConfigMaps necessary to support ingress of TCP and UDP. Individual services can then be proxied by patching the Ingress Controller Service (Daemonset in MicroK8s) and the relevant ConfigMap.
Configuration details at:  
https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
and further examples at:
https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/
The configuration in MicroK8s is slightly different from the above links. This is shown in the following example for exposing Redis with the Ingress Controller.
```
$ k -n pi get service
NAME    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
redis   ClusterIP   10.152.183.238   <none>        6379/TCP   10h
```
```
---
apiVersion: apps/v1
kind: …
```
=> Configure NGINX Ingress Controller to expose TCP and UDP services.

microk8s-resources/wrappers/run-with-config-args
With this PR we make sure packets can be forwarded between nodes when forming the calico cluster.
=> Ensure packet forwarding is enabled when transitioning to calico

upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh
Until we decide on how the UX would look like I cannot be sure what the context of the transition scripts would be. With this PR all scripts assume they run within a microk8s context and as root.
=> Fix transition to calico permissions

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-ctr.wrapper, microk8s-resources/wrappers/run-containerd-with-args
Some ctr commands use a snapshotter locally. By default this is `overlayfs`, but when using zfs we need to use `native` (or `zfs`) snapshotter.
#1000 fixes this issue for containerd, but ctr doesn't use the containerd config.
Commands affected by this are:
- ctr containers create
- ctr images check
- ctr images import
- ctr images pull
- ctr run
- ctr snapshots
Snapshotter selection should probably be consolidated into one place.
=> Fix ctr using overlayfs on zfs

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, scripts/cluster/join.py, snapcraft.yaml
With this PR:
- We inform the dqlite cluster of a departing node.
- Start does not uncordon the node as this was causing only the first node to uncordon
- Fix credential permissions of the dqlite backend
=> Have dqlite node gracefully depart a cluster

microk8s-resources/actions/dashboard.yaml, microk8s-resources/actions/disable.dashboard.sh, microk8s-resources/actions/enable.dashboard.sh, microk8s-resources/wrappers/addon-lists.yaml, tests/validators.py
Upgrade dashboard to v2.0.0
Remove influx, heapster and grafana.
Enable metrics-server when enabling dashboard add-on.
=> Upgrade and cleanup dashboard

tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
Newer kernels do not have this module anymore.
=> Remove nf_conntrack_ipv4 from lxc profiles

upgrade-scripts/001-switch-to-dqlite/commit-master.sh, upgrade-scripts/001-switch-to-dqlite/commit-node.sh, upgrade-scripts/001-switch-to-dqlite/prepare-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/commit-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/description.txt, upgrade-scripts/002-switch-to-flannel-etcd/prepare-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/prepare-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-node.sh
This PR includes a set of scripts that would allow to transition a *single* node from a setup with dqlite+calico to etcd+flannel. This is needed when a node departs a cluster and needs to get back to its prior state. These scripts will be exercised when the user calls `microk8s disable ha-cluster`.
In case the transition to etcd+flannel fails we have a rollback script to bring the current state back.
=> Transition scripts from dqlite and calico to flannel and etcd

microk8s-resources/wrappers/microk8s-remove-node.wrapper, scripts/cluster/join.py
Wen removing a dqlite node we need to:
- fail if the node is present on the dqlite cluster and ask the user to call `microk8s.leave` from the departing node.
- if the dqlite node has crashed and is not available anymore, allow the forceful removal of the node with the `--force` flag. 
A node to be removed should first un-register with dqlite and we should be certain that node will not try to reenter the cluster.
=> Remove crashed nodes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-leave.wrapper, scripts/cluster/agent.py, scripts/cluster/join.py, snap/hooks/configure
A few fixes in this PR:
- we make sure dqlites storage directory `${SNAP_DATA}/var/kubernetes/backend/ ` has the right permissions so commands like `microk8s.leave` can reset it.
- when joining a dqlite cluster you are asked to first enable ha "Please, retry after enabling HA on this joining node with 'microk8s enable ha-cluster'."
- stop poluting stdout/stderr from subprocess.check_call
=> Improving the HA UX experience

scripts/inspect.sh
Flannel and etcd are not running in HA, they should not be reported as error.
=> No not inspect etcd and flannel when in HA mode

build-scripts/build-k8s-binaries.sh
After it is copied to KUBE_SNAP_BINS, this fixes the issue https://github.com/ubuntu/microk8s/issues/1223
=> clean up kubernetes _output directory 

installer/windows/microk8s.nsi
User feedback shows that silent isn't passed through bundled installers.
=> Force passthrough of silent install to multipass

docs/build.md
Added a few small changes to build documentation to cover things I ran into building, namely:
- install snapcraft
- add user to LXD group so they can access LXD during build
- line to show how to install the resulting package (there is one in another section, but thought it'd be good to have it up top in regular build instructions)
=> Small tweaks to build documentation

microk8s-resources/actions/disable.ingress.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml
Added support for optional NGINX Ingress Controller default certificate.
See https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate
The new, optional key-value pair is parsed in [`enable.ingress.sh`](https://github.com/marcobellaccini/microk8s/blob/master/microk8s-resources/actions/enable.ingress.sh) in the same way as in [`enable.host-access.sh`](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.host-access.sh).
Usage example:
`microk8s.enable ingress:defaultcert=namespace/secretname`
=> Support for NGINX Ingress Controller default certificate

microk8s-resources/wrappers/microk8s-refresh-certs.wrapper
The definition of the long option `--check` for the (great) `refresh-certs` command (as introduced in #1159) included an excessive trailing colon, making it require an argument:
```text
$ microk8s refresh-certs --check
--check: option '--check' requires an argument
$ microk8s refresh-certs -c
The CA certificate will expire in 3649 days.
```
From `man getopt`, emphasis mine:
> `-l`, `--longoptions` _longopts_
>
> The long (multi-character) options to be recognized. More than one option name may be specified at once, by separating the names with commas. This option may be given more than once, the `longopts` are cumulative. **Each long option name in longopts may be followed by one colon to indicate it has a required argument**, and by two colons to indicate it has an optional argument. …
=> Fix long option "--check" of refresh certs command

snapcraft.yaml
This makes gpu work out of the box at least on ubuntu 20.04
=> Update nvidia packages

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/enable.kubeflow.sh, microk8s-resources/actions/ingress.yaml, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py, snap/hooks/configure, snapcraft.yaml
Configuration should be done at the beginning, when you have one node.
The cluster agent port should be the same across all nodes because there is no single configuration point.
=> Rebase and add port management for dqlite-cluster agent

snapcraft.yaml
Reverts ubuntu/microk8s#1299
@joedborg, @mar-kolya I am afraid I have to revert this PR. Although it works for me that I am in 20.04 we get reports we are breaking old 18.04 deployments [1]
[1] https://github.com/ubuntu/microk8s/issues/1342
=> Revert "Update nvidia packages"

microk8s-resources/actions/disable.cilium.sh, microk8s-resources/actions/disable.multus.sh, microk8s-resources/actions/enable.cilium.sh, microk8s-resources/actions/enable.multus.sh, microk8s-resources/actions/multus.yaml, microk8s-resources/default-args/containerd-template.toml, microk8s-resources/default-args/kubelet, microk8s-resources/wrappers/addon-lists.yaml, microk8s-resources/wrappers/run-flanneld-with-args, snap/hooks/configure, tests/templates/multus-alpine.yaml, tests/templates/multus-networks.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/test-upgrade.py, tests/validators.py, upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh
This PR creates a new add-on that installs the Multus CNI plugin.  Multus CNI enables attaching multiple network interfaces to pods in Kubernetes (details here: https://github.com/intel/multus-cni).  The install is transparent and the current CNI plugin is carried forward as the default in Multus.  With Multus installed users can easily add multiple interfaces to pods using varying CNI plugins (like bridge, macvlan, ipvlan, ptp, etc.) all of which wasn't possible previously in microk8s without some hacking. 
I've sorted out enable/disable compatibility with the cilium (the only other CNI add-on) so either one or both may be enabled simultaneously.  It may make sense to make a more structural changes to store CNI plugins in SNAP_DATA in general, but I'll save that for a later PR.
Multus …
=> Add new add-on for Multus CNI

microk8s-resources/default-args/containerd-template.toml, microk8s-resources/default-args/kube-apiserver, snap/hooks/configure, snap/hooks/install, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh
Start microk8s with calico and dqlite without the need to `microk8s enable ha-cluster`.
`microk8s disable ha-cluster` will get you back to etcd+flannel
=> Start dqlite and calico by default

tests/test-upgrade.py
This will guard against issues like https://github.com/ubuntu/microk8s/issues/1293 . We start from an old release and refresh until the latest snap. The configure hook on all releases in exercised during this test.
=> Test the refresh path from an old track (1.14) all the way to now

scripts/wrappers/status.py
This PR updates the microk8s.status command in the following way:
The `--format short` does not change, is the old default output. It is short, so it does not need to report HA status, plus it can be used for backwards compatibility
```
ubuntu@ip-172-31-24-191:~$ sudo microk8s.status --format short | head -n 20
microk8s is running
addons:
ha-cluster: enabled
cilium: disabled
dashboard: disabled
dns: disabled
fluentd: disabled
gpu: disabled
helm: disabled
helm3: disabled
host-access: disabled
ingress: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
multus: disabled
```
The new default output is the same as `--format pretty`:
```
ubuntu@ip-172-31-24-191:~$ sudo microk8s.status
microk8s is running …
```
=> Remove the ha-cluster subcommand from status

.github/workflows/build-snap.yml
Tests are running on GH with this PR.
We also run the refresh path test where we start from 1.14 and upgrade all the way to the snap just built.
=> Test on GH

scripts/cluster/agent.py, scripts/cluster/join.py
This should address the comment at https://github.com/ubuntu/microk8s/issues/1127#issuecomment-648415386
Note that this is a partial fix because the first node to which other nodes connect does not set the `--hostname-override` automatically. The admin should do that. The same is expected in the current (non-ha) clustering.
=> Handle non-resolvable node names

scripts/cluster/join.py
Running microk8s on certain distributions such as Centos 7.4, resulted
in failure to execute openssl. This happened because the path to
openssl was not being correctly set within the snap. As a result
either no openssl was found or the wrong one was selected leading
to linker relocation errors.
This commit fixes the issue by specifying the full path to openssl.
Fixes: https://github.com/ubuntu/microk8s/issues/1270
=> Fix path to openssl

installer/common/definitions.py, microk8s-resources/actions/disable.ambassador.sh, microk8s-resources/actions/enable.ambassador.sh, microk8s-resources/wrappers/addon-lists.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/test-upgrade.py, tests/validators.py
This PR adds support for installing [Ambassador](https://getambassador.io/), an API Gateway and Ingress Controller, in microk8s.
Ambassador is installed via the Ambassador Operator which is the recommended way of installing Ambassador - it makes sure users always have the latest version of Ambassador installed and takes care of the update schedule as well.
=> Support for Ambassador API Gateway and Ingress Controller

scripts/cluster/common/utils.py, scripts/cluster/distributed_op.py
This PR Fixes: https://github.com/ubuntu/microk8s/issues/1402.
Uses the node IP instead of hostname to interact with the cluster-agent.
=> fix enabling of dns when running HA.

.travis.yml
We reduce the tests in Travis so we do not hit the respective test timeout.
Upgrades are tested in GH [1] so this PR does not have an imparct in test coverage.
[1] https://github.com/ubuntu/microk8s/blob/master/.github/workflows/build-snap.yml#L42
=> Do not test upgrades on Travis

microk8s-resources/wrappers/control-plane-kicker, scripts/wrappers/common/utils.py, scripts/wrappers/control-plane-kicker.py, scripts/wrappers/status.py, snap/snapcraft.yaml
Only the dqlite voters will run the controller manager and the scheduler. Running three instances of those services should be enough.
=> Stopping control plane on HA

scripts/inspect.sh
#1404 
**Output of `microk8s.inspect`**
```root@issue-1404:~# microk8s.inspect
Inspecting Certificates
Inspecting services
Service snap.microk8s.daemon-cluster-agent is running
Service snap.microk8s.daemon-containerd is running
Service snap.microk8s.daemon-apiserver is running
Service snap.microk8s.daemon-apiserver-kicker is running
Service snap.microk8s.daemon-proxy is running
FAIL:  Service snap.microk8s.daemon-kubelet is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelet
Service snap.microk8s.daemon-scheduler is running
Service snap.microk8s.daemon-controller-manager is running
Service snap.microk8s.daemon-flanneld is running
Service snap.microk8s.daemon-etcd is running
Copy service arguments to the final report tarball
Inspecting AppArmor …
```
=> check for possible missing profile with vanilla LXD container

microk8s-resources/actions/enable.kubeflow.sh
Follow-up to #1441, which missed converting this variable usage.
=> Fix Kubeflow arg handling

scripts/wrappers/control-plane-kicker.py
This is a bug fix. If you call `microk8s status` without `sudo` from a user in the `microk8s` group you get back an exception saying `info.yaml` inside the dqlite storage directory cannot be accessed.
```
$ microk8s.status
microk8s is running
Traceback (most recent call last):
File "/snap/microk8s/1564/scripts/wrappers/status.py", line 242, in <module>
print_pretty(isReady, enabled, disabled)
File "/snap/microk8s/1564/scripts/wrappers/status.py", line 51, in print_pretty
info = get_dqlite_info()
File "/snap/microk8s/1564/scripts/wrappers/common/utils.py", line 71, in get_dqlite_info
with open("{}/info.yaml".format(cluster_dir), mode='r') as f:
PermissionError: [Errno 13] Permission denied: '/var/snap/microk8s/1564/var/kubernetes/backend/info.yaml'
```
The dqlite daemon runs as root so its …
=> Change ownership of files under the dqlite path

scripts/cluster/join.py
When joining an HA cluster we print a  `Contacting cluster at <node>` right at the beginning so we do not leave the user wondering if the command works or not.
```
$ sudo microk8s join 10.228.72.149:25000/c30b882c33b126b388af31c61573d4f6
Contacting cluster at 10.228.72.149
Waiting for node to join the cluster. .. .. 
```
=> Add message in joining

scripts/cluster/distributed_op.py
This PR changes the error message shown to the user in the case of an error:
```
ubuntu@ip-172-31-40-63:~/microk8s$ microk8s.enable dashboard
Enabling Kubernetes Dashboard
Enabling Metrics-Server
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.apps/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created …
```
=> Handle not reachable nodes

scripts/wrappers/common/utils.py
This PR fixes the bug when `microk8s status -wait-ready` is executed.  It waits for the kubernetes node to report `Ready` state.
=> Bugfix status 

.travis.yml
Adding verbose output will help travis not timeout due to no output..... I hope.
=> Enable snapcraft verbose output

scripts/cluster/join.py
We should not allow a node to leave the cluster (`microk8s.leave`) in the case where:
- That node is the leader
- There are no other voters to take over leadership
- There are non-voters that need the leader
=> microk8s.leave single leader guard

microk8s-resources/actions/disable.cilium.sh, microk8s-resources/actions/enable.cilium.sh
Enabling and disabling cilium works on a single node cluster with this PR. I think that was always the case.
Fixes: https://github.com/ubuntu/microk8s/issues/1447
=> Fix cilium in an ha cluster

microk8s-resources/wrappers/microk8s-dbctl.wrapper, scripts/wrappers/dbctl.py, snap/snapcraft.yaml, tests/test-addons.py, tests/test-cluster.py
A dbctl command is added to take backups and restore the dqlite db.
```
$ microk8s dbctl --help
usage: microk8s dbctl [-h] [--debug] {restore,backup} ...
backup and restore the Kubernetes datastore
optional arguments:
-h, --help        show this help message and exit
--debug           print debug output
commands:
{restore,backup}  backup and restore operations
```
=> dbctl for dqlite backup and restore

microk8s-resources/actions/enable.metallb.sh, microk8s-resources/actions/metallb.yaml, microk8s-resources/wrappers/addon-lists.yaml, tests/test-addons.py, tests/test-upgrade.py
This PR add CIDR support when specifying IP addresses.  Also upgrades metallb v0.9.3.
=> Update MetalLB to v0.9.3 and add support for CIDR notation

build-scripts/set-env-variables.sh
This PR fixes the multiple bug reports relating to containerd not pulling over HTTP, even when forced (https://github.com/containerd/cri/issues/1433).
Fixes: https://github.com/ubuntu/microk8s/issues/1444
=> Update containerd to 1.3.7

microk8s-resources/actions/enable.registry.sh
Fixes https://github.com/ubuntu/microk8s/issues/196
I tested this a little bug a little bit with different microk8s channels. This comment (https://github.com/ubuntu/microk8s/issues/196#issuecomment-590403234) was particularly helpful in confirming that there's some underlying kubernetes networking issue, rather than something specific to `docker push`.
I can definitely reproduce the problem on --channel=1.17/stable. It might be fixed on --channel=1.18/stable, but supposedly ipv6 support on v1.18 is still in beta, so it seems safer to error on v1.18 too.
=> enabling the registry should fail if localhost can resolve to an ipv6 address

microk8s-resources/actions/disable.registry.sh, microk8s-resources/actions/registry-help.yaml, microk8s-resources/actions/registry.yaml, microk8s-resources/wrappers/apiservice-kicker
Fixes https://github.com/ubuntu/microk8s/issues/1173
=> add support for local registry discovery

snap/hooks/configure
Multus needs to be reenabled on an update. For this the API server should be up.
We wait for the API server for a minute.
=> Fix multus update

microk8s-resources/actions/disable.fluentd.sh
Fluentd delete followed by an immediate reset causes some pods to stay in "terminating" state.
=> Add delay for the fluentd deletion

microk8s-resources/actions/enable.multus.sh
Fixes issue #1495.
Changes the multus daemon set to use the "current" path symlinks for its mounts and arguments.  This should allow it to survive refreshes and upgrades without needing to be disabled/re-enabled.
=> configure multus to use symlinked current SNAP_DATA locations

snap/hooks/configure
This PR transitions a cluster to use token auth only.
This PR should be merged with the v1.19 release
=> Configure existing deployments to use only token auth

build-scripts/fetch-other-binaries.sh, snap/snapcraft.yaml
Moves pulling in of a few extra non-k8s binaries to their own separate snapcraft steps. This will additionally speed up rebuilds when changing any files other than those under build-scripts/.
=> Move other binaries to separate snapcraft part

build-scripts/build-k8s-binaries.sh, snap/snapcraft.yaml, tests/test-addons.py
Since these don't rely on local source code changes other than what's under build-scripts/, if we build these in a separate snapcraft part, we won't have to rebuild them when making changes in most of the codebase. Building these binaries currently takes the majority of the time spent doing incremental rebuilds.
=> Build K8s binaries in separate build step

microk8s-resources/wrappers/microk8s-start.wrapper, scripts/inspect.sh
Adding an additional check to ensure that memory cgroup is explicitly enabled if running on ARM architecture (RPi or any other), as it's not enabled on ARM systems by default (this is explicitly noted in the microk8s docs: https://microk8s.io/docs/install-alternatives#heading--arm and causing issues like https://github.com/ubuntu/microk8s/issues/1347)
=> Add memory cgroup check

.gitignore, installer/.gitignore, installer/cli/microk8s.py, installer/vm_providers/_multipass/_multipass.py
Not sure how this flew under the radar for so long. 
`start` now added to the multi-OS wrapper and the VM will be re-launched if someone tries to run a command on a stopped cluster.
=> Adding start wrapper

scripts/wrappers/upgrade.py, snap/hooks/configure, upgrade-scripts/001-switch-to-dqlite/commit-master.sh
This PR addresses a few bugs on the transition of a cluster from non-HA to HA.
- If one starts an HA transition and never finishes it (calls `microk8s.enable ha-cluster` on the master node but does not transition the nodes to HA) any refreshes on the nodes will fail if they are following a 1.19+ track.
- The upgrade process was not triggered on all nodes.
- If the node we call `microk8s enable ha-cluster` was already on a non-HA cluster that gets upgraded to HA it may have etcd disabled because it may have already transitioned to dqlite. In this case we should not try to take a backup of etcd.
The workaround for all the above is after we remove the node from the cluster via `microk8s.leave` we `snap remove microk8s` and reinstall so we join a clean node.
=> Fix upgrade from non-HA to HA

microk8s-resources/wrappers/apiservice-kicker
The apiserver kicker complains that:
```
error: error running snapctl: unknown service: "microk8s.daemon-etcd.service"
```
=> Apiserver kicker to restart the right services

microk8s-resources/wrappers/run-containerd-with-args, tests/test-upgrade-path.py, tests/utils.py
Running containerd unconfined allows us to handle AllowPrivilegeEscallation flag correctly.
Fixes https://github.com/ubuntu/microk8s/issues/784
=> Run containerd unconfined

microk8s-resources/wrappers/apiservice-kicker
api-service-kicker check for the local-registry if installed in `kube-public`
=> fix the kubepublic name to kube-public

microk8s-resources/wrappers/microk8s.wrapper, scripts/inspect.sh
_microk8s inspect --help_   doesn't invoke the help function.  The arguments aren't passed to the inspect script by the microk8s wrapper.
=> Fix help option for inspect command

microk8s-resources/wrappers/apiservice-kicker
before this change, the apiservice-kicker would sometime reset the registry configmap even when the registry existed
=> apiservice-kicker: fix a race condition

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml, snap/snapcraft.yaml, tests/test-addons.py
This upgrade now enables Linkerd on `arm64`.  I need help to test this in an `arm64` based architecture.  
See Linkerd 2.9.0 announcement [here](https://linkerd.io/2020/11/09/announcing-linkerd-2.9/)
=> upgrade linkerd 2.9.0

snap/snapcraft.yaml
Dqlite is not using a patched sqlite anymore so we just need to use the upstream one.
=> Build the upstream sqlite and not the patched one

microk8s-resources/actions/disable.ingress.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml, tests/templates/ingress.yaml
Changes:
- Nginx Ingress has a new home.  quay repository is now read only.  Last image is `0.33.0`
- Upgraded nginx ingress to `v0.35.0`
- Introduce the use of `IngressClass`
- Use `networking.k8s.io/v1`
=> update ingress, relocate to the new repository k8s.gcr.io

microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper
Works towards addressing cases similar to https://github.com/ubuntu/microk8s/issues/1748
- `microk8s reset` will not run on multinode clusters. resetting means we revert to a single node cluster and this is not the right way to bring down a multi-node cluster.
- providing more arguments on `microk8s reset` will cause the reset to fail, eg if the user does a `mcirok8s reset healp` the reset will not happen
- improve wording in error messages in clustered node.
=> Do not reset multi-node clusters

upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh
At the beginning of these scripts, the "echo" command mentions "dqlite upgrade" while they are about switching to flannel-etcd.
This seems to be a copy/paste from similar scripts in upgrade-scripts/001-switch-to-dqlite.
I also noticed a small typo at the end of `rollback-master.sh` that I fixed at the same time.
See https://github.com/ubuntu/microk8s/issues/1752
I used `flannel-etcd` instead of dqlite to update the text, in an attempt to keep it consistent with the other files. But please let me know in case there are better descriptions that would apply here.
=> update echo text in flannel-etcd upgrade scripts

microk8s-resources/wrappers/microk8s-linkerd.wrapper, tests/test-addons.py
This is a bug fix to allow linkerd cli on arm architectures.
Linkerd on arm is looking good.  I have also enabled the test on arm.
=> [Fix] Enable linkerd cli on arm architecture

tests/lxc/install-deps/ubuntu_16.04
The reason pytest isn't running on xenial is because importlib-metadata doesn't support python 3.5 on pypy any longer. I've pinned the version here which fixes the issue. It's worth considering using apt packages rather than pypy when available for this very reason. I didn't make that change here, just fixed the existing setup.
=> Fix pytest dependency for xenial testing

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.cilium.sh
This reverts commit 2d3f12512c16 ("Revert "upgrade cilium to version 1.8.3
(#1583)" (#1784)") and resolves the upgrade problem by specifying this
upgrade flag as documented in the [upgrade guide](0):
--set agent.keepDeprecatedLabels=true
[0]: https://docs.cilium.io/en/v1.7/install/upgrade/#important-changes-required-before-upgrading-to-1-7-x
Co-Authored-by: balchua <balchua@yahoo.com>
=> Reintroduce cilium upgrade to 1.8

microk8s-resources/actions/enable.prometheus.sh, microk8s-resources/wrappers/addon-lists.yaml, snap/snapcraft.yaml, tests/test-addons.py
The enable script will use the following multi-arch images:
*  `gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics:v1.9.7` instead of `quay.io/coreos/kube-state-metrics:v1.9.5`
*  `quay.io/brancz/kube-rbac-proxy:v0.8.0` instead of `quay.io/coreos/kube-rbac-proxy:v0.4.1`
The image `quay.io/brancz/kube-rbac-proxy:v0.8.0` is also referenced now in the `kube-prometheus` master branch.  The image is referenced from the author of the kube-rbac-proxy repository.
Tested it in AWS arm EC2 and it is looking good.
```shell
ubuntu@ip-172-31-18-25:~$ uname -a
Linux ip-172-31-18-25 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:08:09 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@ip-172-31-18-25:~$ kubectl -n monitoring get pods -o wide
NAME                                  READY   STATUS …
```
=> Enable prometheus on arm64 architecture

.github/workflows/test-kubeflow.yaml
Also includes drive-by change for ignoring doc changes
=> Skip CI checks requiring AWS on forked PRs

tests/test-upgrade.py
Tow reasons for this:
- We want to test the upgrade of the default CNI as this is what most people will have
- Cilium introduces some flakiness in our tests
=> Do not test the upgrade of cilium

snap/snapcraft.yaml, tests/test-addons.py
Otherwise, it pulls in a version of files such as `enable.kubeflow.sh` that conflicts with what is sitting in the git repo.
For example:
```
Failed to stage: Parts 'containerd' and 'microk8s' have the following files, but with different contents:
microk8s-resources/actions/enable.kubeflow.sh
Snapcraft offers some capabilities to solve this by use of the following keywords:
- `filesets`
- `stage`
- `snap`
- `organize`
To learn more about these part keywords, run `snapcraft help plugins`.
```
=> Limit scope of containerd part

installer/common/definitions.py
I was browsing through the `microk8s --help` commands and couldn't find an entry for dbctl: 
```
$ microk8s --help
Usage: microk8s [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
install         Installs MicroK8s. Use --cpu, --mem, --disk and --channel to configure your setup.
uninstall       Removes MicroK8s
add-node        Adds a node to a cluster
cilium          The cilium client
config          Print the kubeconfig
ctr             The containerd client
dashboard-proxy Enable the Kubernetes dashboard and proxy to host
dbctl
disable         Disables running add-ons
enable          Enables useful add-ons
helm            The helm client
helm3           The helm3 client
inspect         Checks the cluster and gathers logs
istioctl        The istio client …
```
=> Adds a description for the dbctl command.

installer/windows/microk8s.nsi
Maybe we can find a way to do this automatically?
=> Bump default Windows install track to 1.20/stable

installer/vm_providers/_multipass/_multipass_command.py
During initial install on macOS, if 'multipass' is not installed:
```
➜  ~ microk8s install
Support for 'multipass' needs to be set up. Would you like to do that it now? [y/N]: y
Updating Homebrew...
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
```
=> Fix brew cask deprecation warning

microk8s-resources/actions/ingress.yaml
The resourceName has changed from `ingress-controller-leader-nginx` to `ingress-controller-leader-public`.  This only happens when `RBAC` is enabled.
=> Fixes #1829

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, snap/hooks/configure
In the  `configure` hook of snap, use the `readyz` endpoint to if apiserver is ready.
Fixes: #1831
=> Use apiserver readyz endpoint 

scripts/inspect.sh
Change the check in the inspect script to
look for rules for vxlan.calico instead of cni0
which seems to be the interface that
Calico creates for itself when in VXLAN mode.
Fixes #1712
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
=> fix(inspect): calico interface ufw name check

installer/requirements.txt, installer/setup.py
Fixing https://github.com/ubuntu/microk8s/issues/1882
With the release of Python 3.9.1 via brew, a (luckily no longer used) dependency was failing to build.  I have removed that and MicroK8s now builds on macOS Big Sur and Catalina (see https://github.com/ubuntu/homebrew-microk8s/runs/1684157733, note that the jobs fail but that's after MicroK8s is installed).
Note this is live already due to https://github.com/ubuntu/homebrew-microk8s/blob/master/Formula/microk8s.rb already pointing to the installer-2.0.3 tag.
=> Hotfix: remove redundant requirements to fix brew install

.github/workflows/build-installer.yml, installer/cli/microk8s.py, installer/common/auxiliary.py, installer/common/file_utils.py, installer/vm_providers/_base_provider.py, installer/vm_providers/_multipass/_multipass.py, installer/windows/microk8s.nsi
To address the complaint that file manipulation (e.g. `microk8s kubectl apply -f ./pod.yaml`) is difficult with the installers.
This difficultly is caused by files being referenced on the host, which are not then made available inside the VM running MicroK8s.  The most pragmatic fix for this is appears to be running kubectl on the host pointing at the MicroK8s kubeconfig file, which is written to the host every time `microk8s install` is run.  This does not overwrite or merge with `.kube/config` in order to give the "black box" feel of MicroK8s on Linux.  When `microk8s kubectl` is run, the command is no longer passed into the VM, rather run on the host with `--kubeconfig` to point to the aforementioned written file.
For Windows, we bundle `kubectl` with the NSIS installer and place it …
=> Bundle kubectl with Windows installer and set kubectl as brew requirement for MacOS

microk8s-resources/actions/ingress.yaml
[ingress-nginx 0.31.0 introduced support for IngressClass.][1] This broke MicroK8s when both the `rbac` addon and the `ingress` addon were enabled, because the ClusterRole for the `ingress` addon lacked the rules required for the `ingressclasses` resource.
[1]: https://github.com/kubernetes/ingress-nginx/commit/efbb3f9fc868f8e69d892017f672c7bfc00e7201
=> Fix ClusterRole for ingress addon

.github/workflows/test-kubeflow.yaml
The bundle-kubeflow repo now has requirements.txt and test-requirements.txt, which should be used instead of manually installing test dependencies.
=> Fix Kubeflow CI dependency installation

microk8s-resources/actions/enable.kubeflow.sh
You can still manually set it with the `--password` flag, but if that flag is not passed in, a randomly-generated password will be used without prompting the user. The generated password will still be displayed to the user at the end of the script.
=> Remove password prompt in Kubeflow addon

snap/snapcraft.yaml
Hotfix for the latest release of PIP.  The latest release breaks the snap as it uses `f{}` formatting, which isn't supported by Python 3.5, which is what comes with core16.
Mid term fix is to bundle our own Python build, replacing the old version that comes with core16.
Longest term fix is to move to core20.
=> Hotfix broken PIP

microk8s-resources/actions/common/utils.sh
The apiserver will not restart when the vxlan.calico comes up and the certificate issued will not include the respective IP.
=> Do not restart when vxlan.calico comes up

scripts/wrappers/common/utils.py
The click wrapper was ignoring the exit status from addons that it wrapped.
=> Fix subprocess calls in xable scripts

microk8s-resources/actions/dashboard.yaml
If windows node exists in the cluster, enable addon dashboard gives ImagePullBackOff error.
v1.0.4: Pulling from kubernetesui/metrics-scraper
no matching manifest for windows/amd64 10.0.19042 in the manifest list entries
=> Added linux os selection.

snap/snapcraft.yaml
We do not need these debug flags anymore.
=> Remove debug flags from dqlite and raft builds

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
Fix for Linkerd 2.9.0 addon.  Version 2.9.0 is not available for download.  2.9.2 contains some fixes which are critical.
=> fixes linkerd addon, by updating to v2.9.2

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
Fixes #1979. linkerd 2.9.0 is not available for download.
=> [1.20] Fix linkerd addon

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
Fixes #1978, linkerd 2.9.0 is not available for download.
=> [1.19] Fix linkerd addon

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/coredns.yaml, microk8s-resources/wrappers/run-kubelite-with-args
1. If we do not have `br_netfilter` loaded try to load it.
2. Fix iptables-nft rule lost in code merges
3. Remove duplicate volumes declaration in coredns manifest
=> Fixes in kubelite startup script

.gitignore, tests/requirements.txt, tests/test_distros.py, tests/testnode/addons.py, tests/testnode/api.py, tests/testnode/executors.py, tests/testnode/lxc/microk8s.profile, tests/testnode/nodes.py, tests/testnode/templates/bbox.j2, tests/testnode/templates/cuda-add.j2, tests/testnode/templates/ingress.j2, tests/testnode/templates/load-balancer.j2, tox.ini
This brings install and upgrade testing up to parity with the bash based
version. Reorganize the testnode code into a module instead of
one large file. Finally fixed linting as well.
=> Add pytest based nodetest

snap/hooks/start, snap/hooks/stop
LP builds are failing post-build review because of these.  They're not needed as we use microk8s start / stop anyway.
=> Remove invalid hooks

docs/build.md, microk8s-resources/actions/common/utils.sh, scripts/wrappers/common/utils.py
Fixes https://github.com/ubuntu/microk8s/issues/2011
This PR
* Suggests using `newgrp` or a reboot after adding your user to a group. logging out and back in doesn't always work. https://github.com/ubuntu/microk8s/issues/2011
* Suggests changing ownership of ~/.kube when joinging microk8s group in the python utils too. (This was already the case in the bash utils)
* Cleans up the build docs
* Makes it clear that the tests require building and installing the snap.
* Update tests to Ubuntu 20.04 and add sudo to install commands.
* General cleanup and markdown linting.
* Removed the "references" sections since all links were already part of the body.
=> fix instructions for joining microk8s group and cleanup build docs

build-scripts/patches/0001-kubelite-single-binary-k8s.patch, microk8s-resources/default-args/kubelite, microk8s-resources/wrappers/run-kubelite-with-args
You may not want to run the control plane in case you upgrade a non-HA cluster with kubelite.
Related issues: 
- https://github.com/ubuntu/microk8s/issues/2016
- https://github.com/ubuntu/microk8s/issues/2014
=> Option to not start the control plane in kubelite

.github/workflows/build-snap.yml, .github/workflows/test-kubeflow.yaml, snap/snapcraft.yaml
Raft now requires libuv v1.18.0 to build. As this is not available in core we need to build it.
=> Build libuv v1.18.0 in the snap

.gitignore, scripts/wrappers/common/utils.py, snap/snapcraft.yaml
This is the work of @angelnu from PR https://github.com/ubuntu/microk8s/pull/1961, Quoting from there:
```
This is a continuation of the work for https://github.com/ubuntu/microk8s/issues/719 .
After splitting the remote build support this patch adds just the capability to build locally
on armrf or remotely with snapcraft remote-build
The mayor change beyond fixing the check on x86 only plugins was to allow building etcd
from sources when no binary is available. This way the version matches on all platforms
but the official binary is used when available.
The built result is functional and I am able to add nodes successfully.
If there are additional tests needed before a platform is added please let me know.
```
=> Build microk8s for armhf and other architectures

snap/snapcraft.yaml
Pip packages broke the build of ARM64. Pin the pipy packages so we do not have this problem in the future.
Fixes: https://github.com/ubuntu/microk8s/issues/2049
=> Pin versions of pip packages

microk8s-resources/actions/enable.openfaas.sh
**What**
- Change `--auth` flag to `--no-auth` flag and set the AUTH varialbe to
true by default. This enables basic auth by default. At the end of the
installation, the helm message will print the instructions required to
retrieve the password value.
I treid to submit the CLA but I don't know who to put into the "Please add the Canonical Project Manager or contact" field.
=> Change openfaas flags to enable auth by default

build-scripts/patches/0003-Fix-CSI-initialization-conflict.patch
Introduce a patch to kubernetes to handle a CSI initialization race condition. Read more on the issue at https://github.com/k3s-io/k3s/issues/287
=> Fix CSI init race condition

microk8s-resources/actions/enable.prometheus.sh, microk8s-resources/wrappers/addon-lists.yaml
Closes #2059
Contains the following upgrades:
* Grafana v7.3.4
* Prometheus v2.22.1
=> Update Addon kube prometheus  to v0.7.0

scripts/inspect.sh
The inspect script checks that the apiservice is running. Now we should be checking for kubelite.
=> inspect script should check for kubelite

build-scripts/pre-patches/0001-Kubelite-integration.patch, snap/snapcraft.yaml
K8s 1.21.0-beta.1 enforced golang 1.16 and also caused some patch conflicts.
=> Go 1.16. And updated k8s patches.

microk8s-resources/actions/common/utils.sh
Do not restart the API server because the calico interface came up. 
Fixes: https://github.com/ubuntu/microk8s/issues/2083
=> Do not restart when vxlan.calico comes up (#1927)

microk8s-resources/wrappers/run-kubelite-with-args, snap/hooks/install, snap/hooks/remove
To stop hard coded host mounts from using the wrong directory.
=> Create sym link to SNAP_COMMON

microk8s-resources/wrappers/addon-lists.yaml, snap/snapcraft.yaml, tests/test-addons.py
The manifests produced by the openfaas addon are amd64 specific. They have:
```
nodeSelector:
beta.kubernetes.io/arch: amd64
```
=> Do not ship openfaas on arm64

microk8s-resources/actions/disable.ha-cluster.sh
When we have a single node and we call disable ha-cluster we require to have the --force flag.
Fixes #2009
=> Require force for disable HA on single node cluster

microk8s-resources/wrappers/microk8s-add-node.wrapper, scripts/cluster/add_token.py
When calling `microk8s.add-node` multiple times there is a chance you get the same token printed twice.
=> Ensure we display the token we wrote when joining

scripts/cluster/agent.py, scripts/cluster/join.py
Fixes included in this PR:
- Enable node fingerprint verification when provided in the join connection string
- Fail with proper error message when:
1. We join a node to itself
2. We join a cluster and dqlite already knows about that node
- Fixes in parsing the error messages
- Allow for forcefully remove a node from dqlite using its IP.
Fixes some of the cases reported in https://github.com/ubuntu/microk8s/issues/2144
=> Improved handling of joining cases

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-containerd-with-args
After a cold boot containerd will go over all leftover container entries and will try to revive them. This causes kubelet to not be able to start properly. In this PR we mark when containerd started so we know if this is the first time containerd started after a system boot. If it is a first start we manually remove all container entries since we know they do not run anymore.
Fixes: https://github.com/ubuntu/microk8s/issues/2071
=> Clean leftover containers after a cold boot

.github/workflows/build-snap.yml, microk8s-resources/actions/disable.ha-cluster.sh, snap/snapcraft.yaml, tests/lxc/install-deps/images_centos-7, tests/test-addons.py, tests/test-distro.sh
Fixes https://github.com/ubuntu/microk8s/issues/2181
- Build runc in its own part and patch-elf it
- Move a number of binaries into a patched-elf part
- Add a centos7 test option (eg `test-distro.sh images_centos-7 latest/edge latest/beta`)
=> Fixes for Centos7 support

scripts/wrappers/status.py
Fix #2147
Signed-off-by: Karl-Philipp Richter <krichter@posteo.de>
Results in:
```
$ sudo killall -9 kube-apiserver ; microk8s.status --yaml
microk8s:
running: False
message: microk8s is not running. Use microk8s inspect for a deeper inspection.
```
=> Fix yaml output of microk8s.status if not running - 1.20 (#2148)

microk8s-resources/wrappers/microk8s-reset.wrapper
Small fix. There was two duplicated echos in microk8s-reset.wrapper at clean_cluster() function.
* [ x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [ x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
=> Fixed duplicated echo in microk8s-reset.wrapper

microk8s-resources/default-args/kube-controller-manager, microk8s-resources/default-args/kube-scheduler
kube-controller-manager and kube-scheduler need to elect a leader. They do so by tring to update the "lease" which is an entry on the datastore (dqlite or etcd). The controller that manages to update the "lease" becomes the leader. The leader will periodically try to update the "lease" so it does not expire. By default the lease duration is 15 secs and it gets refreshed on the 10th second 
(--leader-elect-lease-duration duration     Default: 15s and --leader-elect-renew-deadline duration     Default: 10s). If a leader fails to update the lease it panics, see [1].
On stressed systems we may not get enough time to update the lease so kubelite crashes. The ideal fix is for the kube-scheduler and kube-controller-manager to step down gracefully. This will need some upstream work. For now we …
=> Increase the controller and scheuler lease to one minute

microk8s-resources/actions/common/utils.sh
In systems like the RPi /proc/1 may not report the boot time.
Fixes: https://github.com/ubuntu/microk8s/issues/2204
=> Get boot time from /proc/stat

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-reset.wrapper, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py, tests/test-cluster.py
When in a cluster you do not want to re-issue certificates due to a network change. We place a lock file indicating if the certs should be reissued or not. Some work has gone into the tests to make sure this lock exists.
=> Do not re-issue certificates on clusters

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh, snap/snapcraft.yaml
This commit includes the following changes:
* Lock Kubeflow tests to particular revision (#2089)
* Improve Kubeflow addon teardown
* Removes cluster-scoped resources during teardown
* Fix pip3 not found CI failure
* Update Kubeflow addon to 1.3
* Change from xip.io to nip.io
=> Back Port Kubeflow 1.3 to 1.20

microk8s-resources/actions/disable.kubeflow.sh
The disable.kubeflow action isn't working correctly as our python version in 1.20 does not support fstrings.
This fixes #2263
=> Fix disable kubeflow for 1.20

snap/snapcraft.yaml
All patches were removed in commit
478e80939311416292e7c10d12bd0a5a9fed6a8a, and snapcraft now complains
that the path is not found.
=> snap: remove patches section from snapcraft file

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-containerd-with-args
The previous code required higher privileges (access to /proc/1/ is
generally not granted to confined applications) and was overcomplicated:
if we only need to know if this is the first execution after boot, then
we can create a sentinel file under /tmp and rely on the fact that /tmp
is cleared after every boot.
=> microk8s-resources: simplify the first-boot detection

snap/snapcraft.yaml
The kubectl program opens a socket to communicate with localhost.
For the time being, let's use the docker-support interface to provide
this access. It may be that this interface is overkill and that kubectl
requires much less permissions, but that will be tracked separately.
=> snap: grant kubectl access to networking

microk8s-resources/actions/disable.kata.sh, microk8s-resources/actions/enable.kata.sh, microk8s-resources/actions/kata/runtime.yaml, microk8s-resources/default-args/containerd-env, microk8s-resources/default-args/containerd-template.toml, microk8s-resources/wrappers/addon-lists.yaml, snap/hooks/configure, snap/snapcraft.yaml, tests/templates/nginx-kata.yaml, tests/test-addons.py, tests/test-upgrade.py, tests/utils.py, tests/validators.py
[Kata Containers](https://katacontainers.io/), is used to build a secure container runtime with lightweight virtual machines that feel and perform like containers, but provide stronger workload isolation using hardware virtualization technology as a second layer of defense. You can enable kata support with: 
``` microk8s enable kata``` 
The addon adds the `kata` `runtimeClassName` that allows you to specify what workloads should be started in Kata containers. For instance, the following manifest starts nginx in a Kata container:
```
apiVersion: v1
kind: Pod
metadata:
labels:
app: kata
name: nginx-kata
spec:
runtimeClassName: kata
containers:
- name: nginx
image: nginx
```
By default the addon will install the Kata runtime via the [kata-containers …
=> Kata containers addon

snap/snapcraft.yaml
The microk8s script is internally executing kubectl, and that happens
without switching to the kubectl confinement (see [1] and [2]).
Therefore, we need to add the plugs needed by kubectl to the microk8s
script.
[1] https://forum.snapcraft.io/t/executing-a-child-process-provided-by-the-same-snap/24744
[2] https://forum.snapcraft.io/t/the-right-way-to-to-start-another-app-inside-same-snap/2069
=> snap: add some kubectl permissions to microk8s script

snap/snapcraft.yaml
This gets rid of these two AppArmor errors:
AVC apparmor="DENIED" operation="capable" profile="snap.microk8s.daemon-apiserver-kicker" pid=46846 comm="ip" capability=16  capname="sys_module"
AVC apparmor="DENIED" operation="capable" profile="snap.microk8s.daemon-apiserver-kicker" pid=36170 comm="ifconfig" capability=16  capname="sys_module"
=> snap: add kernel-module-control plug to the apiserver

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.dns.sh
Setting this flag to "true" causes runc not to set the NO_NEW_PRIVS
flag on the coredns. The reason why we don't want the NO_NEW_PRIVS flag
set on our process is that this flag does not play well with AppArmor,
and having it set prevents a process from switching to a different
AppArmor profile.
=> coredns: allow privilege escalation

microk8s-resources/actions/enable.prometheus.sh
* Add `Loki` default datasource to Grafana.  This can help add Loki seemlessly without having to manually change Grafana dashboard.
* Upgrade to kube-prometheus 0.8.0.
* Cleaned up some scripts which modifies the images that supports `arm64` architecture.
The snap was tested on both `arm64` and `amd64` Architecture.
=> Upgrade kube prometheus 0.8.0

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/configure, snap/hooks/remove, snap/snapcraft.yaml
Set the containerd daemon type to notification. This does not stop the containers when containerd restarts. During a refresh we have to make sure the CNI pods get restarted because they mount locations of $SNAP_DATA.
Fixes: https://github.com/ubuntu/microk8s/issues/2290
=> Reload cni when refreshing

docs/build.md, upgrade-scripts/000-switch-to-calico/resources/calico.s390x.yaml
Addresses https://github.com/ubuntu/microk8s/issues/1611#issuecomment-854421793
=> Make namenode optional on the s390x calico manifest

.github/workflows/check-formatting.yml
Make sure apt-get update is called before apt-get install to refresh the apt list.
`check formatting` github-action job fails with this.
` Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python-virtualenv/python3-virtualenv_20.0.17-1ubuntu0.3_all.deb  404  Not Found [IP: 52.252.75.106 80]`
Calling `apt-get update` may fix this.
=> Fix linting github-action job

.github/workflows/check-formatting.yml, snap/snapcraft.yaml
This PR fixes the go-dqlite build by adding the
`export CGO_LDFLAGS_ALLOW="-Wl,-z,now"`  Refer to https://github.com/canonical/dqlite/issues/308
=> fix go dqlite build.

.github/workflows/check-formatting.yml, snap/snapcraft.yaml, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
This PR upgrade calico to v3.19.1.  No change is done when upgrading a cluster which is already using the previous calico.
This supersedes https://github.com/ubuntu/microk8s/pull/2081, and thanks to @danports for initiating the work.
@ktsakalozos thanks for taking a look at this.
=> upgrade calico to v3.19.1

microk8s-resources/actions/traefik.yaml
The Traefik plugin uses `hostNetwork=true` for its pods. It does not, however, specify a `dnsPolicy` which will cause the policy to default to `ClusterFirst`. This does not work when `hostNetwork` is set to `true`. As recommended by [the Kubernetes documentation on DNS](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/), `ClusterFirstWithHostNet` should be explicitly used as the DNS policy.
> For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
This issue is important in order to use Traefik with forward authentication services, or other features that require a lookup of a service in the cluster.
*I have:*
=> Use ClusterFirstWithHostNet as DNS policy for Traefik

microk8s-resources/actions/disable.linkerd.sh, microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
This PR follows the new plugin feature of Linkerd.  Visualizations are now part of the plugin and is separated from the control plane.
This PR will install the visualization like it used to.
=> upgrade linkerd to v2.10.2

.github/workflows/cla-check.yml
This is running on the push to master and failing due to:
```
Run canonical/has-signed-canonical-cla@1.1.4
Installing python3-launchpadlib
Error: Cannot read property 'commits_url' of undefined
```
I don't think it's meant to be run on push, only PR.
=> This probably shouldn't be running on the actual master branch

microk8s-resources/default-args/containerd-template.toml, microk8s-resources/wrappers/run-containerd-with-args, scripts/inspect.sh
Detect if the `os` is running `cgroupV2` and if so enable `containerd` `cgroupV2`. 
Also enhance inspect to correctly report this `cgroup` version.
Fixes #2054.
duplicate PR of #2052 Closed that as it was committed under incorrect emailaddress.
=> enable containerd cgroupV2 if detect os cgroupV2 enabled

snap/snapcraft.yaml
We want to build the dqlite-client using the libs from the sqlite we build.
=> Use libsqlite-dev from the sqlite build

snap/snapcraft.yaml
With this declaration, snapd will automatically create a user and a
group called "snap_microk8s". We use the passthrough feature to force
snapcraft to accept this value even though it doesn't understand it.
Note: https://github.com/ubuntu/microk8s/pull/2416 would be the best solution, but it's currently blocked by https://github.com/snapcore/snapcraft/pull/3545. While we wait for that change to land, here's a more immediate solution.
=> snap: declare the microk8s user and group

build-scripts/patches/runc/0001-apparmor-change-profile-immediately-not-on-exec.patch, build-scripts/patches/runc/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/patches/runc/0003-standard_init_linux-change-AppArmor-profile-as-late-.patch
The base commit for the runc component was bumped while these patches
were waiting to be merged, and now they don't apply anymore. Here's an
updated version.
=> build-scripts: update NNP patches

microk8s-resources/actions/disable.ingress.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/wrappers/addon-lists.yaml
Due to removal of v1beta1 APIs on K8s [2] we have to go with an alpha Ingress controller release [1].
[1] https://github.com/kubernetes/ingress-nginx/releases 
[2] https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/
=> Update ingress for v1.22

microk8s-resources/actions/enable.openfaas.sh
When running `microk8s enable openfaas --values=values.yaml` (or `microk8s enable openfaas -f=values.yaml`) the error "Error: unknown flag: --f" is raised:
```
Addon dns is already enabled.
Addon helm3 is already enabled.
Enabling OpenFaaS
Operator: false
Basic Auth enabled: true
Overrides file: values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2262/credentials/client.config
"openfaas" already exists with the same configuration, skipping
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2262/credentials/client.config
Error: unknown flag: --f
```
The (helm documentation)[https://helm.sh/docs/chart_template_guide/values_files/] details that the option passed should be …
=> Fix "Error: unknown flag" in enable.openfaas.sh (#2457)

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh
Kubeflow is not available on K8s v1.22 yet so we need to fail gracefully and direct users to a github issue where they can see the progress we are making.
Due to https://github.com/ubuntu/microk8s/issues/2496
=> Disable Kubeflow addon for the v1.22 release

tests/test-addons.py
Cilium is complaining when enabled on lxc:
```
kube-system   pod/cilium-bzzqp                               0/1     Init:CreateContainerError
```
and 
```
(combined from similar events): Error: failed to generate container "95c9998218f6b6bc29c56b4d08a4b64de4b705f786d86e7bf8ebd599ca155328" spec: failed to generate spec: path "/run/cilium/cgroupv2" is mounted on "/run/cilium/cgroupv2" but it is not a shared or slave mount
```
This PR runs the cilium test on GH actions and not on lxc containers.
=> Do not run cilium test on lxc

microk8s-resources/actions/disable.openebs.sh, microk8s-resources/actions/enable.openebs.sh, microk8s-resources/wrappers/addon-lists.yaml, tests/test-addons.py, tests/validators.py
Signed-off-by: Niladri Halder niladri.halder@mayadata.io
Enable changes:
* Disables installation of legacy components which use deprecated API versions
* Installs Jiva(CSI), cStor(CSI) and dynamic-localpv-provisioner storage engines.
* Sample PVC for jiva now uses the default Jiva storageClass, i.e. openebs-jiva-csi-default
* Removed the messages stating that the OpenEBS plugin is not available.
Disable changes:
* Removed deletion of SPC-based components as these are not API-compatible
* Included deletion for legacy components which are API-compatible
* Included deletion for cStor(CSI). Jiva(CSI) deletion is handled by namespace delete.
=> OpenEBS changes for k8s v1.22

scripts/inspect.sh
Detect Debian 9 and suggest a fix for old snapctl.
Mitigates #2513
=> Suggest fix for debian 9

snap/hooks/configure
We do want to have a $SNAP_DATA/certs/ directory in any case because of
`csr.conf.template`. Since the order of the operations is not important,
change it slightly to ensure that the directory is created before
patching the other certificates.
Fixes: https://bugs.launchpad.net/snapd/+bug/1940985
=> snap/hooks/configure: ensure that $SNAP_DATA/certs/ exists

snap/snapcraft.yaml
There are other lock files that are used, such as
/etc/service/enabled/monitor-addresses/supervise/lock
/etc/service/enabled/allocate-tunnel-addrs/supervise/lock
It's probably a good idea to bind-mount the whole parent directory.
=> snap: bind-mount the whole /etc/service/enabled/ directory

docs/community.md
We created a learning resource for Kubernetes called the Kubernetes Automation Toolkit, which uses Microk8s to setup a cluster. Good uptake on GH (37 stars already) plus
It has also been used here: https://www.canarie.ca/cloud/boosterpacks/catalogue/flight-plan-automate-cloud-orchestration-with-kubernetes/sample-solution-kubernetes-automation-toolkit-kat/
* [ x ] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [ x ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
=> Add our K8s learning resource based on Microk8s

tests/patch-kube-proxy.sh, tests/test-cluster.py, tests/test-distro.sh, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/test_distros.py
Placeholder until I can figure out how to run this correctly.  I'm running:
```
./tests/test-distro.sh ubuntu:18.04 latest/edge/strict microk8s.snap
```
But it fails with:
```
Tests are running in b'lxc\n'
+ echo --conntrack-max-per-core=0
+ snapctl restart microk8s.daemon-proxy
error: error running snapctl: cannot restart without a context
F
======================================================================================== FAILURES =========================================================================================
________________________________________________________________________________ TestUpgrade.test_upgrade _________________________________________________________________________________
self = <test-upgrade.TestUpgrade object at 0x7f9470cbd320>
def …
```
=> Upgrade tests for strict branch

microk8s-resources/wrappers/addon-lists.yaml
Trivial change fixing casing of OpenFaaS in addon description.
=> Use correct casing for OpenFaaS addon description

snap/snapcraft.yaml
Update the k8s build process to use go 1.17. This is needed for v1.23.
=> Build k8s binaries with go v1.17

.github/workflows/build-snap.yml, .github/workflows/test-kubeflow.yaml, scripts/cluster/join.py
When joining a node dqlite may print to stderr:
```
$ microk8s join 192.168.1.156:25000/b12f8fe475e8dcf4a1e3178a1de2dcd8/17f9b3dd3c5b
Contacting cluster at 192.168.1.156
Waiting for this node to finish joining the cluster. Error: open servers store: stat /var/snap/microk8s/2493/var/kubernetes/backend/cluster.yaml: no such file or directory
Usage:
dqlite -s <servers> <database> [command] [flags]
Flags:
-c, --cert string       public TLS cert
-f, --format string     output format (tabular, json) (default "tabular")
-h, --help              help for dqlite
-k, --key string        private TLS key
-s, --servers strings   comma-separated list of db servers, or file://<store>
..  
```
We do not want this output to show up as for any error we retry querying dqlite.
=> Do not print dqlite error messages while dqlite forms a cluster

microk8s-resources/actions/enable.openebs.sh
This modifies the helm install flags for the openebs/openebs helm chart so that it may work with v3.0.0.
This pins the chart version to v3.0.x.
=> Change helm install flags to work with OpenEBS v3.0

microk8s-resources/actions/enable.openebs.sh
This modifies the helm install command for the OpenEBS addon, and pins v2.x.x to microk8s v1.22.
Additionally, this chart used legacy components exclusives.
=> Helm install command pinning openebs v2.x.x to microk8s v1.21

scripts/cluster/join.py
Signed-off-by: Karthikeyan Govindaraj <github.gkarthiks@gmail.com>
This PR is to print the `--force` option in the usage/help command for the `microk8s help` command.
=> add: force option in usage

tests/requirements.txt
I keep having to install this manually when running tests.
=> Add sh requirement

microk8s-resources/actions/common/utils.sh
A fix for https://github.com/ubuntu/microk8s/issues/1822 - and probably many other "my API server restarts / crashes / isn't stable" issues which have not diagnosed this far down.
A recap:
- api kicker service considers a list of IP addresses on the system, looks for changes, restarts API server on changes
- some OSes / users install tools like `dhcpcd`, which by default attempts to DHCP _every interface_.
- when DHCP fails for `vxlan.calico`, a `169.254...` address is assigned to the interface
- That address is removed moments later when dhcp decides to re-try
- this causes `get_ips()` to trigger a re-generation of the api-server CSR
- this causes api-kicker to restart the API, more or less in a loop, causing availability and stability issues
Fix is ignoring `169.254` addresses entirely. …
=> ignore unroutable DHCP failure addresses when considering IP addresses for get_ips()

microk8s-resources/actions/disable.inaccel.sh, microk8s-resources/actions/enable.inaccel.sh, tests/templates/inaccel.yaml, tests/validators.py
* Set `kube-system` as the default namespace
* As of `fpga-operator-2.5.3` release, the templates respect the Helm release namespace
* Users will be able to modify this using the cli: `microk8s enable/disable inaccel -n <my-namepace>`
* Test mutating webhook features
* InAccel FPGA Operator v2.5.0 introduced a Mutating Webhook Configuraton
* Simplifies FPGA-enabled Pods (less YAML lines)
* Enables easier integration with CRDs
=> Update inaccel add-on

scripts/inspect.sh, snap/snapcraft.yaml
Include a dqlite directory in the inspection report.
Fix the `microk8s.inspect` command, notice the `.`.
=> Inspect report to include basic dqlite info

microk8s-resources/actions/disable.kubeflow.sh, microk8s-resources/actions/enable.kubeflow.sh, microk8s-resources/wrappers/addon-lists.yaml
Creates lock file after all actions in enable.kubeflow.sh
and points check_status in addon-lists.yaml to that file.
This ensures Kubeflow addon is listed as enabled when
running microk8s status
Fixes #2695
=>  Points Kubeflow's check_status value to kubeflow.enabled lock file 

microk8s-resources/actions/enable.gpu.sh, tests/validators.py
Updated GPU operator as the v1.8.2 allows for "support for user-defined MIG partition configuration via a ConfigMap" [1].
[1] https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html
=> Update GPU operator and fix its test

microk8s-resources/default-args/kube-apiserver, microk8s-resources/default-args/kube-controller-manager, microk8s-resources/default-args/kube-proxy, microk8s-resources/default-args/kube-scheduler
Update default API server arguments
- Disable profiling (--profiling=false)
- Reduce event TTL to 5 minutes (--event-ttl=5m)
=> Disable profiling and reduce event TTL for Kubernetes services

docs/build.md
This PR adds a note to the build documentation about the use of nip.io in tests. Networks implementing [DNS rebinding protection](https://en.wikipedia.org/wiki/DNS_rebinding) may block the resolution of loopback addresses as documented on the nip.io page. 
On my own network, this condition lead to failed tests.
The note includes a `/etc/hosts` workaround.
=> Add note and workaround for nip.io in tests

scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py, scripts/wrappers/common/utils.py
This minor PR is to make use of `yaml.safe_load` when loading YAML files in Python. This is to prevent issues (security or otherwise) that may arise from using the `yaml.FullLoader`
=> Use SafeLoader instead of FullLoader

docs/build.md, microk8s-resources/wrappers/microk8s-kubectl.wrapper, snap/snapcraft.yaml
Bundling `nano` (this seems to be defacto in Ubuntu) in order to be able to edit manifests on-the-fly with `kubectl`.
=> Bundle nano with strict in order to be able to use `kubectl edit`

microk8s-resources/actions/metrics-server.yaml
Upgrading metrics server to `v0.5.2`
=> upgrade metrics server to v0.5.2

microk8s-resources/wrappers/run-k8s-dqlite-with-args
When the `k8s-dqlite` arguments file is missing, then simply `exit 0` from the `snap.microk8s.daemon.k8s-dqlite` service.
This is to avoid a race condition where during a refresh, the k8s-dqlite daemon restarts too many times before the configure hook is able to properly cp the required configuration files.
- This is similar to what we do for traefik on the worker nodes.
=> Improve handling for missing k8s-dqlite arguments file

scripts/cluster/add_token.py
On etcd based clusters (`microk8s.disbale ha-cluster`) all added nodes are workers. This PR keeps the current behavior and hides the --worker flag in those clusters.
=> Fix add-node output in etcd based clusters

microk8s-resources/default-args/certs.d/docker.io/hosts.toml, microk8s-resources/default-args/certs.d/localhost:32000/hosts.toml, microk8s-resources/default-args/containerd-template.toml
As described in #2647, containerd has changed the way registries are configured. This patch adapts microk8s to this change. See more at [containerd](https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration).
PS: I haven't signed the CLA as it requires me to provide the name of a "Canonical Project Manager or contact". Please advise.
=> Remove deprecated configuration from containerd-template.toml

scripts/cluster/reset.py
Parsing the callback tokens file was not correct and we were not removing callback tokens of nodes that had departed the cluster. This was casing the distributed ops to iterate over nodes that had already been removed from the cluster as described in  https://github.com/ubuntu/microk8s/issues/2750
=> Fix removal of callback tokens

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.host-access.sh, microk8s-resources/actions/enable.host-access.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/inspect.sh
It consist basically of the replacement of the long deprecated ifconfig/netstat to ip addr/route/ss tools from iproute2.
The first commit fixes the issue #2657 .
While at it, it also takes care, in a second commit, of other calls of ifconfig and netstat in other scripts such as :  
* enable/disable host-access
* common/utils functions
* inside the wrapper "run-kubelite-with-args" which simply enable the host-access feature
With this, theoretically, it should be possible to remove net-tools from the snap build.
=> Replace depreated call from net-tools to iproute2

scripts/inspect.sh
Closes https://github.com/ubuntu/microk8s/issues/1721
- Check that `dockerd` binary is installed, otherwise do not print the warning message.
=> Print warning for docker if docker daemon is installed

microk8s-resources/wrappers/run-containerd-with-args, snap/hooks/configure, snap/hooks/remove
Backporting fix to 1.22 of https://github.com/ubuntu/microk8s/issues/2645
=> Update the PATH containerd-shims has to find runc for v1.22

microk8s-resources/wrappers/run-containerd-with-args
Addresses https://github.com/ubuntu/microk8s/issues/2645
To test this PR you can:
```
sudo snap install microk8s --revision 2746 --classic
microk8s.enable ingress
microk8s.kubectl get all -A
sudo snap refresh microk8s --revision 2742
sudo snap refresh microk8s --revision 2740
#
ls -lh /snap/microk8s/
microk8s.kubectl get all -A
#delete the ingress pod
microk8s.kubectl get all -A
```
Make sure you do not have a runc already somewhere in your path so the one used is the one from the snap.
=> Update the PATH containerd-shims has to find runc

microk8s-resources/wrappers/run-kubelite-with-args, tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
When kube-proxy starts it tries to set the contents of `/proc/sys/net/netfilter/nf_conntrack_max` to `131072` if it is set to another number. On lxc containers this file is read only causing kube-proxy to fail. With this PR we update the LXC profiles to allow changing this file. This will address the issue on the pre-1.23 tracks
We also try to detect that we run on lxc and we set the conntrack-max-per-core argument so kube-proxy will not bother with contrack. This behavior will apply for the 1.23+ releases.
Fixes: https://github.com/ubuntu/microk8s/issues/1438
=> Allow kube-proxy to change nf_conntrack_max on lxc

README.md
Minor update for preparing for 1.23. This time the pre-release and release patches were the same so we did not need to update those.
=> Prepare for v1.23

snap/snapcraft.yaml
Runc dropped support for Go 1.15 (https://github.com/opencontainers/runc/commit/12e99a0f8df0e6ac59e82ec6941c70dbe12d7142), which has stopped MicroK8s from being buildable anywhere.
Go 1.16 does not pull in the same way as 1.15, so a simple bump is not enough.  Due to the way we have to `go get` and then checkout a commit of `runc` (et. al.), the initial get of 1.15 fails and you cannot then checkout the correct revision.  On top of this, `go get ` places the package in `./mod` instead of `./src` and 1.18 will drop support for `go get` all together (https://maelvls.dev/go111module-everywhere/, https://stackoverflow.com/questions/66284870/go-get-not-downloading-to-src-folder). 
In order to hot fix this issue, I have bumped to Go 1.16 and set `GO111MODULE=off` in order to get the old …
=> Runc now requires Go 1.16 minimum in order to go get

microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml
This PR addresses a breaking change in the way ingress access the configmap for its leader election.
It was previously called `<election-id>-<ingress-class>` where `election-id` is named `ingress-controller-leader` and `ingress-class` is `public`.
Now the resourceName is just the `election-id`
=> fix ingress leader election when rbac is enabled

microk8s-resources/actions/traefik.yaml, microk8s-resources/wrappers/addon-lists.yaml
Backporting https://github.com/ubuntu/microk8s/pull/2809 to 1.22
=> Bump traefik version to 2.5 (#2809)

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-status.wrapper, microk8s-resources/wrappers/run-k8s-dqlite-with-args, microk8s-resources/wrappers/run-kubelite-with-args, scripts/cluster/common/utils.py, scripts/cluster/join.py, scripts/inspect.sh, snap/hooks/install
Prevent MicroK8s from starting control plane components when installed on a machine with low RAM (< 512MB).
Some things below need to be ironed out, but this PR is mostly ready for testing. The changes appear simple, but it is important that we get the UX right.
The low-memory-guard is implemented using a lock file.
- During the `install` hook, we check the available RAM and create the lock file if needed.
- `microk8s start/stop/status` will refuse to run when the lock file exists, printing a relevant error message.
- `microk8s inspect` checks for the existence of the lock file, as well as the amount of available RAM.
When the guard is enabled, the node can be joined as a worker node in a cluster. The low memroy guard can be disabled with:
```bash
microk8s start --disable-low-memory-guard …
```
=> Add low-memory guard

microk8s-resources/actions/disable.hostpath-storage.sh, microk8s-resources/actions/disable.registry.sh, microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/enable.hostpath-storage.sh, microk8s-resources/actions/enable.portainer.sh, microk8s-resources/actions/enable.registry.sh, microk8s-resources/actions/enable.storage.sh, microk8s-resources/wrappers/addon-lists.yaml, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, tests/test-addons.py
Here we're starting the process of deprecating the `storage` addon and replace it with the `hostpath-storage` addon.
We're also acknowledging the limitations of hostpath storage.
=> Deprecate storage addon

microk8s-resources/actions/ingress.yaml
Back porting the #2813 to 1.21 .
This is needed due to the 1.0.5 update.
=> Update the ingress RBAC for allowing leader election

snap/snapcraft.yaml
These are two new services that did not have the disable flag.
=> Do not start traefik and k8s-dqlite until interfaces are connected

microk8s-resources/actions/storage.yaml, snap/snapcraft.yaml
Update hostpath-provisioner version to 1.1.0.
- Update hostpath-provisioner image to `cdkbot/hostpath-provisioner:1.1.0`
- New multi-arch image supports s390x, so enable storage addon for s390x architectures as well.
- After this PR is merged, we can begin with removing the `RemoveSelfLink=false` feature flag, which is removed on Kubernetes 1.24
=> Upgrade hostpath-provisioner

microk8s-resources/actions/enable.hostpath-storage.sh
Removing misleading error message when enabling storage addon.
- The `enable.storage.sh` is idempotent, so this check is not useful.
- The error message `"The hostpath-storage addon is already enabled"` is wrong and highly misleading. For example, if a user disables the hostpath-storage addon and chooses to preserve existing data, they get the following very confusing UX:
```
root@k8s:/snap/microk8s/current/microk8s-resources/actions# m enable hostpath-storage
Hostpath storage is already enabled.
root@k8s:/snap/microk8s/current/microk8s-resources/actions# m disable hostpath-storage
Addon hostpath-storage is already disabled.
```
This affects all MicroK8s versions, so needs to be backported to 1.21, 1.22 and 1.23 branches after merging
=> Enable storage addon even if hostpath directory exists

microk8s-resources/default-args/kube-apiserver, scripts/inspect.sh, snap/hooks/configure
The `RemoveSelfLink=false` feature flag is being removed in Kubernetes 1.24. We had kept that since it was required for our hostpath-provisioner to work.
This is no longer needed, so we can remove it, in time for 1.24.
The PR also adds a check for `microk8s inspect`, with steps for upgrading users that may encounter issues.
=> Drop RemoveSelfLink=false feature flag

upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh
Disable the etcd-server argument pointing to dqlite when disabling ha.
Fixes https://github.com/ubuntu/microk8s/issues/2863
=> Remove the dqlite related argument from the API server when disabling HA

scripts/inspect.sh
The error the inspection script prints when there are is not hostpath provisioner installed:
```
Error from server (NotFound): deployments.apps "hostpath-provisioner" not found
```
=> Silence the hostpath-provisioner error if the provisioner is not installed

microk8s-resources/wrappers/addon-lists.yaml
Add `s390x` to the list of supported architectures for the hostpath-storage addon.
=> Enable hostpath-storage for s390x architectures

microk8s-resources/actions/storage.yaml
Hostpath provisioner needs RBAC rules for `endpoint/microk8s.io-hostpath`.
From logs:
```bash
....
E0126 18:07:48.251277       1 leaderelection.go:330] error retrieving resource lock kube-system/microk8s.io-hostpath: endpoints "microk8s.io-hostpath" is forbidden: User "system:serviceaccount:kube-system:microk8s-hostpath" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
....
E0126 18:09:48.350001       1 leaderelection.go:334] error initially creating leader election record: endpoints is forbidden: User "system:serviceaccount:kube-system:microk8s-hostpath" cannot create resource "endpoints" in API group "" in the namespace "kube-system"
```
=> Fix RBAC rules for hostpath-storage

microk8s-resources/actions/storage.yaml
Followup for #2881, turns out that limiting `resourceNames` gives the following error:
```
E0126 21:02:56.968579       1 leaderelection.go:330] error retrieving resource lock kube-system/microk8s.io-hostpath: endpoints "microk8s.io-hostpath" is forbidden: User "system:serviceaccount:kube-system:microk8s-hostpath" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
```
=> Fix error retrieving resource lock

build-scripts/set-env-variables.sh
Upgrade containerd to 1.5.9.
See notes https://github.com/containerd/containerd/releases/tag/v1.5.8 and https://github.com/containerd/containerd/releases/tag/v1.5.9 for complete details.
In particular, we are interested in the following changes:
- [release/1.5] Output a warning for label image labels instead of erroring ([#6187](https://github.com/containerd/containerd/pull/6187))
- [release/1.5] update runc binary to v1.0.3 ([#6343](https://github.com/containerd/containerd/pull/6343))
=> Upgrade containerd to 1.5.9 and runc to 1.0.3

microk8s-resources/wrappers/run-kubelite-with-args, tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
=> Backport 1.22: Allow kube-proxy to change nf_conntrack_max on lxc

microk8s-resources/wrappers/run-kubelite-with-args, tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
=> Backport 1.21: Allow kube-proxy to change nf_conntrack_max on lxc

microk8s-resources/default-args/kube-controller-manager, microk8s-resources/default-args/kube-scheduler, snap/hooks/configure
`kube-scheduler` and `kube-controller-manager` have deprecated the `--address` flag and it is being removed in 1.24
Related logs:
```
Feb 07 11:37:32 ip-172-31-33-169 microk8s.daemon-kubelite[2706]: I0207 11:37:32.038243    2706 daemon.go:22] Starting Controller Manager
Feb 07 11:37:32 ip-172-31-33-169 microk8s.daemon-kubelite[2706]: Flag --address has been deprecated, This flag has no effect now and will be removed in v1.24.
Feb 07 11:37:32 ip-172-31-33-169 microk8s.daemon-kubelite[2706]: I0207 11:37:32.060648    2706 daemon.go:33] Starting Scheduler
Feb 07 11:37:32 ip-172-31-33-169 microk8s.daemon-kubelite[2706]: Flag --address has been deprecated, This flag has no effect now and will be removed in v1.24. You can use --bind-address instead.
```
=> deprecated --address flag removed in version 1.24

microk8s-resources/wrappers/microk8s-addons.wrapper, scripts/wrappers/addons.py, scripts/wrappers/common/utils.py, scripts/wrappers/disable.py, scripts/wrappers/enable.py, scripts/wrappers/status.py, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, tests/unit/test_addons.py, tox.ini
Extend the microk8s `status`, `enable` and `disable` commands to support addons from multiple repositories.
Also, introduce the following commands:
```bash
microk8s addons repo list
microk8s addons repo add
microk8s addons repo remove
microk8s addons repo update
```
Simple commands to test with a custom addons repository:
```bash
sudo snap install microk8s --classic --channel latest/edge/addon-repos
microk8s addons repo list
microk8s addons repo add neo https://github.com/neoaggelos/microk8s-addons-extras
microk8s addons repo list
microk8s enable neo/nginx
microk8s status
```
=> Support multiple addon repositories

scripts/cluster/add_token.py
Add support for `--format json` in the `microk8s add-node` command. Example output:
```bash
$ microk8s add-node --format json
{
"token": "d1b89bff339243598ea96e72a23cf015/9f45c8048db9",
"urls": [
"10.0.0.197:25000/d1b89bff339243598ea96e72a23cf015/9f45c8048db9",
"10.0.0.210:25000/d1b89bff339243598ea96e72a23cf015/9f45c8048db9"
]
}
```
=> Support JSON and YAML format for microk8s add-node command

microk8s-resources/actions/common/utils.sh
Closes #2814 
Add multiple dummy default routes and verify that `get_default_ip` does not fail.
Example error message where `get_default_ip` failed:
```
Device "eth0
eth0" does not exist.
none
```
=> Properly resolve host IP with multiple default routes

microk8s-resources/wrappers/git.wrapper, microk8s-resources/wrappers/microk8s-addons.wrapper, scripts/wrappers/addons.py, snap/hooks/configure, snap/hooks/install
git uses a few helper paths and configuration files from the system. Make sure that we do not get failures when running in strict
Also, remove the git clone from the install hook (it is already there in the configure hook).
=> Fixes for git to work with strict confinement

snap/snapcraft.yaml
Back porting https://github.com/canonical/microk8s/pull/2966 to 1.23
=> add SQLITE_ENABLE_DBSTAT_VTAB=1 to enable this virtual table (#2966)

.github/workflows/build-snap.yml, build-scripts/set-env-variables.sh, scripts/wrappers/common/utils.py, scripts/wrappers/reset.py, snap/snapcraft.yaml, tests/test-distro.sh
With this PR we stop loading the community repository by default. This was we do not clutter the UX with often irrelevant addons. If however we detect that an addon is in the community repository we prompt the user to enable the repository with a `microk8s enable community` call.
=> Do not load the community repo

snap/snapcraft.yaml
Without the `home-read-all` interface the git.wrapper is not able to clone local directories. Fixes errors like: 
```
+ sudo microk8s addons repo add core .
fatal: repository '.' does not exist
Traceback (most recent call last):
File "/snap/microk8s/3069/scripts/wrappers/addons.py", line 1[41](https://github.com/canonical/microk8s-core-addons/runs/5736312714?check_suite_focus=true#step:4:41), in <module>
addons(prog_name="microk8s addons")
File "/snap/microk8s/3069/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/snap/microk8s/3069/usr/lib/python3/dist-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/snap/microk8s/3069/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
return …
```
=> Add home-read-all to microk8s so the git.wrapper does not complain

build-scripts/set-env-variables.sh
Upgrade containerd to 1.5.11, addressing CVEs
- https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7
- https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c
This will also need to be backported to 1.23, 1.22, 1.21 branches.
=> Update containerd to v1.5.11

tox.ini
Backport relevant parts of #3014 to 1.23 branch.
=> Pin click to 8.0.4 to fix Black

build-scripts/set-env-variables.sh
The addons repository has been renamed from `microk8s-addons` to `microk8s-community-addons`. This PR updates the reference to it.
=> Point to new community addons repo

snap/snapcraft.yaml
Fixes for building containerd.
- Update Go to version 1.17 (same as in go.mod of containerd)
- Fetch containerd repository with git clone instead of go get.
This needs to be backported to all stable tracks, and is affecting #3030 
Fixes the following error
```
+ go get -d github.com/containerd/containerd
[06/Apr/2022:21:06:34 +0000] "CONNECT github.com:443 HTTP/1.1" 200 83078509 "-" "git/2.17.1"
package embed: unrecognized import path "embed": import path does not begin with hostname
```
=> Fix containerd build

build-scripts/set-env-variables.sh
Update containerd to 1.4.13. Address CVE:
- https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c
containerd 1.4 is EOL since March 3rd, 2022. MicroK8s 1.21 will also be EOL after the 1.24 release.
=> Upgrade containerd to 1.4.13

microk8s-resources/wrappers/microk8s-config.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper
Fix `microk8s start`, `microk8s stop` and `microk8s config` commands printing the internal wrapper script in usage messages.
=> Do not print path to wrapper script for start/stop/config commands

microk8s-resources/wrappers/apiservice-kicker
Fix the name of the cluster agent service. Followup fix for typo in #3054
Fixes
```
Apr 13 17:23:24 test-3 microk8s.daemon-apiserver-kicker[3342]: CSR change detected. Restarting the cluster-agent
Apr 13 17:23:24 test-3 microk8s.daemon-apiserver-kicker[8134]: error: error running snapctl: unknown service: "microk8s.cluster-agent"
```
=> fix name of cluster agent service

snap/snapcraft.yaml
Back porting https://github.com/canonical/microk8s/pull/3102 to 1.23
=> Include kernel module utils in the snap - 1.23

snap/snapcraft.yaml
Back porting https://github.com/canonical/microk8s/pull/3102 to 1.22
=> Package kernel module utils in the snap - 1.22

tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
Fixes #3121
- Launch a container with the new profile (testing with ubuntu:18.04, ubuntu:20.04, ubuntu:22.04)
- Install microk8s and run unit tests.
=> remove the apparmor parameters mount from the microk8s profile

README.md, build-scripts/patches/0000-Kubelite-integration.patch, snap/snapcraft.yaml
In preparation for 1.24:
- update the README
- use the 1.24 k8s patchs
- use golang from 1.18 stable
=> Prepare for 1.24

.github/workflows/check-unit-tests.yml, scripts/cluster/join.py, scripts/cluster/leave.py, tests/requirements.txt, tests/unit/cluster/test_join.py, tests/unit/cluster/test_leave.py, tox.ini
This PR unifies CLI help messages for join and leave commands.
```bash
$ microk8s join --help
Join a cluster: microk8s join <master>:<port>/<token> [options]
Options:
--skip-verify  skip the certificate verification of the node we are joining to (default: false).
```
```bash
$ microk8s leave --help
Usage: microk8s leave
With microk8s leave the node will depart from the cluster it is in.
```
```bash
$ microk8s join --help
Usage: join [OPTIONS] CONNECTION                                                                                                                                       
Join the node to a cluster                                                                                                                                           
CONNECTION: the cluster connection …
```
=> Fix inconsistent CLI help sections in join and leave  

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
- try to load using modprobe from the host, fallback to the
snap binary if that fails
- if br_netfilter module loads successfully, make sure to remove
the --proxy-mode=userspace flag from kube-proxy
=> improve handling for br_netfilter module (#3138)

microk8s-resources/wrappers/microk8s.wrapper, snap/hooks/configure
Addons now can provide commands to the microk8s CLI by inserting executables under `$SNAP_COMMON/plugins`.
E.g. `microk8s istioctl ...`
Added a condition to microk8s.wrapper so that it can scan and pass through to commands under `$SNAP_COMMON/plugins`.
Existing tests should cover the testing. Created a custom addon to populate `$SNAP_COMMON/plugins`, and called the populated executable by `microk8s executable ...`
There could be naming collisions with existing commands in microk8s, but internal commands take precedence in the case of a collision.
=> Enable addons to provide commands to the cli under $SNAP_COMMON/plugins

snap/hooks/remove
During remove hook, remove the vxlan.calico interface, as well the network namespaces created by the CNI for the pod workloads.
```
snap install microk8s
microk8s.kubectl create deploy nginx --image nginx --replicas 10
snap remove microk8s --purge
```
With the added changes, this should leave networking on the host in a clean state.
- Introduces a short delay in the remove hook (in order to delete the namespaces). The deletion itself takes very little time, so it should not be a problem, but let's keep an eye on it, especially on slower hardware.
- Possible issues with strict, but we already have `ip link delete cni0` (from the flannel days), so I don't expect this to be a problem.
This is probably something worth backporting to all supported tracks.
=> cleanup calico interface and cni network namespaces on remove

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-ctr.wrapper, snap/hooks/install, snap/snapcraft.yaml
A number of denials were thrown from the install and configure hooks. For example:
```
= Seccomp =
Time: May 30 22:55:39
Log: auid=4294967295 uid=0 gid=0 ses=4294967295 subj=snap.microk8s.hook.install pid=367587 comm="chgrp" exe="/snap/microk8s/3269/bin/chgrp" sig=0 arch=c000003e 260(fchownat) compat=0 ip=0x7fe972f5e44a code=0x50000
Syscall: fchownat
Suggestions:
* don't copy ownership of files (eg, use 'cp -r --preserve=mode' instead of 'cp -a')
* try the snapcraft preload plugin: https://github.com/sergiusens/snapcraft-preload
* adjust program to not use 'fchownat'
* ignore the denial if the program otherwise works correctly (unconditial chown is often just noise)
= AppArmor =
Time: May 30 22:55:43
Log: apparmor="DENIED" operation="capable" profile="snap.microk8s.hook.configure" …
```
=> Address most denials in install and configure hooks

microk8s-resources/wrappers/microk8s-kubectl.wrapper
Added a strict check so nano from snap is used for kubectl only when we are confined
Adds a `is_strict` check in `microk8s-kubectl.wrapper` and set `EDITOR="${SNAP}/bin/nano"` if strictly confined.
=> Strict check to use nano from snap for kubectl when we are strictly confined

microk8s-resources/actions/common/utils.sh
Added usergroup determination helper, updated hard-coded groups and new strict functions
Added `get_microk8s_group` bash function in `utils.sh` to determine user group based on strict confinement.
Changed hardcoded user groups to use the `get_microk8s_group` function.
Added `is_first_boot_on_strict`, `exit_if_not_root` and `enable_snap` helper functions for strict confinement checks.
Current tests should cover the changes
=> Closing the gap between strict and classic for bash utils

build-scripts/patches/runc/0001-apparmor-change-profile-immediately-not-on-exec.patch, build-scripts/patches/runc/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/patches/runc/0003-standard_init_linux-change-AppArmor-profile-as-late-.patch
Added patches for runc/containerd to work properly in strict confinement.
Added apparmor and privilege patches for runc/containerd for strict confinement
=> Add runc/containerd patches for strict confinement

microk8s-resources/wrappers/microk8s-images.wrapper, scripts/cluster/distributed_op.py, scripts/cluster/images.py, snap/snapcraft.yaml
Implement `microk8s images import` command, which can be used to import OCI images to all nodes of a MicroK8s cluster.
Assumes https://github.com/canonical/microk8s-cluster-agent/pull/4
- Refactor existing code in `distributed_op`: Pull out the code that retrieves the list of all current nodes and their callback tokens
- Implement `do_image_import`, similar to the existing `do_op`.
- Implement `microk8s.images import` command, importing images to the whole cluster.
Manually
Please check if I have missed something in the original code where the list of nodes is retrieved. There was a lot of duplicate code which I have tried to refactor.
I have tried to preserve the error messages in all cases.
=> Implement "microk8s images import" command

scripts/wrappers/common/utils.py
If we call kubectl simply, the system installed kubectl has precedence.
That may lead to some weird issues like an error due to a discrepancy
between kubectl cli and kubernetes API versions.
Closes: #3175
1. prepare `kubectl` on the system that always fails
$ sudo ln -s /bin/false /usr/local/bin/kubectl
$ kubectl; echo $?
1
1. install the patched snap
$ sudo snap install --dangerous --classic ./microk8s.snap
1. execute addon enable command, which was failing in #3175
1. confirm the command now works.
=> Make sure to use microk8s.kubectl

microk8s-resources/wrappers/microk8s-kubectl.wrapper, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper
Remove unnecessary changes from the strict patch for kubectl, leave and start since `run_with_sudo` is now strict aware and new strict logic is merged to the master branch.
Removed the changes in c792a245690867cadf08df01d63806f3fba99fa4 for `kubectl` `start` and `leave` wrappers.
=> Remove unnecessary changes from the strict patch for kubectl, leave and start

snap/hooks/configure
Closes #3086
Snap has been pushed to `latest/edge/certcheck`. Test with:
```
juju deploy microk8s -n 3 --constraints 'mem=4G' --config channel=latest/edge/certcheck
```
=> restart the cluster agent if the cert hashes do not match

scripts/wrappers/common/utils.py
Backport of https://github.com/canonical/microk8s/pull/3176 to 1.24 branch
=> [Backport 1.24] Make sure to use microk8s-kubectl.wrapper (#3176)

scripts/wrappers/common/utils.py
Backport of https://github.com/canonical/microk8s/pull/3176 to 1.22 branch
=> [Backport 1.22] Make sure to use microk8s-kubectl.wrapper (#3176)

snap/hooks/configure
In the configure hook we wait for the services to come up and apply the CNI manifest. In strict the snapctl will start services only after the configure hook ends so there is no point in waiting for them. This behavior (services starting after the configure hook) is present only in the snaps we get from the store, not in the ones we build locally.
Add an ! is_strict in the waiting of the apiserver in the configure hook. 
Try:
```
snap install microk8s --channel=latest/edge/MK-565
```
vs 
```
snap install microk8s --channel=latest/edge/strict
```
The first should install 2.5 minutes faster.
There is a difference in UX. Now the `snap install` will finish before K8s starts so users will need to `microk8s status --wait-ready`
=> Do not wait for services to start in configure hook in strict

scripts/cluster/images.py
Builds on top of #3183, review after that one is merged.
Implement "microk8s images export" command, which can be used to export all (or a selected set) of OCI images from the local containerd daemon.
This can be used in conjunction with the microk8s images import command of #3183, see the testing section for details.
This command is used as a useful wrapper around the `microk8s.ctr image export` command, solving some of its shortcomings.
```
ubuntu@cluster1:$ microk8s images export > all-images.tar
ubuntu@cluster2:$ microk8s images import < all-images.tar
Pushing OCI images to node1:25000
Pushing OCI images to node2:25000
Pushing OCI images to node3:25000
```
none
Doing a `microk8s.ctr image export` is not sufficient due to the following issue. This is the reason why we do the …
=> Implement "microk8s images export-local" command

scripts/inspect.sh
Do not use mount in the inspect script.
=> scripts: fix the inspect script not to call /bin/mount

snap/snapcraft.yaml
We have two ways to call a command, for example we can call inspect with `microk8s inspect` or `microk8s.inspect`. Both commands should have the same set of interfaces so that we have the same apparmor rules. This PR adds to the `microk8s` wrapper the same interface as the inspect script and the enable command. 
- Update the list of the interfaces used by the `microk8s` command
Manually build the snap and call `microk8s.inspect` and `microk8s inspect` commands and see they do not produce any denials.
=> Updating the interfaces user by the 'microk8s' command

snap/snapcraft.yaml
Use the content interface to pass the microk8s credentials to juju (or anyone else that may need them)
Update the content interface with the right path to the k8s credentials
```
snap install microk8s --channel=latest/edge/MK-530
```
Build a tester snap https://github.com/ktsakalozos/microk8s-content-tester.git and snap install it.
Connect the interface:
```
snap connect tester:microk8s  microk8s:microk8s
```
Get a shell into the tester snap:
```
sudo snap run --shell tester.hello
```
The client.config file is available:
```
ls -lh $SNAP_DATA/credentials/
```
This interface will be in the MicroK8s strict snap.
=> Pass credentials over the content interface

microk8s-resources/wrappers/run-containerd-with-args
References https://github.com/canonical/microk8s/pull/3190
Reverts regression introduced by https://github.com/canonical/microk8s/pull/3190/files#diff-15029275d146b90729a4c97b9541b16d2110d3582322181ffdd86e473b1b4842L57-L59
Reboot a microk8s instance, make sure that containerd does not get stuck during init.
Please double check that this is the intended behavior.
Could we possibly test this in a CI setting?
=> fix containerd initialization after reboot

snap/hooks/install
The link removal process for `cilium` CNI is repeated in multiple hooks. This process won't work on strict install hook since it checks if interfaces are connected, although all off the snap interfaces connect after the install hook. Also any links should already be cleaned in the `remove` hook, since this process is located there as well.
The `cilium` removal process is removed from the `install` hook.
=> Remove cilium CNI removal process from install hook

snap/hooks/configure
Fix regression from https://github.com/canonical/microk8s/commit/5ff8682524d29037a299ff54d09a885954668ad9#diff-7f1ea137a27c441e1be1e0ddb37091c53b09335f3124c2b47c4792e82b15290dR7
`$SNAP_DATA/var/lock/installed.lock` will not be there on old installs, which prevents the configure hook from running.
Revert change to only check for the lock file on the strict branch.
=> fix configure hook not running on old installs

build-scripts/set-env-variables.sh, snap/snapcraft.yaml
Update containerd to 1.6
- containerd upgrade to 1.6.6 (from 1.5.11)
- runc upgrade to 1.1.2 (from 1.0.3). Version retrieved from https://github.com/containerd/containerd/blob/v1.6.6/go.mod#L46
- use Go 1.18 to build containerd and runc
- Clean install with containerd 1.6.6, test create, scale, teardown a deployment
- Install 1.24, create a deployment, upgrade to containerd 1.6.6, scale and teardown the deployment
Pointing to the changelogs for runc and containerd:
- https://github.com/opencontainers/runc/blob/main/CHANGELOG.md
- https://github.com/containerd/containerd/releases
=> Update containerd to 1.6.6 and runc to 1.1.2

build-scripts/set-env-variables.sh, snap/snapcraft.yaml
Backport https://github.com/canonical/microk8s/pull/3264 to 1.22 branch
=> [1.22] upgrade containerd to 1.5.13

scripts/cluster/join.py
Backport parts of https://github.com/canonical/microk8s/pull/3216 to 1.21 branch.
=> [Backport 1.21] ensure kubelet --node-ip is set correctly when joining a cluster (#3216)

microk8s-resources/wrappers/run-containerd-with-args
Documentation:
https://www.kernel.org/doc/html/latest/admin-guide/LSM/index.html
Fixes:
https://github.com/canonical/microk8s/issues/3161
~Currently untested -- I need to get the necessary tooling working to build and test.~ Tested install and boot on Manjaro linux with kernel version 5.17.
Older kernels without the separate security module folders in /proc/.../attr might now fail to install microk8s.
* [n/a] The introduced changes are covered by unit and/or integration tests.
I don't think it's applicable in this case
=> Check the correct file for AppArmor confinement.

snap/snapcraft.yaml
Fix the following denial in `microk8s config`:
```
= Seccomp = 
Time: Jun 29 21:37:55 
Log: auid=1000 uid=1000 gid=1000 ses=3 subj=snap.microk8s.config pid=2093990 comm="ip" exe="/snap/microk8s/3502/bin/ip" sig=0 arch=c000003e 41(socket) compat=0 ip=0x7f92612cbc57 code=0x50000 
Syscall: socket 
Suggestions: 
* add account-control (if using NETLINK_AUDIT) 
* add audio-playback (if using NETLINK_KOBJECT_UEVENT) 
* add bluetooth-control (if using AF_{ALG,BLUETOOTH}) 
* add firewall-control (if using NETLINK_{FIREWALL,IP6_FW,NETFILTER,NF_LOG,ROUTE}) 
* add hardware-observe (if using NETLINK_{GENERIC,KOBJECT_UEVENT}) 
* add netlink-audit (if using NETLINK_AUDIT) 
* add netlink-connector (if using NETLINK_CONNECTOR) 
* add network (if using AF_INET{,6}, AF_CONN, NETLINK_ROUTE) 
* add …
```
=> Fix microk8s config denial

snap/snapcraft.yaml
Fixes the denial:
```
= AppArmor =
Time: Jun 29 20:23:22
Log: apparmor="DENIED" operation="open" profile="snap.microk8s.reset" name="/home/jackal/workspace/microk8s/" pid=1984983 comm="bash" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000
File: /home/jackal/workspace/microk8s/ (read)
Suggestion:
* add 'home' to 'plugs'
```
=> Fix reset denial on accessing home

tests/test-distro.sh
Added a strict flag to addons testing in `test-distro.sh` so addons tests that are expected to fail are skipped
Changed workdir from `/root/` to `/var/tmp`
Added a strict flag to addons testing in `test-distro.sh` so addons tests that are expected to fail are skipped
Changed workdir from `/root/` to `/var/tmp`
Manually run the `test-distro.sh` and existing tests should cover the changes.
=> Added a strict flag to skip addons tests that are expected to fail in test-distro

tests/test-distro.sh
Two fixes:
- remove the `--classic` flag on installing a locally built snap
- wait for the installation to finish. This fixes a race condition where the first unit test of test-addons fails because the cluster is not yet ready.
=> Imporved installation of snap before testing addons

.github/workflows/update-images.yml, build-scripts/update-images.sh
Add GitHub action to update list of images used by MicroK8s on a schedule.
The action installs MicroK8s from the requested track, enables some core addons, prints the list of images that are used and then creates a pull request for the respective branch on the microk8s repo.
This way, `build-scripts/images.txt` is the source of truth of the images required by MicroK8s for each release.
=> Add GitHub action to update list of images

snap/snapcraft.yaml
Build failure log (https://launchpadlibrarian.net/611225011/buildlog_snap_ubuntu_bionic_arm64_microk8s-1.23_BUILDING.txt.gz):
```
+ rm actions/gpu.yaml
rm: cannot remove 'actions/gpu.yaml': No such file or directory
Failed to run 'override-build': Exit code was 1.
```
=> [1.23] Fix build failures on arm64 and s390x

snap/snapcraft.yaml
Build failure log (https://launchpad.net/~microk8s-dev/+snap/microk8s-1.22/+build/1810946/+files/buildlog_snap_ubuntu_bionic_arm64_microk8s-1.22_BUILDING.txt.gz):
```
+ rm actions/gpu.yaml
rm: cannot remove 'actions/gpu.yaml': No such file or directory
Failed to run 'override-build': Exit code was 1.
```
=> [1.22] Fix build failures on arm64 and s390x

microk8s-resources/default-hooks/post-refresh.d/10-cni-reload, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/10-cni-restart-cilium, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/default-hooks/remove.d/10-cni-link, microk8s-resources/default-hooks/remove.d/10-cni-link-cilium, microk8s-resources/default-hooks/remove.d/20-cni-netns, microk8s-resources/default-hooks/remove.d/90-containers, microk8s-resources/wrappers/apiservice-kicker, scripts/kill-host-pods.py, scripts/run-lifecycle-hooks.py, snap/hooks/configure, snap/hooks/install, snap/hooks/post-refresh, snap/hooks/remove
Support adding custom hooks for `post-refresh`, `reconcile` and `remove` lifecycle events. This allows us to extend the add-on ecosystem with much richer addons, like addons that manage the complete lifecycle of custom CNIs, for example https://github.com/canonical/microk8s-core-addons/pull/28
- Move addon specific code out of the configure hook. Take this change to also remove obsolete code.
- Move hard-coded calico and cilium CNI refresh hooks out of apiservice-kicker and into reconcile hooks.
Tested along with https://github.com/canonical/microk8s-core-addons/pull/28
```
sudo snap install microk8s --classic --channel latest/edge/hooks
```
=> Support for post-refresh, remove and reconcile hooks for addons

microk8s-resources/wrappers/microk8s.wrapper
Small fix for the following issue:
```
ubuntu@dev:/var/snap/microk8s/common/plugins$ microk8s > /dev/null
basename: extra operand ‘/var/snap/microk8s/common/plugins/c’
Try 'basename --help' for more information.
ubuntu@dev:/var/snap/microk8s/common/plugins$ ls
a  b  c
```
=> Fix printing of available commands from addons

build-scripts/set-env-variables.sh
Make the 1.24 branch pickup patch releases from the upstream 1.24 and not from latest stable.
=> Pin the 1.24 track to 1.24 releases

build-scripts/addon-repositories.sh, build-scripts/addons/repositories.sh, build-scripts/build-component.sh, build-scripts/components/README.md, build-scripts/components/cni/build.sh, build-scripts/components/cni/patches/0001-single-entrypoint-for-cni-tools.patch, build-scripts/components/helm/build.sh, build-scripts/components/kubernetes/build.sh, build-scripts/components/migrator/build.sh, snap/snapcraft.yaml
Follow up PR for #3324 
- Move logic of initializing addon repositories out of snapcraft.yaml
- Specify the build directory for each component, which prevents rebuilding all components when a single one is changed
- Build kubelite with CGO_ENABLED=0
- Build go-migrator with CGO_ENABLED=0
- Move `snapcraftctl set-version` in a separate build step for simplicity
- Ensure runc (which requires CGO) has `build-attributes: [no-patchelf]` set
- Remove `build-attributes: [no-patchelf]` from parts that do not need it (microk8s-addons, kubernetes)
- Build the containernetwork plugins into a single binary, further reducing the installation size (cni tools reduced from 65MB to 8MB).
=> Follow improvements for snapcraft build pipeline

snap/snapcraft.yaml
The gpu.yaml file was removed when we upgraded the gpu operator.
In s390x builds we are trying to delete this file and we are failing the build. This PR fixes this issue.
=> Fix s390x build. gpu.yaml as it is not in our repo anymore

microk8s-resources/default-args/kubelet
By default, write kubelet logs to `SNAP_COMMON/var/log`. This is to reduce the diff with the strict patch.
=> Kubelet logs in SNAP_COMMON

build-scripts/components/flanneld/build.sh, build-scripts/components/flanneld/patches/0001-disable-udp-backend.patch, build-scripts/components/flanneld/version.sh
Update flannel to version 0.15.1 and build from source instead of pulling in binaries.
- Build flannel from source
- Update flannel to version 0.15.1
=> update flanneld to v0.15.1 and remove unused backends

microk8s-resources/wrappers/apiservice-kicker, snap/hooks/configure
Fixes the following issue on Xenial:
```
Aug 04 14:11:24 test-xenial microk8s.daemon-apiserver-kicker[4291]: RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
Aug 04 14:11:24 test-xenial microk8s.daemon-apiserver-kicker[4291]: This system supports the C.UTF-8 locale which is recommended.
Aug 04 14:11:24 test-xenial microk8s.daemon-apiserver-kicker[4291]: You might be able to resolve your issue by exporting the
Aug 04 14:11:24 test-xenial microk8s.daemon-apiserver-kicker[4291]: following environment variables:
Aug 04 14:11:24 test-xenial microk8s.daemon-apiserver-kicker[4291]:     export LC_ALL=C.UTF-8
Aug 04 14:11:24 test-xenial …
```
=> export LC_ALL and LANG to fix issues with Click

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, scripts/inspect.sh, scripts/wrappers/common/cluster/utils.py, snap/hooks/configure, snap/hooks/remove, upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh, upgrade-scripts/001-switch-to-dqlite/commit-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-node.sh
Cleanup legacy code for pre-Kubelite service names
The services are no longer used for a number of minor releases (kube control plane from 1.19, docker from 1.15), and snapctl is properly managing killing the services.
=> Cleanup stale references to removed services

snap/hooks/configure
We do not need to have microk8s as a system group.
Closes https://github.com/canonical/microk8s/issues/3373
Do not create microk8s as a system group in configure hook
Manual testing
None. System groups are just a convnetion.
=> Do not create microk8s as a systemgroup

scripts/wrappers/addons.py
The core and community addons repositories are packaged inside the $SNAP. When these repos are added they are git cloned under $SNAP_COMMON following the branch the repo has in the $SNAP. The branch of the repo in the $SNAP may change as we ship new releases ie, main, 1.24, 1.25 etc. This change will cause the `git pull` performed in the `microk8s addons repo update` to fail because the branch name we follow disappeared. In this case we need to re-add the repository. 
Fixes: https://github.com/canonical/microk8s/issues/3392
Update the `microk8s addons repo update` command to be able to detect if the name of the branch a repository followed has changed.
To reproduce:
```
sudo snap install microk8s --channel=latest/edge --classic
sudo snap refresh microk8s --channel=1.24/stable
sudo …
```
=> Handle brnaches that changed names for local repos

build-scripts/build-component.sh, build-scripts/components/README.md, build-scripts/components/kubernetes/build.sh, build-scripts/components/kubernetes/pre-patch.sh
Ensure that kubectl and kubelet report a clean Kubernetes version.
Before:
```
$ microk8s kubectl get node
NAME   STATUS   ROLES    AGE     VERSION
node   Ready    <none>   5d18h   v1.24.3-2+63243a96d1c393
```
After:
```
$ microk8s kubectl get node
NAME   STATUS   ROLES    AGE     VERSION
node   Ready    <none>   5d18h   v1.24.3
```
Optionally, we could add `+uk8s1` suffix, but we have decided against it at the moment.
- Add an optional `pre-patch.sh` step when building components.
- Use kubernetes machinery to save the source version prior to the kubelite patches.
Verify output of `kubectl version` and `kubectl get node` (contains version reported by the kubelet)
There should not be any. This ensures the Kubernetes version is a valid semantic version string.
=> Clean Kubernetes version reported by kubectl and kubelet

snap/hooks/configure, tox.ini
In classic we do not set any state, so if you had a strict deployment and you did not connect all interfaces the message you get is "blocked: please connect some interfaces". This message persists removals and re-installations of the snap. In this PR the classic snap sets the status message so it cleans any old one.
=> Clear old posibly failed state of strict deployments

.github/workflows/build-snap.yml, .github/workflows/check-formatting.yml, .github/workflows/check-unit-tests.yml
Update GitHub actions workflow for building and testing the MicroK8s snap.
The build step and each test runs in a separate job, so that it is easier to see which jobs are failing. Further, the tests are now running in parallel (instead of running sequentially and manually removing-reinstalling the snap multiple times), reducing the total CI time from sum(T_tests) to max(T_tests).
To be merged after https://github.com/canonical/microk8s/pull/3406, since there will be conflicts
=> Run CI tests in parallel

microk8s-resources/wrappers/run-containerd-with-args
The cgroup2 mount may sometimes appear as:
```
$ mount -t cgroup2
none on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
```
=> Improve check for cgroup2 availability

tests/test-distro.sh
Call tests from `/root` instead of `/var/tmp`.
Addresses the following issue in strict confinement:
```
15:53:51  Retrying /snap/bin/microk8s.kubectl apply -f /var/tmp/tests/templates/ingress.yaml
15:53:54  error: open /var/tmp/tests/templates/ingress.yaml: permission denied
15:53:54  
15:53:54  Will not test ingress
```
=> Attempt to fix test-upgrade.py under strict confinement

build-scripts/components/kubernetes/version.sh, build-scripts/eksd/build.sh, build-scripts/eksd/parse-manifest.py, snap/snapcraft.yaml
Set kubernetes version based on manifest, set snap version as eskd version
Added the ability to set the kubernetes version based on the fetched eksd manifest
Set snap version to eksd version instead of kubernetes version
Organized and cleaned up code
Manually tested by snapping and installing the snap.
=> Set kubernetes version based on manifest, set snap version as eskd version 

scripts/wrappers/join.py
Closes #3431 
Needs backporting to all supported MicroK8s tracks.
=> Ignore --hostname-override from kubelet arguments when joining

scripts/cluster/join.py
=> [Backport 1.24] Ignore --hostname-override from kubelet arguments when joining (#3434)

scripts/cluster/join.py
Backport #3434 and #3441 to 1.22 branch
=> [Backport 1.22] Ignore --hostname-override kubelet flag when joining a cluster

scripts/cluster/join.py
=> [Backport 1.23] Ignore --hostname-override from kubelet arguments when joining (#3434)

build-scripts/components/cluster-agent/version.sh, tests/test-distro.sh
The airgap test is failing with:
```
21:32:59  error: unrecognized condition: "jsonpath={.status.numberReady}=1"
21:32:59  waiting for calico
```
=> Fix the airgap test on 1.22

snap/hooks/install
This might happen if Juju is installed, due to the content interface. Fixes https://github.com/canonical/microk8s/issues/3455
- Backport to `strict` branch after merge
cc @mthaddon
=> Do not fail install of credentials directory already exists

microk8s-resources/wrappers/apiservice-kicker, scripts/launcher.py, snap/hooks/connect-plug-configuration, snap/hooks/disconnect-plug-configuration, snap/snapcraft.yaml, tests/test-cluster.py, tests/unit/test_launcher.py, tests/unit/yamls/invalid-launcher.yaml, tests/unit/yamls/valid-launcher.yaml, tox.ini
Allow for launch configurations in yaml
- A launcher python script that can handle configurations with a certain schema.
- Content interface.
- Unit and integration tests.
Unit tests: `tox -e scripts`
Integration tests: `sudo -E ./tests/test-distro.sh ubuntu:18.04 latest/strict latest/edge/MK-735`
=> Launcher for launch configurations handling only addons

snap/hooks/configure, tests/test-airgap.sh, tests/test-distro.sh
Two fixes to get the tests passing:
- in the airgap test add the public.ecr.aws registry
- in the configure hook handle the case where we are moving from a non k8s-dqlite installation to one that has this service
=> Disable airgap test for 1.23-eksd

build-scripts/components/etcd/build.sh, build-scripts/components/etcd/version.sh
Upgrade etcd to 3.5.5 for 1.26 onwards
Currently in draft to get a build and initiate testing.
=> (1.26+) update etcd to v3.5.5

microk8s-resources/wrappers/run-kubelite-with-args, scripts/find-resolv-conf.py
Auto-configure resolv.conf file used by kubelet for host DNS resolution.
- By default `/etc/resolv.conf` is used. In most systemd systems, this points to 127.0.0.53, which is the loopback address for the local resolver, and is unusable inside pods.
- In most OSes, /run/systemd/resolve/resolv.conf will instead have a list of reachable upstream nameservers.
- Only change the resolv.conf file if all nameservers are non-loopback addresses. This is checked with find-resolv-conf.py. Otherwise, no configuration is changed, maintaining the old behaviour
- If user has already configured --resolv-conf, configuration will not be overwritten.
=> Auto-configure kubelet resolv.conf file with upstream nameservers

upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/001-switch-to-dqlite/commit-master.sh
This PR fixes the `microk8s enable ha-cluster` command.
- the cni-bin-dir is removed from the kubelet args
- we load the CNI after enabling ha-cluster (calico)
Manual
=> Fix enable ha-cluster

snap/snapcraft.yaml
Two fixes on the build process:
- rework the migrator part to use the 1.19 go lang that includes the os.WriteFile
- fix the runc build by setting  GO111MODULE=on
=> Fix runc and migrator builds, 1.24

snap/snapcraft.yaml, tox.ini
Two fixes on the build process:
- rework the migrator part to use the 1.19 go lang that includes the os.WriteFile
- fix the runc build by setting GO111MODULE=on
=> Fix runc and migrator builds, 1.23

snap/snapcraft.yaml
Two fixes on the build process:
- rework the migrator part to use the 1.19 go lang that includes the os.WriteFile
- fix the runc build by setting GO111MODULE=on
=> Fix the build of migrator and runc, 1.22

build-scripts/components/kubernetes/pre-patches/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/pre-patches/0001-Unix-socket-skip-validation-in-component-status.patch
Porting the pre-stable patches to 1.26.
=> Port kubelite patches to 1.26-alpha.3

upgrade-scripts/000-switch-to-calico/resources/calico.yaml
References #3458 
Upgrade Calico version to 3.23.5 for new clusters
- https://github.com/projectcalico/calico/blob/release-v3.23/calico/_includes/release-notes/v3.23.4-release-notes.md
- https://github.com/projectcalico/calico/blob/release-v3.23/calico/_includes/release-notes/v3.23.5-release-notes.md
We are interested in the following from the 3.23.4 release notes:
- Match full interface names in IP auto-detection default exclude list. https://github.com/projectcalico/calico/pull/6879 (@neoaggelos)
Manual testing and CI
A patchlevel version bump should not cause any issues, but let's see if CI uncovers anything.
=> Update to Calico 3.23.5 for new installs

scripts/wrappers/join.py, snap/hooks/configure
Previously, these paths included snap revision numbers, which would break after two snap refreshes
See https://kubernetes.slack.com/archives/CAUNWQ85V/p1668093680342589 for context
=> fix kubeconfig for worker node services

microk8s-resources/default-args/kubelet, snap/hooks/configure
Kubernetes 1.26 no longer accepts the `--log-dir` argument. Remove so that kubelet starts properly
Also removed unnecessary second sed call from #3554
=> 1.26 removed kubelet --log-dir argument

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-provider-id-update, snap/hooks/configure
EKSD installations of MicroK8s will automatically add providerID if they're running on EC2 machines.
Added some checks to configure hooks and added a new reconcile hook.
Manually tested by installing on EC2 and non EC2 instances.
=> Added auto add for provider id on eksd

microk8s-resources/actions/common/utils.sh, scripts/wrappers/common/utils.py
When the user has insufficient permissions, we suggest commands to run. We shouldn't suggest using the `-f` flag in `chown`, because this suppresses error messages which might be useful to the user.
Fixes #3534
Remove `-f` flag in `chown` in the "insufficient permissions" error.
N/A
N/A
N/A
=> remove -f flag from suggested chown cmd

microk8s-resources/wrappers/run-kubelite-with-args
Fixes
```
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32433]: ++ cat /var/snap/microk8s/4225/args/kubelet
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32434]: ++ grep --resolv-conf
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32436]: ++ gawk '{print $2}'
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32434]: grep: unrecognized option '--resolv-conf'
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32435]: ++ tr = ' '
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32434]: Usage: grep [OPTION]... PATTERN [FILE]...
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32434]: Try 'grep --help' for more information.
Nov 16 11:35:49 ip-172-31-13-224 microk8s.daemon-kubelite[32375]: + resolv_conf=
Nov 16 11:35:49 …
```
=> Ensure grep considers arguments as regex

build-scripts/components/k8s-dqlite/version.sh
Update k8s-dqlite to include https://github.com/canonical/kine/pull/9
=> Update k8s-dqlite to 1.0.5 to include Kine fix for 1.26

microk8s-resources/wrappers/run-kubelite-with-args
`userspace` proxy-mode is not allowed on the 1.26+ k8s https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#removal-of-kube-proxy-userspace-modes  so we remove it from the kube-proxy config if we find it there.
=> Remove the userspace proxy mode if present

microk8s-resources/default-hooks/reconcile.d/10-provider-id-update, snap/hooks/configure
Fix configure hook failing when EC2 endpoint is not reachable
Update configure hook so curl does not fail the entire hook if EC2 endpoint is unreachable.
Manually tested by installing the snap inside LXD containers on EC2 host.
=> [1.23-eksd] Fix configure hook failing when EC2 endpoint is not reachable

microk8s-resources/wrappers/run-kubelite-with-args, tox.ini
This came up from the strict testing where kubelite was failing with:
```
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162363]: ++ tr = ' '
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162364]: ++ gawk '{print $2}'
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162292]: + resolv_conf=
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162292]: + '[' -z '' ']'
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162365]: ++ /snap/microk8s/4354/usr/bin/python3 /snap/microk8s/4354/scripts/find-resolv-conf.py
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162365]: Traceback (most recent call last):
Δεκ 08 18:10:19 aurora microk8s.daemon-kubelite[4162365]:   File "/snap/microk8s/4354/scripts/find-resolv-conf.py", line 66, in <module>
Δεκ 08 18:10:19 aurora …
```
=> Set LC_ALL LANG in the kubelite wrapper so find-resolv-conf.py will not fail

README.md, build-scripts/components/kubernetes/patches/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/patches/0001-Unix-socket-skip-validation-in-component-status.patch
The master branch would be building 1.26 now so the pre-release patches are moved to the patches directory.
We also update the README.
=> Update the k8s patches for 1.26

snap/hooks/configure
References https://github.com/canonical/microk8s/issues/3375#issuecomment-1322023278
=> Ensure cp nodes upgraded to 1.25 don't start apiserver proxy

snap/hooks/configure, tox.ini
Backport https://github.com/canonical/microk8s/pull/3632 to 1.25 branch
=> [Backport 1.25] Ensure cp nodes upgraded to 1.25 don't start apiserver proxy

.github/workflows/build-installer.yml, installer/requirements.txt, installer/vm_providers/_multipass/_windows.py, installer/windows/microk8s.nsi
- Bump MicroK8s installer to 2.3.0
- Bump Multipass to 1.10.1
- Bump kubectl to 1.26.0
- Bump default microk8s version to 1.26
Also fixes some requirements, see relevant parts of https://github.com/ubuntu/homebrew-microk8s/pull/7
=> Installer 2.3.0

tests/test-upgrade-path.py, tests/utils.py
Closing upgrade path gap with strict
Closing upgrade path gap with strict
Manually tested by running `test-upgrade-path`
=> [main] Close the gap between test-upgrade-path in strict

installer/common/auxiliary.py
`microk8s kubectl` commands were affected in some cases by https://github.com/canonical/microk8s/pull/3142.
=> fix kubectl invocations in the microk8s installer

build-scripts/components/dqlite-client/version.sh, build-scripts/components/dqlite/version.sh, build-scripts/components/k8s-dqlite/version.sh, build-scripts/components/raft/version.sh
Bump k8s-dqlite to v1.1.1 to support disk-mode, with deps
- Update dqlite to v1.13.0 (needed for disk mode)
- Update go-dqlite to v1.11.6 (needed for go bindings of disk mode)
- Update raft to v0.16.0 (needed >= v0.14.0 for dqlite)
Marked as work in progress until linked PR https://github.com/canonical/k8s-dqlite/pull/38 is merged
A development build has been pushed to `latest/edge/dqlite-disk-mode`. Test with:
```bash
sudo snap install microk8s --classic --channel latest/edge/dqlite-disk-mode
echo '--disk-mode' | sudo tee -a /var/snap/microk8s/current/args/k8s-dqlite
sudo snap restart microk8s.daemon-k8s-dqlite
```
In the logs, you should see a log line that disk mode operation is enabled.
```log
Jan 16 15:04:36 u1 microk8s.daemon-k8s-dqlite[11443]: I0116 19:04:36.636870   11443 …
```
=> Bump k8s-dqlite to v1.1.1 to support disk-mode

scripts/inspect.sh
Closes #3270, also others that we are missing at the moment.
When running `microk8s inspect`, print a warning if the hostname contains uppercase letters, since we have seen this cause issues and confusion to users.
If there are uppercase letters, a message like this is printed to the screen:
```
root@U1:~# check_hostname
WARNING:  The hostname of this server is 'U1'.
Having uppercase letters in the hostname may cause issues with RBAC.
Consider changing the hostname to only have lowercase letters with:
hostnamectl set-hostname u1
```
=> check for uppercase letters in the inspect script

installer/windows/microk8s.nsi
Bump default MicroK8s version suggested by Windows installer
=> bump default install version to 1.26

tests/test-distro.sh
Run the GPU tests on the host since all tests are run in lxc containers
This work is in test-distro.sh
Manual
=> Run GPU tests on 1.26

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Add a function for all the services to remove deprecated arguments. Backporting https://github.com/canonical/microk8s/pull/3690 
Included a new util function for argument sanitization. Used this function in all the desired services.
=> Add arguments sanitisation when starting services (#3690) - 1.26

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, tests/test-upgrade-path.py
Add a function for all the services to remove deprecated arguments. Backporting https://github.com/canonical/microk8s/pull/3690 
Included a new util function for argument sanitization. Used this function in all the desired services.
=> Add arguments sanitisation when starting services (#3690) - 1.26-strict

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, tests/test-upgrade-path.py, tox.ini
Add a function for all the services to remove deprecated arguments. Backporting https://github.com/canonical/microk8s/pull/3690 to 1.25-strict
The --proxy-mode option is under a different business login in 1.25 so didn't remove it, by the extension of which there were not so many flags left in kube-proxy sanitization function, and hence removed it altogether.
=> Add arguments sanitisation when starting services (#3690) - 1.25-strict

microk8s-resources/microk8s.default.yaml, microk8s-resources/wrappers/apiservice-kicker, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml
Allow setting MicroK8s configuration using:
- `snap set microk8s config="$(cat config.yaml)"` commands.
- An existing configuration file on the disk during the snap installation (for now: `/etc/microk8s.yaml` and `/root/.microk8s.yaml`)
1. Configuration is only copied to `$SNAP_COMMON/etc/microk8s/{init,snap-set}.yaml` and is applied by the apiservice-kicker service. This decouples any long-running actions or actions that require the API server to be running (e.g. enable addons) from the actual snap installation.
2. If applied successfully, the files are renamed to have a `.applied` suffix and are then ignored. In the future, we might want to remove them completely after applying.
3. Configuration is applied using https://github.com/canonical/microk8s-cluster-agent/pull/11. In fact, this …
=> Init configurations during install or with `snap set microk8s config=<config>`

tests/test-airgap.sh
=> remove air-gapped registry when offline tests finishes for 1.26

snap/snapcraft.yaml
Build Kubernetes binaries with Go 1.19, following upstream.
=> [1.23] Use Go 1.19 to build Kubernetes

snap/snapcraft.yaml
Build Kubernetes binaries with Go 1.19, following upstream.
=> [1.24] Build Kubernetes with Go 1.19

tests/test-airgap.sh
=> Backport air-gapped registry container removal for 1.25

snap/hooks/install
Adjust install hook to support setting extra SANs to the apiserver certificates.
References https://github.com/canonical/microk8s-cluster-agent/pull/17
=> Support extra SANs using init configurations

microk8s-resources/wrappers/microk8s-join.wrapper
MicroK8s by default looks for `openssl.cnf` from `/usr/lib/ssl/openssl.cnf` which does not exist on some distributions like Red Hat / Fedora / CentOS.
Closes #3715
Explictly set the `openssl.cnf` path by setting `OPENSSL_CONF` environment variable for join script.
https://github.com/canonical/microk8s/blob/64d6d977ab3cf13624be44c78ddb65e77c06a649/microk8s-resources/wrappers/microk8s-join.wrapper#L7
Manually tested
=> fix: openssl config path error in some distros when joining a cluster

tests/test-airgap.sh
Remove the air-gapped registry when tests finish.
Remove the registry lxc container so after the test finishes.
=> Remove air-gapped registry when offline tests finishes

tests/test-airgap.sh
=> Backport air-gapped registry container removal for 1.24-eksd

tests/test-airgap.sh
=> Backport air-gapped registry container removal for 1.23-eksd

snap/snapcraft.yaml
Increase the start timeout of `daemon-containerd`.
Order the start of `daemon-kubelite` after it.
Closes #3684
Please see above; no user facing changes.
Please see #3684 for reproduction steps.
Apparently no regressions from increasing the `daemon-containerd` timeout to 5 minutes.
There might delays in the setup/commands performed by `daemon-kubelite` until
up to `waiting for containerd socket` in `run-kubelite-with-args`, as it now starts
_after_ `daemon-containerd`, and not concurrently with it anymore.
(I think this ^ might not be needed per association with Canonical already?)
=> Increase daemon-containerd timeout and order daemon-kubelite after it

microk8s-resources/actions/common/utils.sh, scripts/wrappers/refresh_certs.py, tests/unit/test_refresh_certs.py
Closes #3241
Replaces #3182, doing the same thing while touching less critical parts of the codebase.
Thanks @dud225 for the initial work.
=> microk8s refresh-certs use new csr.conf.template

scripts/wrappers/addons.py, tests/unit/test_addons.py
Closes https://github.com/canonical/microk8s/issues/3730
The root cause behind the issue is the way git treats repositories where the current user is different from the owner of the repository.
Temporarily work around the issue by requiring root, which also makes sense from a security perspective.
=> Require root for microk8s addons commands

build-scripts/components/cluster-agent/build.sh, microk8s-resources/default-args/cluster-agent-env, microk8s-resources/wrappers/run-cluster-agent-with-args, snap/snapcraft.yaml
Same as k8s-dqlite and k8s services. Building the cluster-agent with cgo support and having an env file to load the right libs before starting the service.
=> Cluster agent built for FIPS

microk8s-resources/wrappers/apiservice-kicker, snap/hooks/install
Implement side-loading of images during cluster initialization. This is done by adding `tar` image archives in well-known directories. After a few iterations, looks like this is one of the easiest ways for cluster administrators to automatically sideload images into containerd during provisioning.
On one node, to download all required images:
```
$ sudo snap install microk8s --classic
$ sudo microk8s images export-local images.tar
```
On node where you want to sideload images, ensure they are at `/var/snap/microk8s/common/sideload/` and install the snap:
```
$ mkdir -p /var/snap/microk8s/common/sideload
$ cp images.tar /var/snap/microk8s/common/sideload
$ sudo snap install ./microk8s.snap --dangerous --classic
```
Will do as a separate PR, our airgap tests are currently "imperative" and …
=> Initial implementation of image side-loading during install

snap/snapcraft.yaml
This is a cherry-pick of PR #3685 to release branch 1.24 (trivial backport).
Summary of test steps (see PR for details):
Before:
```
$ sudo snap install microk8s --classic --channel=1.24/edge
$ snap info microk8s | grep 1.24/edge:
1.24/edge:             v1.24.10        2023-02-03 (4638) 224MB classic
...
$ systemctl show snap.microk8s.daemon-containerd.service | grep NRestarts
NRestarts=3
$ systemctl show snap.microk8s.daemon-kubelite.service | grep NRestarts
NRestarts=13
```
After:
```
$ git log --oneline -2
ca3b5bb31b0c (daemon-containerd-timeout-1.24) Increase daemon-containerd timeout and order daemon-kubelite after it (#3685)
6bc7a2979987 (origin/1.24) update list of images used by 1.24 (#3727)
$ sudo snap install ./microk8s_v1.24.10_amd64.snap --classic --dangerous
...
$ systemctl …
```
=> [backport/1.24] Increase daemon-containerd timeout and order daemon-kubelite after it

snap/snapcraft.yaml
This is a cherry-pick of PR #3685 to release branch 1.26.
Summary of test steps (see PR for details):
Before:
```
$ sudo snap install microk8s --classic --channel=1.26/edge
$ snap info microk8s | grep 1.26/edge:
1.26/edge:             v1.26.1         2023-02-09 (4676) 176MB classic
...
$ systemctl show snap.microk8s.daemon-containerd.service | grep NRestarts
NRestarts=3
$ systemctl show snap.microk8s.daemon-kubelite.service | grep NRestarts
NRestarts=14
```
After:
```
$ git log --oneline -2
cccfd53438b7 (HEAD -> daemon-containerd-timeout-1.26) Increase daemon-containerd timeout and order daemon-kubelite after it (#3685)
422fd562d7a6 (origin/1.26) update containerd to 1.6.15 (#3746)
$ sudo snap install ./microk8s_v1.26.1_amd64.snap --classic --dangerous
...
$ systemctl show …
```
=> [backport/1.26] Increase daemon-containerd timeout and order daemon-kubelite after it

snap/snapcraft.yaml
This is a cherry-pick of PR #3685 to release branch 1.25.
Summary of test steps (see PR for details):
Before:
```
$ sudo snap install microk8s --classic --channel=1.25/edge
$ snap info microk8s | grep 1.25/edge:
1.25/edge:             v1.25.6         2023-02-09 (4677) 175MB classic
...
$ systemctl show snap.microk8s.daemon-containerd.service | grep NRestarts
NRestarts=3
$ systemctl show snap.microk8s.daemon-kubelite.service | grep NRestarts
NRestarts=12
```
After:
```
$ git log --oneline -2
b0a417c039c8 (daemon-containerd-timeout-1.25) Increase daemon-containerd timeout and order daemon-kubelite after it (#3685)
a15a5691c159 (origin/1.25) Update containerd to 1.6.15 (#3745)
$ sudo snap install ./microk8s_v1.25.6_amd64.snap --classic --dangerous
...
$ systemctl show …
```
=> [backport/1.25] Increase daemon-containerd timeout and order daemon-kubelite after it

.github/workflows/update-images.yml
Run update-images for 1.26 and 1.24-eksd branches
=> update images for 1.26 and 1.24-eksd branches

scripts/wrappers/common/utils.py
Improve the warning messaging because the "Chained operations" are our internal code name for enabling/disabling addons in one command.
=> Improve chained ops warning

build-scripts/components/containerd/build.sh, build-scripts/components/containerd/patches/0001-microk8s-sideload-images-plugin.patch, microk8s-resources/wrappers/apiservice-kicker
Use a configurable containerd plugin for image sideloading instead of an apiservice kicker hook.
Improvements:
- Apiserver kicker service is not always running (e.g. for MicroK8s worker nodes), whereas the containerd plugin will always pick up images.
- Containerd plugin is configurable and runs in a lightweight thread as part of containerd itself. No configuration is needed out of the box. Example configuration:
```toml
[plugins."io.containerd.service.v1.sideload-images"]
interval = "0s"
sources = ["$SNAP_COMMON/my-sideload-images-dir"]
namespace = "my-other-namespace"    
```
- Less traffic over the containerd socket. This is more relevant for large image blobs.
=> Use a containerd plugin for sideloading images

scripts/wrappers/common/utils.py, tests/unit/test_disable.py
Use a lockfile to prevent `microk8s enable/disable` operations from running concurrently.
Draft until we consider the new UX acceptable.
=> Prevent concurrent addon enable/disable operations

build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh, microk8s-resources/default-args/containerd-env
Build containerd and runc with CGO enabled so it can use FIPS certified libs
Changes in the build scripts and the env containerd runs under.
Manual. Enable GOFIPS and give it a wrong lib path to verify it is trying to find libs from there.
=> Containerd and runc build with CGO

build-scripts/components/dqlite-client/version.sh
Update go-dqlite to 1.11.7 for important bug-fixes https://github.com/canonical/go-dqlite/releases/tag/v1.11.7
=> Bump go-dqlite to 1.11.7

scripts/wrappers/join.py, tests/test-cluster.py
The error occurred during the joining of the worker node. An empty serviceaccount was created which was not required by the microk8s agent and hence was causing the node to fail when it left the cluster.
Closes #3708 
Local testing.
Will also create backports for this.
=> Fixed error for worker node's leaving operation which caused unresponsiveness in the node

microk8s-resources/wrappers/microk8s-ctr.wrapper
Do not allow `microk8s ctr` command if user do not have permission.
Add check to the `ctr` wrapper to make sure the user has permission before continuing.
None
* [ X ] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [ X ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
=> do not allow the ctr command if no permission

build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh
Statically link containerd and runc binaries in the snap.
Fixes issues with GLIBC version incompatibilities across a range of operating systems.
=> Static link containerd and runc

build-scripts/components/k8s-dqlite/build.sh
Replaces #3835 
Backport #3846 to 1.26 branch. Do not upgrade k8s-dqlite version as it would require a minor upgrade of dqlite.
=> build k8s-dqlite with go1.19.5

build-scripts/components/k8s-dqlite/build.sh, build-scripts/components/k8s-dqlite/version.sh
Build k8s-dqlite using Go 1.19.5 to temporarily workaround issues around TLS session resumption
Also bump k8s-dqlite to 1.1.2 which includes the upstream fixes in go-dqlite 1.11.7
=> Fix k8s-dqlite TLS issues

build-scripts/components/dqlite/build.sh, build-scripts/components/raft/build.sh
I was confused, `--enable-debug` turns on assertions, not debug info. These libraries are not stripped in any case, and in #3821 I'm working on another approach to getting better diagnostics.
Reverts canonical/microk8s#3750
Signed-off-by: Cole Miller <cole.miller@canonical.com>
=> Revert "Build libdqlite and libraft with debuginfo"

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kubelet
Fixes
```
Mar 21 06:42:43 u1 microk8s.daemon-kubelite[69528]: Error: failed to parse kubelet flag: unknown flag: --container-runtime
Mar 21 06:42:43 u1 microk8s.daemon-kubelite[69528]: F0321 06:42:43.601537   69528 daemon.go:57] Kubelet exited failed to parse kubelet flag: unknown flag: --container-runtime
Mar 21 06:42:43 u1 microk8s.daemon-kubelite[69528]: Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
```
Also contains a fix for the `skip_opt_in_local_config` helper function. This is because removing the `container-runtime` flag would also remove the `container-runtime-endpoint` flag, which is not desired.
=> Fix kubelet arguments for 1.27

installer/cli/microk8s.py, installer/common/definitions.py, installer/vm_providers/_multipass/_multipass.py
I added the ability to specify the image version (currently fixed at 18.04) in the `microk8s install` command. While I haven't seen an issue associated with it, Windows seems to have some instability in restarting an Ubuntu 18.04 image. 20.04+ is much more stable, which contributes to a much better microk8s experience.
User facing change: the `microk8s install` command now has a `--image` option. The help message was updated as well.
Behind the scenes, I simply added a new spec that's passed into the microk8s._launch method, and handled appropriately. Also added a default so that 18.04 is the default image. As a result, the default behavior remains unchanged.
I ran the `microk8s install` method a couple times on my Windows machine to confirm that I could install different versions.
No. …
=> Added support for specifying the image that is used by multipass

snap/hooks/install
The default config paths might be confusing for users, especially they implicitly require extra directories to be created.
For classic confinement, enable reading microk8s launch configuration from an `/etc/microk8s.yaml` config file as well.
=> support config from /etc/microk8s.yaml

tests/test-cluster.py
Increasing the time to detect the node in cases where `k get nodes` returned an empty list.
=> [1.23] Worker node leave fix

tests/test-cluster.py
Increasing the time to detect the node in cases where `k get nodes` returned an empty list.
=> [1.23-eksd] Worker node leave fix

tests/test-cluster.py
The previous assumption of tracks being of the form `foo/bar` may not always be true, especially in the CI pipeline, which can also be of the form `foo/bar/baz`. The fix for this is to use a list for these separate sections.
=> Fix track to take channels with multiple '/'

tests/test-cluster.py
=> Handle node when leaving the cluster - 1.24-eksd

tests/test-cluster.py
=> Handle node when leaving the cluster - 1.26

tests/test-cluster.py
=> Handle node when leaving the cluster

tests/test-cluster.py
=> Handle node when leaving the cluster - 1.26-strict

tests/test-cluster.py
=> Handle node when leaving the cluster - 1.25-strict

tests/test-cluster.py
=> Handle node when leaving the cluster - 1.25-eksd

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, scripts/wrappers/join.py
Regenerate *apiserver* certificate `server.crt` from *apiservice-kicker*, if it is not issued by the current CA `ca.crt`. If configuration `csr.conf`/`csr.conf.rendered` is missing, render them, and regenerate `front-proxy-client.crt` as well, as changes may be introduced and both certificates will then be created from the same configuration.
It streamlines the process of regenerating certificates from *apiservice-kicker*, by introducing some separation of concerns between the two cases:
* generating certificates due to a CA change (or absence of a certificate)
* generating new certificates with new SANs due to an address change
Further, an existing `csr.conf` will **not be rerendered and replaced automatically** on cluster join, with the following rationales. Where 1. has already been …
=> Regenerate apiserver certificate if not matching CA - Fixes #3785 #3321 #3068 #2123 

scripts/wrappers/common/utils.py, scripts/wrappers/status.py
MicroK8s status takes a long time when dqlite is not running. This is an issue because microk8s status in control plane nodes will always attempt to query the status of the dqlite database.
This is false in the following conditions:
- non-HA setup; etcd is used instead and dqlite is not running
- custom setup; an external etcd data store is used, not dqlite
Now we check the etcd endpoints configured in apiserver and act accordingly:
(a) if dqlite, keep current behaviour
(b) if non-ha, print etcd single-node address
(c) if etcd, print list of members (perhaps verify status with etcdctl member list)
tested locally
=> Add conditions when using etcd instead of dqlite

tests/test-airgap.sh
Adding the AWS ECR registry to 1.25-eksd
=> [1.25-eksd] Added ECR to airgap registries

tests/libs/utils.sh
`test_distro.sh` will prioritize command line parameters first, but will use command line options like `--distro` if parameters are not specified.
=> Accept both parameters and options for test-distro

tests/test-cluster.py
Back porting this fix.
We need to wait for a node to join in case where there is a node marked as NotReady *or* if we do not see the joining node in the list of all nodes.
=> Change the condition for nod (#3870)

scripts/wrappers/common/utils.py
Fixes
```
root@u1:~# microk8s enable dns 1.1.1.1
WARNING: Do not enable or disable multiple addons in one command.
This form of chained operations on addons will be DEPRECATED in the future.
Please, enable one addon at a time: 'microk8s enable <addon>'
Infer repository core for addon dns
...
```
=> Specifying addon arguments should not print warnings

microk8s-resources/wrappers/microk8s-start.wrapper
The microk8s start script has a bug based on a race condition for the deletion of the stopped.lock file. The start script first starts the snap services and then tries to remove the stopped.lock file. The problem is that run-kubelite-with-args has a [deletion code block](https://github.com/canonical/microk8s/blob/f7cac669e495108700407701243816552021a9f4/microk8s-resources/wrappers/run-kubelite-with-args#L35-L40) for the same lock file. And if this block is executed before the start script finishes, t[he removal of the lock file](https://github.com/canonical/microk8s/blob/f7cac669e495108700407701243816552021a9f4/microk8s-resources/wrappers/microk8s-start.wrapper#L58) in the start script fails because the file does not exist.
=> Added force deletion to ignore missing lock file in start script

tests/test-cluster.py
This PR disables two tests when testing strict releases.
The `test_calico_interfaces_removed_on_snap_remove` is already disabled in the strict snap. This PR will make the strict patch cleaner.
The `test_mixed_version_join` is new. On lxc when this test runs we receive apparmor denials such as:
```
[ 1167.513699] audit: type=1400 audit(1682088400.887:5468): apparmor="DENIED" operation="chown" profile="snap.microk8s.add-node" name="/var/snap/microk8s/5017/credentials/cluster-tokens.txt" pid=51115 comm="chgrp" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
[ 1167.516199] audit: type=1400 audit(1682088400.891:5469): apparmor="DENIED" operation="chmod" profile="snap.microk8s.add-node" name="/var/snap/microk8s/5017/credentials/cluster-tokens.txt" pid=51117 comm="chmod" requested_mask="w" …
```
=> Stop testing mixed version clusters on lxc+strict

scripts/wrappers/common/utils.py, scripts/wrappers/status.py
covers part of #3927
* exit with error code 1 if cluster is not ready after timeout
* refactor wait_for_ready to eliminate loop calculation
* refactor variable name according to PEP8
=> exit with error code 1 if cluster is not ready after timeout

build-scripts/generate-bom.py, scripts/inspect.sh, snap/snapcraft.yaml
Generate bill of materials when building snap. Include this bill of materials when building an inspection report.
Example bill of materials, built from this commit. The following items are included:
- Tool versions (gcc and go)
- Component repositories, version, git revision, list of patches
- MicroK8s commit
```json
{
"microk8s": {
"version": "MK-1128/bom",
"revision": "eb2c74f2fa089d42ca9ae6082c1730d22c13250d"
},
"tools": {
"go": [
"go version go1.20.3 linux/amd64"
],
"gcc": [
"gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0",
"Copyright (C) 2019 Free Software Foundation, Inc.",
"This is free software; see the source for copying conditions.  There is NO",
"warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
],
"python": [
"Python 3.8.10 (default, Mar 13 2023, …
```
=> Generate bill of materials when building snap

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kubelet, snap/hooks/configure
Backport https://github.com/canonical/microk8s/pull/3961 to 1.27
=> 1.27 - Allow argument to configure cadvisor containerd connection

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kubelet
The observability addon fails to pull some metrics on containers. We allow the containerd argument so cadvisor knows where to search for the running containers.
Allow `--containerd` argument and put it in the default arguments.
Manual
=> Allow argument to configure cadvisor containerd connection

microk8s-resources/wrappers/run-kubelite-with-args, snap/hooks/remove
Fixes #3971
I used the kube-proxy arg file to get the proper CIDR.
I decided to also leave the existing files as a fallback when kube-proxy doesn't have the value.
I DID NOT TEST.
I do not have the capabilities to build and deploy a cluster from code.
Change should be straightforward enough.
Existing iptables rules with the wrong IP will remains.
=> fixes iptables rule with custom CIDR

build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh
=> [Backport 1.26-strict] Static link containerd and runc

build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh
=> [Backport 1.26] Static link containerd and runc

build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh
=> [Backport 1.25] Static link containerd and runc

tests/libs/airgap.sh
Backport https://github.com/canonical/microk8s/pull/4005 to 1.27
=> Fix air gap test 1.27

tests/libs/airgap.sh, tests/libs/utils.sh, tests/lxc/install-deps/ubuntu_16.04, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04
- Setting `DEBIAN_FRONTEND=noninteractive` in our CI tests.
- Improvements in airgap test flakiness
=> [Master] Set non-interactive mode for our tests and robust airgap test

tests/lxc/install-deps/ubuntu_16.04, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-distro.sh
Backport https://github.com/canonical/microk8s/pull/3996 to 1.26
=> [1.26] Set non-interactive mode for our tests

build-scripts/components/cluster-agent/version.sh, build-scripts/components/containerd/build.sh, build-scripts/components/runc/build.sh, microk8s-resources/wrappers/microk8s-start.wrapper, scripts/wrappers/join.py, tests/lxc/install-deps/ubuntu_16.04, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py, tests/test-distro.sh
Backport:
- CI fixes
- static builds of containerd/runc
- leave worker node test
=> 1.25 strict update with latest 1.25 changes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-add-node.wrapper, scripts/wrappers/addons.py, scripts/wrappers/common/cluster/utils.py, scripts/wrappers/common/utils.py, snap/hooks/configure, tests/unit/cluster/test_join.py
This PR makes sure that when we create or edit files and we have applied CIS hardening we keep the file ownership group root and set access permissions to 600
This PR builds on top of https://github.com/canonical/microk8s/pull/4013 so it has to be merged after it.
=> Permissions fixes in CIS hardened deployments

microk8s-resources/default-args/admission-control-config-file.yaml, microk8s-resources/default-args/eventconfig.yaml, microk8s-resources/default-args/kube-apiserver
We make the CIS Checks 1.2.9 for `eventratelimit` default argument for kube-apiserver.
The default configuration is set to 
```
limits:
- type: Server
qps: 5000
burst: 20000
```
to limit the requests to API server. This can definitely be changed according to the user's needs.
Locally build the snap to verify the presence of arguments and configuration in `/var/snap/microk8s/current/args`
Other Relevant PR: https://github.com/canonical/microk8s-core-addons/pull/195
=> Set EventRateLimit by default

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/manifests/kube-apiserver-to-kubelet.yaml, microk8s-resources/default-hooks/reconcile.d/20-apiserver-to-kubelet, scripts/wrappers/common/cluster/utils.py, snap/hooks/configure
This PR configures MicroK8s correctly so it can support kubelet webhook auth mode properly.
First we make sure the certificate kubelet presents to its 10250 interface is valid for the host it runs on. This requires we use the `-extfile` flag of `openssl x509 -req`.
Second we make sure there are RBAC rules so that when the API server asks for things like for example pod logs that request is allowed. We apply the respective ClusterRules as part of the reconciliation loop run by the apiserver-kicker. 
Fixes: https://github.com/canonical/microk8s/issues/3965
=> Configure kubelet webhook auth-mode

microk8s-resources/default-args/kube-apiserver
Add the argument `--kubelet-certificate-authority` as default in kube api-server.
Tested locally by building the snap and enabling and disabling CIS addon.
=> Add --kubelet-certificate-authority as default in api-server

.github/workflows/build-installer.yml, installer/common/definitions.py, installer/vm_providers/_multipass/_windows.py, installer/windows/microk8s.nsi
update homebrew formula to newest microk8s version (1.27) and ubuntu version (22.04)- otherwise Mac Users can't use it.
Closes #4045
References #4045
microk8s version changes from 1.26 --> 1.27
ubuntu version from 18.04 --> 22.04
=> Update microk8s version to 1.27 and ubuntu version to 22.04

snap/hooks/install
Closes https://github.com/canonical/microk8s/issues/4041
=> [1.27] ensure $SNAP_DATA/credentials exists during init configuration

snap/hooks/install
=> [1.27 strict] ensure $SNAP_DATA/credentials exists during init configuration

snap/snapcraft.yaml
References #4047, https://github.com/canonical/microk8s-core-addons/issues/192
Setup PYTHONPATH and PATH so that binaries and libraries from the snap are always prioritized
Fixes the two referenced issues, does not seem to cause regressions elsewhere (commands work ok, no warnings/errors in the logs
Yes, in case we are silently using and depending on binaries outside of the snap, but in this case we want to know about it either way.
=> Prioritize in-snap PYTHONPATH and PATH vars

snap/snapcraft.yaml
=> [Backport 1.27] Prioritize in-snap PYTHONPATH and PATH vars (#4055)

snap/snapcraft.yaml
Backport #4055 to 1.27-strict branch
=> [Backport 1.27-strict] Prioritize in-snap PYTHONPATH and PATH vars (#4055)

build-scripts/components/containerd/patches/0001-microk8s-sideload-images-plugin.patch
containerd can fail in tricky ways with some exports if some foreign-platform manifests are missing from the image export.
This is similar to what we added in https://github.com/canonical/microk8s-cluster-agent/pull/33
```go
// from
images, err := cl.Import(ic.Context, r)
// to
images, err := cl.Import(ic.Context, r, containerd.WithImportPlatform(platforms.Default()))
```
=> Fix containerd image import to match platform images only

build-scripts/components/containerd/patches/0001-microk8s-sideload-images-plugin.patch
=> [Backport 1.27-strict] import images for default platform only (#4074)

scripts/inspect.sh
Suppress some false positives in the inspect hook, using the check from https://github.com/canonical/microk8s/pull/3413
References https://github.com/canonical/microk8s/issues/1691, and probably some more issues
=> Do not warn for cgroups if cgroups v2 is available

tests/templates/dual-stack.yaml, tests/test-cluster.py, tests/utils.py
Add the tests for dual-stack configuration. For the test, we configure a `lxd` container with the required launch configuration. We then deploy a nginx deployment and services and ping on its IPv6 address to verify that IPv6 addresses are also supported.
=> Add test for dual-stack

scripts/wrappers/common/cluster/utils.py
The kubelet cert needs to be created with a reference to the node it is made for. With the CIS hardening work we introduced a bug where during joining of a node  we skip the node reference.
Possibly related https://github.com/canonical/microk8s/issues/4091
Corrected env variable.
Manual
No
=> Bug fix: use extfile in kubelet cert creation

build-scripts/components/cluster-agent/version.sh, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/run-cluster-agent-with-args, scripts/wrappers/common/cluster/utils.py, scripts/wrappers/join.py, snap/hooks/install, snap/snapcraft.yaml, tests/unit/cluster/test_join.py
fixes a number of issues/bugs:
- properly update --secure-port on control plane nodes that join
- always ensure kubelet certificates include subject alternate names for hostname and IP
- remove duplicate python code for certificate generation
- misc cleanup and tidy code
- cleanup OPENSSL_CONF env configuration
Requires https://github.com/canonical/microk8s-cluster-agent/pull/41
=> Rework cluster certificates generation

microk8s-resources/default-args/kube-apiserver
Prefer InternalIP over Hostname for Kubelet connections (e.g. for `kubectl logs`)
Test and review along with https://github.com/canonical/microk8s-cluster-agent/pull/38
=> Prefer InternalIP over Hostname for Kubelet connections

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-k8s-dqlite-with-args, snap/hooks/configure, snap/hooks/remove
Set sane defaults for fs and asyncio parameters.
Does not work in strict, not enough permissions to modify any of these values/files or do `sysctl` calls. 
`system-files` interface might let us create one of these files, although this should be discussed with the snapd team first.
=> Set sane defaults for fs and asyncio parameters

build-scripts/components/kubernetes/pre-patches/0001-Set-log-reapply-handling-to-ignore-unchanged.patch
Fix Kubelet exited with logging configuration was already applied earlier, changing it is not allowed
=> Fix kubelet start error on 1.28.0-rc.0

microk8s-resources/wrappers/git.wrapper, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/microk8s-addons.wrapper, microk8s-resources/wrappers/microk8s-dbctl.wrapper, microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-images.wrapper, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-refresh-certs.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-status.wrapper, microk8s-resources/wrappers/microk8s-version.wrapper
When passing arguments with whitespace/empty values, they are passed incorrectly to the underlying scripts
=> Fix passing of arguments in wrapper scripts

snap/snapcraft.yaml
- Set proper LD_LIBRARY_PATH across the snap
- Fixes missing libceph-common.so on strict
Worth to note, this would help us reduce some of the common boilerplate in places like https://github.com/canonical/microk8s/blob/7dab3b8993d164af058ca1566f2ea94cb2984fd8/microk8s-resources/wrappers/microk8s-addons.wrapper#L9-L17
But we are too close to the 1.28 release to attempt such changes now, so we will defer it for a later time.
=> Configure LD_LIBRARY_PATH on snap environment

microk8s-resources/default-hooks/remove.d/10-cni-link
Calico creates an vxlan-v6.calico interface for IPv6. On remove we need to remove that interface too.
The test-clustering we prepare for dual stack caught that.
=> Remove the IPv6 calico interface when removing the snap

scripts/wrappers/common/cluster/utils.py
Backport for error when cni.yaml was missing.
Related to #4061
=> [1.27] Backport fix for missing cni.yaml for kube-ovn

build-scripts/components/etcd/build.sh, build-scripts/components/flanneld/build.sh, microk8s-resources/wrappers/run-apiserver-proxy-with-args, microk8s-resources/wrappers/run-etcd-with-args, microk8s-resources/wrappers/run-flanneld-with-args, snap/snapcraft.yaml
Follow up from #4096 
- Fix apiserver-proxy broken in FIPS mode (otherwise worker nodes cannot start an apiserver proxy)
- Support etcd and flanneld running in FIPS mode (based on the existing FIPS configuration)
- Fix ignored etcd-env on the etcd service
Assumes https://github.com/canonical/microk8s-cluster-agent/pull/43
=> Fixes and follow-up FIPS-ready patches

build-scripts/components/etcd/build.sh, build-scripts/components/flanneld/build.sh, microk8s-resources/wrappers/run-apiserver-proxy-with-args, microk8s-resources/wrappers/run-etcd-with-args, microk8s-resources/wrappers/run-flanneld-with-args, snap/snapcraft.yaml
Reverts canonical/microk8s#4135
Reverting the FIPS work because it is breaking non-Ubuntu deployments.
=> Revert "Fixes and follow-up FIPS-ready patches"

microk8s-resources/actions/common/utils.sh
Some user actions may trigger the creation of certificates/credentials. In these cases we should be using the bin utils packaged with the snap and not use the ones on the host.
Fixes https://github.com/canonical/microk8s/issues/4133
In our wrappers and in the snapcraft.yaml we set the PATH correctly but when we use sudo (even with the -E flag) to call for example a python script from the wrappers the PATH is not inherited. This behavior depends on the distro and how the admin has setup sudo.  
In utils.sh we use full patch in some calls of binary utils (grep, tr, sed, hostpath).
Manual.
In followup PRs we should try to eliminate all calls from the PATH of bins in utils.sh. There might be other places where we escape snap isolation.
=> Use full path for bins called while joining

microk8s-resources/wrappers/microk8s.wrapper, snap/snapcraft.yaml
#4124 changed how we set LD_LIBRARY_PATH.
However, setting the LD_LIBRARY_PATH on snapcraft.yaml causes issues on non-Ubuntu distros with different libc versions. This PR mitigates the issue by reverting the old change, and then setting the LD_LIBRARY_PATH for the code-path where we needed it.
=> fix broken in LD_LIBRARY_PATH in non-ubuntu

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
Fixes #4142 
Try to symlink /var/lib/calico to /var/snap/microk8s/current/var/lib/calico so that calico mtu autodetection works without issues.
This is required because the `calico` cni plugin is executed from containerd and runs against the filesystem of the host, hardcoding the path to `/var/lib/calico/mtu`: https://github.com/projectcalico/calico/blob/v3.25.1/cni-plugin/pkg/plugin/plugin.go#L198
=> symlink /var/lib/calico

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
=> [Backport 1.27] symlink /var/lib/calico

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
=> [Backport 1.26] symlink /var/lib/calico (#4149)

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
=> [Backport 1.25] symlink /var/lib/calico (#4149)

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
=> [Backport 1.24] symlink /var/lib/calico (#4149)

scripts/wrappers/join.py
Client update necessary for https://github.com/canonical/microk8s-cluster-agent/pull/48 to work
=> Let cluster-agent know we can handle x509 auth on v2/join

snap/snapcraft.yaml
Backport #4149 to 1.27-strict branch
=> [1.27-strict] fix bind mounts for calico and kubelet

snap/snapcraft.yaml
Backport #4149 to 1.26-strict branch
=> [1.26-strict] fix bind mounts for calico and kubelet

scripts/wrappers/join.py
Support custom etcd servers when joining a MicroK8s cluster, requires https://github.com/canonical/microk8s-cluster-agent/pull/45
=> Support custom etcd servers on join

scripts/wrappers/dbctl.py, upgrade-scripts/001-switch-to-dqlite/commit-master.sh
Update call sites of `migrator` tool, now that it's [built into k8s-dqlite](https://github.com/canonical/k8s-dqlite/pull/63)
=> Update migrator invocations

microk8s-resources/default-hooks/reconcile.d/10-pods-restart, scripts/kill-host-pods.py
Minor improvements on https://github.com/canonical/microk8s/pull/4184
- Only restart pods with an owner reference, to protect standalone pods from being deleted and not recreated.
- Also restart pods that mount paths that are symlinks for `$SNAP_DATA` paths
=> Improve handling of necessary system pod restarts on snap refresh

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
Create symlinks for `/etc/cni/net.d` and `/opt/cni/bin` directories (if possible), to ensure compatibility with standard Kubernetes CNI paths.
- For strict this will use bind mounts instead
=> Symlinks for CNI conf and binary directories

scripts/wrappers/join.py
The user currently doesn't get sufficient feedback that the `microk8s join` command was successful.
Adding a short success message at the end IMHO improves the user-experience.
Current output when joining a node (on the joining node):
```
ubuntu@ubuntu:~$ sudo microk8s join 192.168.178.69:25000/615bccdafddbfb07c6645c0d9d813c70/4d874d404e8c
Contacting cluster at 192.168.178.69
Waiting for this node to finish joining the cluster. .. .. ..  
```
Now we get
```
ubuntu@ubuntu:~/microk8s$ sudo microk8s join 192.168.178.69:25000/c7a6eab1455305afbb0ad4edd33413ad/4d874d404e8c
Contacting cluster at 192.168.178.69
Waiting for this node to finish joining the cluster. .. .. .. .  
Successfully joined the cluster.
```
Manually joined two microK8s nodes and verified the output of the joining node.
* [✓] …
=> Print message when node joined successfully

scripts/wrappers/join.py, tests/test-cluster.py, tests/test-upgrade.py
The following fixes are back ported:
- use of x509 certs flag
- skip dual stack tests on arm64
- external etcd endpoints during joining
=> Backport fixes to strict

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/wrappers/run-kubelite-with-args, tests/libs/addons.sh
Introduce a MicroCeph integration test. 
The addons tests will call the respective pytest from the core addos repository. Needs to be merged after: https://github.com/canonical/microk8s-core-addons/pull/242
=> Run microceph integration test

.github/workflows/build-installer.yml, installer/common/definitions.py, installer/vm_providers/_multipass/_windows.py, installer/windows/microk8s.nsi
update homebrew formula to newest microk8s version (1.27) and ubuntu version (22.04)- otherwise Mac Users can't use it.
Closes #4231
References #4231
microk8s version changes from 1.27 --> 1.28
multipass version changes 1.12.0 --> 1.12.2
=> Update microk8s version to 1.28 and multipass 1.12.2

.github/workflows/build-snap.yml
Temporarily use latest/stable snapd to unblock CI
=> temporarily use latest/stable snapd to unblock CI

microk8s-resources/actions/common/utils.sh
If an intermediate CA is used, we cannot verify the whole chain since the CA needs to be self-signed for `openssl verify` to work.
We only want to verify that the server certificate is actually issued by the parent CA (either a root CA or intermediate), thus verifying the partial chain is sufficient.
See also: https://stackoverflow.com/a/60831762
=> Only verify partial CA chain

microk8s-resources/actions/common/utils.sh
This simplifies the address detection a bit for the 'add-node' command hint, enabling a use case where FRR or similar is installing the default route via multiple 'unnumbered' interfaces:
```
From the node you wish to join to this cluster, run the following:
microk8s join none:25000/........
default nhid 151 proto bgp metric 20 
nexthop via inet6 fe80::290:bff:fea5:e2d3 dev bgpenp36s0 weight 1 
nexthop via inet6 fe80::290:bff:fea5:deab dev bgpenp35s0 weight 1 
broadcast 255.255.255.255 dev bgpenp35s0 src 10.0.200.1 uid 0 
cache <local,brd> 
```
Instead of fetching the default route interface and then its address, the suggested change simply finds the system-wide default source address for 255.255.255.255.  In a typical dhcp or static ip scenario, this will be the expected interface; in my …
=> use default broadcast source address for add-node hint

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/openssl.wrapper, scripts/wrappers/join.py, scripts/wrappers/leave.py, scripts/wrappers/refresh_certs.py, snap/snapcraft.yaml
Use a wrapper script for all openssl invocations. This is to reduce the diff with the FIPS-ready branch (https://github.com/canonical/microk8s/compare/fips)
Also cleanup some duplicate configs between `use_snap_env` and `snapcraft.yaml:environment`
=> Use openssl.wrapper script for all openssl invocations

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
Backport https://github.com/canonical/microk8s/pull/4273 to 1.27-strict branch
=> [Backport 1.27-strict] Fix microk8s import images for offline clusters (#4273)

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Backport https://github.com/canonical/microk8s/pull/4265 https://github.com/canonical/microk8s/issues/4253 to 1.28-strict branch
=> [Backport 1.28-strict] CI and tooling fixes to make 1.28-strict branch usable

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/inspect.sh, snap/snapcraft.yaml, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/ubuntu_16.04, tests/lxc/install-deps/ubuntu_20.04
Do a pass over dependencies that are not required for the snap to work. Adjust minor parts of the code accordingly.
- Remove unused `aufs-tools`, `socat`, `squashfs-tools` packages
- Use `ufw` from the host (when available)
- Cleanup `containerd` part (remove unused stage file filters, drop conntrack and libs as they are not required, containerd is now a static binary)
- Drop perl and perl5 scripts (unused, only pulled due to git dependency)
- Drop python wheel files from result snap
- Remove mutiple doc-related files from the snap
As a result of this work, the amd64 snap size is reduced from 180MB to 160mb (about ~12% size reduction)
=> Cleanup unused snap dependencies

scripts/wrappers/distributed_op.py
Backport #4273 to 1.28-strict branch
=> [Backport 1.28-strict] Fix microk8s import images for offline clusters (#4273)

microk8s-resources/actions/common/utils.sh
Backport #4265 to 1.28-strict branch
=> [Backport 1.28-strict] Default to apiserver-proxy port for worker kubeconfigs (#4265)

microk8s-resources/actions/common/utils.sh
=> [Backport 1.28] Default to apiserver-proxy port for worker kubeconfigs (#4265)

snap/snapcraft.yaml
=> Build with Go 1.21

README.md
Adding Badges to snapcraft.io and gh actions builds
Improves the publicity of the snap, and adds these badges to https://releases.juju.is/?team=Kubernetes
Confirmed that the Badges render appropriate icons and reference valid links
No tests are added
=> Add github and snapcraft badges to README.md

scripts/find-resolv-conf.py
References https://github.com/canonical/microk8s/issues/4327
Python 3.8 (from core20) does not support scoped IPv6 addresses. Make sure to handle the case gracefully.
This should be backported to 1.28, 1.27, 1.26 branches after merging
=> Fix find-resolv-conf.py from breaking with scoped IPv6 addresses

installer/vm_providers/_multipass/_multipass_command.py
#Fixes 4320
MacOS fix multipass launch parameter mem deprecated warning
update installer/vm_providers/_multipass/_multipass_command.py file to pass memory instead of mem
verified the multipass deprecated warning no longer appears
=> quickfix multipass launch parameter

scripts/wrappers/join.py
Closes #4345
Needs backport on all supported tracks
`kube-proxy` must be configured to use the same node name as `kubelet`, otherwise services with Local external traffic policy fail to forward traffic (since node name of endpoints does not match the node name of the proxy).
In the past (for non HA), we would set `--hostname-override` flags on both kube-proxy and kubelet services. In recent times, we do not need to do this, and we end in a situation where kubelet is running with its proper hostname, but kube-proxy still tries to find a node with the IP as name (which does not exist).
For more details, see https://github.com/canonical/microk8s/issues/4345#issuecomment-1871073150
- Clear the `--hostname-override` flag on the kube-proxy when joining a cluster. We would only do this if we set …
=> Do not set --hostname-override on kube-proxy when joining a cluster

scripts/wrappers/join.py
=> [Backport 1.27] Do not set --hostname-override on kube-proxy (#4360)

scripts/wrappers/join.py
Backport #4360 to 1.27-strict branch
=> [Backport 1.27-strict] Do not set --hostname-override on kube-proxy (#4360)

snap/snapcraft.yaml
This improves the snapcraft.yaml file by making use of the built-in syntax for installing snap build dependencies, rather than manually installing and refreshing the snaps in `override-build`.
Replaces `snap install` and `snap refresh` with `build-snaps: [ go/1.21/stable ]`, allowing snapcraft to manage the lifecycle of the snap dependencies. 
Built the snap using snapcraft and installed it. The snap builds and runs correctly.
N/A
=> Use build-snaps instead of manually installing the go snap

.github/workflows/build-snap.yml
Pin snapcraft to 7.x for building MicroK8s, required for core18 snaps.
=> [1.25-strict] Use snapcraft 7.x/edge for builds

.github/workflows/build-snap.yml
Pin snapcraft to 7.x for building MicroK8s, required for core18 snaps.
=> [1.26-strict] Use snapcraft 7.x/edge for builds

.github/workflows/build-snap.yml
Pin snapcraft to 7.x for building MicroK8s, required for core18 snaps.
=> [1.25] Use snapcraft 7.x/edge for builds

.github/workflows/build-snap.yml
Pin snapcraft to 7.x for building MicroK8s, required for core18 snaps.
=> [1.26] Use snapcraft 7.x/edge for builds

build-scripts/components/runc/build.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-on-arm64.patch
=> [1.28] Disable static PIE runc builds on arm64

build-scripts/components/runc/build.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-on-arm64.patch
=> [1.27] do not produce static PIE runc executables on arm64

build-scripts/components/containerd/version.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-builds.patch, build-scripts/components/runc/strict-patches/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/components/runc/version.sh
Upgrade containerd to v1.6.28 and runc to v1.1.12
- Update runc patch for strict confinement
- Disable static PIE runc builds, as they are not supported on core18
```
+ make 'BUILDTAGS=seccomp apparmor' 'EXTRA_LDFLAGS=-s -w' static
go build -trimpath -buildmode=pie  -tags "seccomp apparmor netgo osusergo" -ldflags "-X main.gitCommit=v1.1.12-0-g51d5e94 -X main.version=1.1.12 -linkmode external -extldflags --static-pie -s -w" -o runc .
/snap/go/10482/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘--static-pie’; did you mean ‘--static’?
Makefile:69: recipe for target 'static' failed
make: *** [static] Error 1
```
=> [1.26] Bump containerd to v1.6.28 and runc to v1.1.12

build-scripts/components/containerd/version.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-builds.patch, build-scripts/components/runc/strict-patches/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/components/runc/version.sh
Upgrade containerd to v1.6.28 and runc to v1.1.12
- Update runc patch for strict confinement
- Disable static PIE runc builds, as they are not supported on core18
```
+ make 'BUILDTAGS=seccomp apparmor' 'EXTRA_LDFLAGS=-s -w' static
go build -trimpath -buildmode=pie  -tags "seccomp apparmor netgo osusergo" -ldflags "-X main.gitCommit=v1.1.12-0-g51d5e94 -X main.version=1.1.12 -linkmode external -extldflags --static-pie -s -w" -o runc .
/snap/go/10482/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘--static-pie’; did you mean ‘--static’?
Makefile:69: recipe for target 'static' failed
make: *** [static] Error 1
```
=> [1.25] Bump containerd to v1.6.28 and runc to v1.1.12 

build-scripts/components/containerd/version.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-builds.patch, build-scripts/components/runc/strict-patches/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/components/runc/version.sh
Backport #4429 to 1.25-strict branch
=> [1.25-strict] Bump containerd to v1.6.28 and runc to v1.1.12  (#4429)

build-scripts/components/containerd/version.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-builds.patch, build-scripts/components/runc/strict-patches/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/components/runc/version.sh
=> [1.26-strict] Bump containerd to v1.6.28 and runc to v1.1.12 (#4428)

build-scripts/components/runc/build.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-on-arm64.patch
Backport #4427 to 1.27-strict branch
=> [1.27-strict] do not produce static PIE runc executables on arm64 (#4427)

build-scripts/components/runc/build.sh, build-scripts/components/runc/patches/0001-Disable-static-PIE-on-arm64.patch
Backport #4426 to 1.28-strict branch
=> [1.28-strict] do not produce static PIE runc executables on arm64

build-scripts/components/k8s-dqlite/version.sh
Backporting [k8s-dqlite#83](https://github.com/canonical/k8s-dqlite/pull/83)
=> [1.28] Backport k8s-dqlite#83 list query update

build-scripts/components/k8s-dqlite/version.sh
Backporting [k8s-dqlite#83](https://github.com/canonical/k8s-dqlite/pull/83)
=> [1.27-strict] Backport k8s-dqlite#83 list query update

build-scripts/components/k8s-dqlite/version.sh
Backporting [k8s-dqlite#83](https://github.com/canonical/k8s-dqlite/pull/83)
=> [1.28-strict] Backport k8s-dqlite#83 list query update

build-scripts/components/k8s-dqlite/version.sh
Backporting [k8s-dqlite#83](https://github.com/canonical/k8s-dqlite/pull/83)
=> [1.27] Backport k8s-dqlite#83 list query update

.gitignore, scripts/wrappers/add_token.py, scripts/wrappers/common/cluster/utils.py, scripts/wrappers/join.py
Add validation to microk8s join connection string to avoid wrong usage that may lead to propagating errors to microk8s state.
Closes #4396
The validation of the connection string checks:
- The format of the string
- The validity of master IP
- The validity of master PORT
- The lengths of token and fingerprint
=> Fix erroneous microk8s join invocations by adding validation

microk8s-resources/wrappers/run-kubelite-with-args, snap/hooks/remove
Add delegate config if cpuset is missing, possible workaround for #4361
The issue is likely to be upstream dependency update on runc/libcontainers as 1.28 does not suffer from this.
An updated kernel(6.1+, tested with 6.5) also does not seem to suffer from this condition.
=> Add systemd delegate config if cpuset is missing

scripts/wrappers/join.py
When joining control plane nodes, do not fail if the `info.yaml` file of the existing dqlite cluster does not exist
Addresses the following error:
```
Traceback (most recent call last):
File "/snap/microk8s/6738/scripts/wrappers/join.py", line 1015, in <module>
join(prog_name="microk8s join")
File "/snap/microk8s/6738/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/snap/microk8s/6738/usr/lib/python3/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/snap/microk8s/6738/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/snap/microk8s/6738/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs) …
```
=> ignore missing info.yaml file when joining dqlite control plane node

scripts/wrappers/add_token.py, tests/unit/test_addtoken.py
/microk8s/scripts/wrappers/add_token.py
The change was tested with a unittest in tests/unit/test_addtoken.py
Tested using mock print assertion with builtins.print
* [Yes] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [Yes] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [Yes] The introduced changes are covered by unit and/or integration tests.
=> Changed add_token.py for issue #4526 

tests/libs/addons.sh
Running tests on the host and on lxc containers seems to have unforeseen side-effects. For now we disable testing on the host.
Remove the addon tests that run on the host on strict confinement.
Locally and in our CI
The most notable change is the test of micro-ceph
=> Do not run addons tests on the host. Only on lxc containers.

tests/libs/addons.sh, tests/test-distro.sh
Do not test workloads on the host.
Remove the addon tests that run on the host on strict confinement.
Locally and in our CI
The most notable change is the test of micro-ceph
=> Stop running tests on the host -  1.30 strict

.github/workflows/build-snap.yml
The lxc images are missing for the spread tests.
=> Disable testing on debian and centos. Images missing.

build-scripts/components/kubernetes/version.sh
Typo fix in pinning the k8s version in the 1.30 track
=> Fix the KUBE_TRACK version

.github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> [Backport 1.30] Watch query timeout k8s-dqlite backport

build-scripts/components/k8s-dqlite/version.sh
=> [Backport 1.30-strict] Watch query timeout k8s-dqlite backport

.github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> [Backport 1.29] watch query timeout backport k8s-dqlite

build-scripts/components/k8s-dqlite/version.sh
=> [Backport 1.29-strict] Watch query timeout backport k8s-dqlite

build-scripts/components/k8s-dqlite/build.sh, build-scripts/components/k8s-dqlite/version.sh, snap/snapcraft.yaml
=> [Backport 1.28-strict] Watcher query timeout

build-scripts/components/k8s-dqlite/build.sh, build-scripts/components/k8s-dqlite/version.sh, snap/snapcraft.yaml
=> [Backport 1.28] k8s-dqlite watcher query timeout backport

microk8s-resources/wrappers/run-containerd-with-args
The wrong priority in path leads to issues with containerd-shim binary trying to be called from a previous revision that is not installed anymore. Prioritizing $SNAP_CURRENT paths makes sure this path always exists and points to the latest binary.
Fixes #4691
=> Prioritize SNAP_CURRENT in containerd paths

microk8s-resources/wrappers/run-kubelite-with-args
Closes #4462 
By explicitly loading `nf_conntrack` before starting `kubelite`, it should ensure the procfs values that the ProxyServer reads are always present on startup.
* …
=> fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.28-strict] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.29-strict] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.28] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.29] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.29-strict] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.30] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.30-strict] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.31] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.31-strict] fix: ensure nf_conntrack module loaded for kubelite.

microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.28-strict] fix: ensure nf_conntrack module loaded for kubelite.

docs/build.md, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
KU-1196 #4585
This PR updates Calico version from v3.25.1 to v3.28.1
Closes #4585 
Updates Calico version from v3.25.1 to v3.28.1
Tested manually kube-proxy with ` --proxy-mode=ipvs `  flag.
=> Update calico version to v3.28.1

scripts/inspect.sh
Fixes typo in the output of the `ip route` command when running `microk8s inspect`
Inspired by canonical/microk8s/pull/4694
fix in `scripts/inspect.sh`
manual test
no
=> Inspect ip route fix

build-scripts/components/k8s-dqlite/version.sh
This PR updates the k8s-dqlite version from `v1.2.0` to `v1.3.0`.
Release notes: https://github.com/canonical/k8s-dqlite/releases/tag/v1.3.0
=> K8s-dqlite v1.3.0 (Dqlite LTS)

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/remove.d/90-containers, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove, tests/requirements.txt, tests/test-simple.py, tests/test-upgrade.py, tests/utils.py
The containerd shims and the containers are now removed in both classic and strict modes when stopping microk8s (``microk8s stop``) or when removing the snap.
Note that ``ctr container delete`` has no ``--force`` flag.
Adds additional assertion in the upgrade test, ensuring that the Pods / containers have been removed on snap removal.
Adds additional test, ensuring that the Pods / containers have been removed when running ``microk8s stop``.
The Kubernetes-related containers / Pods are now stopped when running ``microk8s stop``. The same containers / Pods are no longer leaked on snap removal.
Added extra assertions and integration test to ensure the new behaviour.
Inspired by: https://github.com/canonical/microk8s/pull/4693
Closes: https://github.com/canonical/microk8s/issues/3969
=> Cleans up containers and shims on microk8s stop and snap removal

microk8s-resources/default-args/kube-apiserver, snap/hooks/configure
Disable WatchList feature gate(enabled by default 1.32+) until k8s-dqlite can properly support it.
=> Disable WatchList feature gate

build-scripts/components/etcd/version.sh, snap/snapcraft.yaml
Bumps go version to 1.23 to accommodate 1.32 release
Bumps etcd patch version to `3.5.17` to build with 1.23
=> Bump go version to 1.23

tests/libs/utils.sh, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04
Follow up on #4755 to add psutil to testing scripts as well
We've received errors on psutil not being available by default
=> Add psutil to pip install directives

.github/workflows/update-images.yml
This PR accomplishes the following:
- replaces @neoaggelos with @berkayoz  as a reviewer.
- adds top-level permissions
- adds 1.31 branches
=> Update Images Workflow Improvement

microk8s-resources/default-hooks/reconcile.d/10-pods-restart
Starting with k8s 1.32, AuthorizeNodeWithSelectors is enabled by default: https://kubernetes.io/docs/reference/access-authn-authz/node/
If the rbac microk8s addon is enabled, the kube-apiserver will run with "--authorization-mode=RBAC,Node". This means that kublets (system:node:$node) will no longer be allowed to access pods that reside on other nodes.
For this reason, the "kill-host-pods.py" script is now getting access denied errors:
```
Error from server (Forbidden): pods is forbidden:
User "system:node:myhostname" cannot list resource "pods" in API group ""
at the cluster scope: can only list/watch pods with spec.nodeName field selector
```
As suggested by the error message, we'll solve it by filtering pods by the node name.
Fixes: https://github.com/canonical/microk8s/issues/4802
=> kill-host-pods.py: filter pods by node

scripts/kill-host-pods.py
This PR fixes the `kill-host-pods.py` script. Currently the `--with-snap-data-mounts` filter does not work correctly as it returns `False` too early.
=> scripts: Fix kill-host-pods script

scripts/kill-host-pods.py
This PR fixes the `kill-host-pods.py` script. Currently the `--with-snap-data-mounts` filter does not work correctly as it returns `False` too early.
=> scripts: Fix kill-host-pods script (#4835)

build-scripts/components/k8s-dqlite/version.sh
This PR bumps the k8s-dqlite version. See the [release notes](https://github.com/canonical/k8s-dqlite/releases/tag/v1.4.0) for further details on the changes.
=> k8s-dqlite v1.4.0

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, .github/workflows/update-images.yml
This PR adds 1.32 to the list of branches who's images are checked for updates by CI.
=> Auto-update images branch 1.32

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.29] memory leak k8s-dqlite v1.1.12 (#4869)

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.29-strict] memory leak k8s-dqlite v1.1.12

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.30-strict] memory leak k8s-dqlite v1.1.12 (#4869)

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
* bug: [backport v1.2] memory leak fix k8s-dqlite PR: https://github.com/canonical/k8s-dqlite/pull/240
* CI: bump artifact in gh actions
* CI: Trivy job fix
=> Backport: [1.31-strict] memory leak fix k8s-dqlite v1.2.1 (#4866)

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.32-strict] memory leak k8s-dqlite v1.3.1

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
Bump strict from v1.3.0 -> v1.4.1 to align with master branch version and include memory leak fix: https://github.com/canonical/k8s-dqlite/pull/240.
=> bug: [strict] fix memory leak k8s-dqlite v1.4.1 (#4868)

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.28] memory leak k8s-dqlite v1.1.12 (#4869)

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
=> backport: [1.28-strict] memory leak k8s-dqlite v1.1.12

.github/workflows/backport.yml
Currently, the backports are being made by the ``github-actions`` user, which means that other workflows are not triggered by it, including CI tests, which we want to run.
Running as a different user will address this issue.
NOTE: the secret ``BOT_TOKEN`` **must** exist.
=> actions: Run backport action with a different account

scripts/wrappers/reset.py
This MR adds some common non-namespaced APIs to be removed when doing a `microk8s reset`. I also refactored the code a bit to be more consistent and fixed the help message for destroy storage.
Closes #4747
References #3243 #4297
I added the removal of CRDs to a function and created a function for the rest of the non-namespaced APIs.
I ran the following steps:
1. Setup microk8s cluster.
2. Install ingress-nginx-controller as described [here](https://kubernetes.github.io/ingress-nginx/deploy/#quick-start).
```bash
helm upgrade --install ingress-nginx ingress-nginx \
--repo https://kubernetes.github.io/ingress-nginx \
--namespace ingress-nginx --create-namespace
```
3. Run microk8s reset.
4. Everything was removed.
=> Cleanup common non-namespaced resources (Closes #4747)

tests/test-cluster.py
We would like to switch to use Ubuntu 20.04 in our tests. This PR fixes some tests that had the ubuntu distro hard coded.
=> CI: Distro from env variable in test - 1.30

tests/test-cluster.py
We would like to switch to use Ubuntu 20.04 in our tests. This PR fixes some tests that had the ubuntu distro hard coded.
Tested in https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/536/parameters/
=> CI: Distro from env variable in test - 1.31

tests/test-cluster.py
We would like to switch to use Ubuntu 20.04 in our tests. This PR fixes some tests that had the ubuntu distro hard coded.
Tested in https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/535/console
=> CI: Distro from env variable in test

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04
Passed Jenkins release CI: https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/553/console
Currently, the "Test core addons" job fails because the test_cis test fails, having 2 more warnings than expected.
Those warnings are from ``microk8s kube-burner``, which has the following new warnings (the checks were passing before):
```
[WARN] 2.3 Ensure that the --auto-tls argument is not set to true (Automated)
[WARN] 2.6 Ensure that the --peer-auto-tls argument is not set to true (Automated)
``
Those warnings appear because the commands used for checking them fail:
```
2.3 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1 2.6 audit test did not run: failed to run: "/bin/ps -ef | …
=> [Backport 1.32] CI: Pins pytest to 8.3.4 for Test core addons (#4923)

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py
We would like to switch to use Ubuntu 20.04 in our tests. This PR fixes some tests that had the ubuntu distro hard coded.
CI: Pins pytest to 8.3.4 for Test core addons
Currently, the "Test core addons" job fails because the ``test_cis`` test fails, having 2 more warnings than expected.
Those warnings are from ``microk8s kube-burner``, which has the following new warnings (the checks were passing before):
```
[WARN] 2.3 Ensure that the --auto-tls argument is not set to true (Automated)
[WARN] 2.6 Ensure that the --peer-auto-tls argument is not set to true (Automated)
```
Those warnings appear because the commands used for checking them fail:
```
2.3 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1
2.6 audit …
```
=> [Backport 1.32-strict] CI: Distro from env variable in test, pin pytest (#4910) (#4923) 

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04
Test run: https://jenkins.canonical.com/k8s-ps5/view/Microk8s/job/release-microk8s-arch-arm64/485/
Currently, the "Test core addons" job fails because the test_cis test fails, having 2 more warnings than expected.
Those warnings are from ``microk8s kube-burner``, which has the following new warnings (the checks were passing before):
```
[WARN] 2.3 Ensure that the --auto-tls argument is not set to true (Automated)
[WARN] 2.6 Ensure that the --peer-auto-tls argument is not set to true (Automated)
``
Those warnings appear because the commands used for checking them fail:
```
2.3 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1 2.6 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | …
=> [Backport 1.31] CI: Pins pytest to 8.3.4 for Test core addons (#4923)

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04
Currently, the "Test core addons" job fails because the test_cis test fails, having 2 more warnings than expected.
Those warnings are from ``microk8s kube-burner``, which has the following new warnings (the checks were passing before):
```
[WARN] 2.3 Ensure that the --auto-tls argument is not set to true (Automated)
[WARN] 2.6 Ensure that the --peer-auto-tls argument is not set to true (Automated)
``
Those warnings appear because the commands used for checking them fail:
```
2.3 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1 2.6 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1
```
Those errors would suggest that there is no …
```
=> [Backport 1.30] CI: Pins pytest to 8.3.4 for Test core addons (#4923)

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py
This PR fixes the addons-CI by changing the distro in the test and pinning pytest. For further info please refer to the back-ported PRs.
=> [Backport 1.30-strict] CI: Distro from env variable in test 1.31-strict, pin pytest (#4912) (#4923)

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py
This PR fixes the addons-CI by changing the distro in the test and pinning pytest. For further info please refer to the back-ported PRs.
=> [Backport 1.28-strict] CI: Fix addons CI (#4913)(#4923)

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py
This PR fixes the addons-CI by changing the distro in the test and pinning pytest. For further info please refer to the back-ported PRs.
=> [Backport 1.29-strict] CI: Fix addons CI (#4913)(#4923) 

.github/workflows/build-snap.yml, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_archlinux, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-cluster.py
This PR fixes the addons-CI by changing the distro in the test and pinning pytest. For further info please refer to the back-ported PRs.
=> [Backport 1.29] CI: Fix addons CI (#4913) (#4923) (#4606)

snap/snapcraft.yaml
The config.guess script in libmnl-1.0.4 is too old to recognize the riscv64 architecture.
Besides the build system the differences between both version are mostly cosmetic, like adding a const qualifier to a  function parameter.
=> snapcraft.yaml: upgrade to libmnl-1.0.5

microk8s-resources/actions/common/utils.sh
=> fix: flush the `CNI-HOSTPORT-DNAT` chain on stop

microk8s-resources/actions/common/utils.sh
=> [Backport 1.32] fix: flush the `CNI-HOSTPORT-DNAT` chain on stop (#4963)

microk8s-resources/actions/common/utils.sh
=> [Backport 1.32-strict] fix: flush the `CNI-HOSTPORT-DNAT` chain on stop (#4963)

microk8s-resources/actions/common/utils.sh
=> [Backport 1.31] fix: flush the `CNI-HOSTPORT-DNAT` chain on stop (#4963)

microk8s-resources/actions/common/utils.sh
=> [Backport 1.31-strict] fix: flush the `CNI-HOSTPORT-DNAT` chain on stop (#4963)

microk8s-resources/actions/common/utils.sh
=> [Backport 1.30] fix: flush the `CNI-HOSTPORT-DNAT` chain on stop (#4963)

tests/lxc/install-deps/ubuntu_20.04
Jenkins run: [603](https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/603/console)
=> fix: Microk8s release CI by pre-install xdelta3

tests/libs/utils.sh, tests/lxc/install-deps/ubuntu_20.04
Backport of https://github.com/canonical/microk8s/pull/4975.
The microk8s release test was configuring the proxy for the distro test even when no PROXY argument was passed and consequently failing. This PR uses the 1.29 utils.sh script changes from https://github.com/canonical/microk8s/pull/4211/files#diff-ab9576bfebf72148bf033576bf8375386e2ca3724ce06bba9076280358ed5d90.
Release job success: [598](https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/598/console)
Without `xdelta3` we get a failure: [599](https://jenkins.canonical.com/k8s-ps5/job/release-microk8s-arch-amd64/node=runner-cloud/599/console), `error: cannot communicate with server: Post "http://localhost/v2/snaps/microk8s": read unix @->/run/snapd.socket: read: connection reset by peer`
=> backport: [1.28] Check for PROXY in distro test, bump to core20, pre-install xdelta3

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.29-strict] Microk8s release CI by pre-install xdelta3

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.29] Microk8s release CI by pre-install xdelta3 

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.31-strict]Microk8s release CI by pre-install xdelta3

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.30] Microk8s release CI by pre-install xdelta3

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.30-strict] Microk8s release CI by pre-install xdelta3

.github/workflows/build-snap.yml, tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.32-strict] Microk8s release CI by pre-install xdelta3

tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.31] Microk8s release CI by pre-install xdelta3

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, tests/lxc/install-deps/ubuntu_20.04
=> backport: [1.32]  Microk8s release CI by pre-install xdelta3

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py
* GH actions no longer support 20.04 runners, so we'll switch to 22.04
* need to apply the well known iptables workaround to address the compatibility issue between LXD and Docker
* we're adding the run-all-tests label which controls the UNDER_TIME_PRESSURE env variable
* to avoid duplicate logic, we'll add a composite action that takes care of the test prerequisites, making them easier to maintain.
* we'll avoid installing python packages globally (no longer allowed by recent Python versions). Instead, we'll use actions/setup-python, which will also cache the packages.
* define job timeouts
=> ci: unblock the CI and add a few improvements

tests/libs/clustering.sh
Fix clustering test flake by increasing the timeout and adding retries.
=> CI: [1.28] fix clustering flake

.github/workflows/build-snap.yml, snap/hooks/configure, tests/utils.py, tests/validators.py
At the moment, the default hooks are not updated when refreshing
the snap[1].
There's an explicit check so this was most probably by design so that
custom hooks would not get overridden[2]. However, it means that bug
fixes are not applied automatically and the users need to copy the
files manually, which is undocumented and not very user friendly.
**Warning:**
This change will always refresh the default hooks, replacing
the existing files. Custom hooks are expected to use separate files
so that they won't get overridden during upgrades.
[1] https://github.com/canonical/microk8s/pull/4819
[2] https://github.com/canonical/microk8s/pull/4819#issuecomment-2676378060
=> fix: Always refresh the default hooks during upgrades

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt
The CIS tests are currently failing if we remove some Python
dependency constraints.
The reason is that these tests run a few "ps" commands and receive
truncated output[1].
As a workaround, we'll explicitly set the terminal size using
the COLUMNS env variable.
[1] https://github.com/canonical/microk8s-core-addons/blob/f2716f1d4c0e169762f0bff37d7496f7ac33db62/addons/cis-hardening/cfg/cis-1.24-microk8s/etcd.yaml#L13
=> CI: fix CIS test failures caused by truncated ps output

build-scripts/components/k8s-dqlite/version.sh
This PR drops the k8s-dqlite tag down to v1.3.1 as we wait on the Dqlite release for v1.6.0 https://github.com/canonical/microk8s/pull/5004.
The missing event bug is resolved on 1.6.0 but not on v1.4.1. We decided to stay on the stable tag until we get the Dqlite release.
Drop the k8s-dqlite version.
CI testing.
NA
NA
=> Fix: downgrade k8s-dqlite version v1.3.1

microk8s-resources/actions/common/utils.sh
Runs `iptables` with sudo and suppress the output.
=> fix: run iptables as sudo on microk8s stop

.github/workflows/build-snap.yml
Adds `export UNDER_TIME_PRESSURE=${UNDER_TIME_PRESSURE@u}` to maintain compatibility with tests in addons repositories which expects a camel case value, e.g. `True`.
=> fix: camel case UNDER_TIME_PRESSURE value

.github/workflows/build-snap.yml
Backports https://github.com/canonical/microk8s/pull/5043
=> [1.32-strict] fix: camel case UNDER_TIME_PRESSURE value

.github/workflows/build-snap.yml
Addresses [this deprecation](https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/) regarding security scanning CI
=> fix: upload sarif files sequentially with category set to their basename

.github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
This PR updates the k8s-dqlite tag due to a new patch, see https://github.com/canonical/k8s-dqlite/releases/tag/v1.3.3.
I also cherry-picked Reza's fix for Sarif in CI.
=> fix: use v1.3.3 k8s-dqlite patch release 1.32-strict, fix sarif CI

tests/validators.py
We updated the dashboard addon so it is in its own namespace. The upgrade tests should take this into account.
=> Update the dashboard validator so it passes in both old and new versions

build-scripts/components/cni/version.sh, build-scripts/components/containerd/version.sh, build-scripts/components/etcd/build.sh, build-scripts/components/etcd/version.sh, build-scripts/components/flannel-cni-plugin/version.sh, build-scripts/components/flanneld/version.sh, build-scripts/components/helm/version.sh, build-scripts/components/k8s-dqlite/version.sh, build-scripts/components/microk8s-completion/patches/default/0001-microk8s-autocompleter-script.patch, build-scripts/components/microk8s-completion/version.sh, build-scripts/components/runc/version.sh
This PR bumps component versions to the latest at the moment as a preparation for the 1.34 release.
The latest version for `containerd` is 2.1.4, which is a major version bump compared to the current version being used in Microk8s. I deliberately did not bump to that version, instead went for the latest 1.X.X version (same major version).
=> chore: Bump component versions to latest

build-scripts/components/kubernetes/patches/v1.34.0/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/version.sh, microk8s-resources/default-args/kube-apiserver, snap/hooks/configure
Updates for building 1.34
* updated k8s patches
* configure the API server with proper feature gates
=> Prepare for the 1.34 release

.github/workflows/build-snap.yml, microk8s-resources/containerd-profile
Add explicit AppArmor rules to permit common socket types (inet, inet6, unix) needed by Kubernetes workloads (e.g., kube-controller, coredns). Plucky ships AppArmor 4.1.0, which is stricter and requires exact socket types to be set. This resolves "apparmor=DENIED operation=create class=net" denials.
Fixes #5082
Fixes #5190
Fixes #5140
=> fix(apparmor): allow sockets in cri-containerd profile (Backport #5218)
