snapcraft.yaml
This cleanup is required to get through the snap manual review. See https://forum.snapcraft.io/t/classic-confinement-for-microk8s-snap/5242/5
=> Remove all plugs

microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper
```
microk8s.enable dns dashboard
microk8s.disable dns dashboard
```
=> Makes it so you can use multiple parameters to microk8s.enable and disable

microk8s-resources/default-args/etcd
=> Move etcd to SNAP_COMMON

microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/enable.storage.sh, microk8s-resources/actions/storage.yaml, microk8s-resources/default-args/kube-apiserver
We add a default storage classed implemented as NFS on a hostpath under SNAP_COMMON.
Enabling/disabling is done through respective actions.
=> Add action for default storage class

microk8s-resources/default-args/kubelet
=> Lower eviction limits for kubelet

microk8s-resources/wrappers/run-etcd-with-args, snapcraft.yaml
Should fix: https://github.com/juju-solutions/microk8s/issues/44
=> Remove the etcd socket file when etcd restart

.gitignore, README.md, microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/storage.yaml, tests/templates/pvc.yaml, tests/test-addons.py, tests/validators.py
nfs-proviosner needs nfs-coomon which is rather hard to put in a snap package. Instead we moved to hostpath-provioner. In this PR we also improve tests on storage.
Should fix: https://github.com/juju-solutions/microk8s/issues/47
=> Replace nfs-provisioner with hostpath-provisioner

README.md
Fixes #56
We may want to change it back once `microk8s.config` is in beta / stable.
=> Update README to not recommend microk8s.config by default

README.md
Based on https://github.com/kubernetes/kubeadm/issues/338 and
https://github.com/kubernetes/kubernetes/issues/34043 there is no easy way to update the IP of the master. Lets propose a microk8s restart for now.
=> Document microk8s restart when master IP changes

README.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.dns.sh, microk8s-resources/actions/disable.gpu.sh, microk8s-resources/actions/enable.dns.sh, microk8s-resources/actions/enable.gpu.sh, microk8s-resources/actions/gpu.yaml, microk8s-resources/default-args/dockerd, microk8s-resources/default-args/kubelet, microk8s-resources/wrappers/run-docker-with-args, snapcraft.yaml, tests/templates/cuda-add.yaml, tests/test-addons.py, tests/test-upgrade.py, tests/validators.py
Do `microk8s.enable gpu` on a host with NVIDIA loaded.
The nvidia docker container will be enabled and the nvidia daemon set will come up.
=> Add GPU addon

microk8s-resources/wrappers/microk8s-enable.wrapper
Fixes https://github.com/ubuntu/microk8s/issues/89
=> Limit search in microk8s.enable --help

README.md, build-scripts/prepare-env.sh
Fixes https://github.com/ubuntu/microk8s/issues/85
=> Upgrade CNI to v0.7.1 due to reported ipv6 problems

microk8s-resources/default-args/kubelet
=> Add missing --docker kubelet arg

.travis.yml
=> Use stable docker image for building in travis

snapcraft.yaml
Fixes https://github.com/ubuntu/microk8s/issues/98
=> Package zfs utilities

README.md, scripts/inspect.sh, snapcraft.yaml
First pass in introspection script.
Fixes: https://github.com/ubuntu/microk8s/issues/37
=> Adding the inspect command

build-scripts/prepare-env.sh
This is part of the branch creation automation we need to have. A card is already created.
=> Have 1.11 branch to build from 1.11 k8s

tests/test-upgrade.py
systemd-detect-virt  will not detect it is running in a travis container: https://travis-ci.org/ubuntu/microk8s/builds/437530500?utm_source=github_status&utm_medium=notification
=> Better container detection (mainly for travis)

microk8s-resources/default-args/kube-apiserver
Fixes: https://github.com/ubuntu/microk8s/issues/141
=> Use the default log level for the api-server

microk8s-resources/wrappers/microk8s-config.wrapper, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/148
=> Package net-tools in the snap

tests/lxc/install-deps/ubuntu:16.04, tests/lxc/install-deps/ubuntu:18.04, tests/test-distro.sh, tests/utils.py
This changes are needed for pip install not to fail in our CI.
We make sure pip uses the proxy passed.
=>  Add proxy setting for pip fix

tests/lxc/install-deps/ubuntu:16.04, tests/lxc/install-deps/ubuntu:18.04, tests/test-distro.sh, tests/utils.py
Fix for our CI failing on pip install
=> Increase kubectl timeout - pass proxy to pip

README.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-istioctl.wrapper, microk8s-resources/wrappers/microk8s-kubectl.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, microk8s-resources/wrappers/run-with-config-args, snap/hooks/configure, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/162
=> Add start stop commands

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-config.wrapper, microk8s-resources/wrappers/run-with-config-args, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/118
=> Apiserver kicker tracking IP changes

README.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-status.wrapper, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/155 https://github.com/ubuntu/microk8s/issues/115 https://github.com/ubuntu/microk8s/issues/174
=> Add status command

microk8s-resources/default-args/kubelet
Fixes: https://github.com/ubuntu/microk8s/issues/176
=> Eviction if memory is less than 100MB

README.md, docs/dockerd.md, docs/registry.md, docs/release-channels.md
Fixes: https://github.com/ubuntu/microk8s/issues/201
=> Update README with MicroK8s

.gitignore, tests/test-live-addons.py, tests/test-upgrade.py, tests/utils.py, tests/validators.py
Help my ide resolve the local imports, and some style fixes
=> Mark local imports

.idea/microk8s.iml, .idea/modules.xml, .idea/vcs.xml, .idea/workspace.xml, tests/templates/bbox.yaml, tests/test-addons.py, tests/test-live-addons.py, tests/test-upgrade.py, tests/validators.py
Move dns test along with dashboard testing becasue we are running short on time on travis.
Fix dns testing
=> Better dns testing

snapcraft.yaml
=> Update nvidia runtime to match dockerd upgrade

README.md
Having spent a day trying out microk8s this is a solution for dev / demo environments. However, I lost a couple of hours to debugging a bad networking rule.
When I followed the instructions to raise an issue I discovered that inspect command showed me the issue with my networking configuration.
This PR is intended to add information about using the inspect command to troubleshoot networking issues.
=> Improve debug docs for network issues

README.md
Fixes: https://github.com/ubuntu/microk8s/issues/221
=> Document changing the upstream dns servers

microk8s-resources/wrappers/microk8s-docker.wrapper
Add flag in sudo to preserve user environment when running docker command
Fixes #272
=> Pass user environment to underlying docker client

microk8s-resources/actions/disable.ingress.sh, microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml, snapcraft.yaml, tests/test-addons.py, tests/test-upgrade.py, tests/validators.py
Fixes: https://github.com/ubuntu/microk8s/issues/301
=> Fix ingress on arm64

microk8s-resources/actions/fluentd/fluentd-es-ds.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/310
=> Correct the fluentd paths

microk8s-resources/default-args/kubelet
Fixes https://github.com/ubuntu/microk8s/issues/308
The label added is: `microk8s.io/cluster=true`
=> Adding microk8s label to node

snap/hooks/install, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/373
=> Get openssl from the host

.travis.yml, tests/test-addons.py
Make 1.12 tests run faster on CI
=> Consolidate tests to have them go through our CI

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-with-config-args, snap/hooks/configure, snap/hooks/install, snapcraft.yaml
Fixes https://github.com/ubuntu/microk8s/issues/415
=> Put all IPs in the certificate

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-with-config-args, snap/hooks/configure, snap/hooks/install
=> Include all host IPs in server cert

microk8s-resources/wrappers/run-containerd-with-args
Fixes: https://github.com/ubuntu/microk8s/issues/423
=> Have containerd wait for default route

microk8s-resources/actions/ingress.yaml
According to https://kubernetes.github.io/ingress-nginx/deploy/rbac/
=> Add RBAC for NGINX Ingress Controller

microk8s-resources/actions/registry.yaml
Allow deleting images from the private repository. See discussion in:
https://github.com/ubuntu/microk8s/issues/382#issuecomment-488229576
=> Enable deleting in the registry

microk8s-resources/wrappers/apiservice-kicker
This PR fixes https://github.com/ubuntu/microk8s/issues/451
=> Restart kubelet after ip change

microk8s-resources/actions/enable.ingress.sh
Fixes https://github.com/ubuntu/microk8s/issues/485
=> Upgrade nginx ingress to 0.24.1

microk8s-resources/actions/enable.knative.sh, tests/test-addons.py
Fix bug in knative enable script. Consolidate istio and knative tests.
=> Fixes on knative addon enable and tests

microk8s-resources/wrappers/run-with-config-args
Fixes: https://github.com/ubuntu/microk8s/issues/519
=> Handle non-unified cgroups

microk8s-resources/actions/storage.yaml
Add a ServiceAccount and ClusterRole to enable the hostpath addon to work with RBAC enabled.
This fixes #516.
=> Setup RBAC for hostpath

snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/525
=> Add missing archlinux libs

microk8s-resources/containerd-profile
Fixes: https://github.com/ubuntu/microk8s/issues/530
Fixes: https://github.com/ubuntu/microk8s/issues/538
=> Fix typo in apparmor profile

microk8s-resources/actions/coredns.yaml, microk8s-resources/actions/enable.dns.sh
This is a fix only for xenial, other distribution may be affected. We will have to add them here are they come.
Fixes: https://github.com/ubuntu/microk8s/issues/533
=> Fix privilege escalation of coredns on xenial

docs/community.md
Add links for medium stories, in which we execute a simple flask application as a microk8s service.
=> Adds link to medium story (flask + microk8s)

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kube-apiserver, microk8s-resources/wrappers/apiservice-kicker, snap/hooks/configure, snap/hooks/install
Fixes #560
Links:
- https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-kubernetes-apiserver-flags
=> Enable the aggregation layer

scripts/inspect.sh
Stores memory, disk, distribution, uptime, vm information. Checks for… SELinux and docker installation and prints warnings. Stores kubernetes info about pv and pvc.
=> Update Inspection Script

microk8s-resources/wrappers/run-with-config-args, snap/hooks/remove
This is best described in: https://www.altoros.com/blog/kubernetes-networking-writing-your-own-simple-cni-plug-in-with-bash/
=> Configure iptable forwarding policy for pods

microk8s-resources/actions/common/utils.sh, snap/hooks/configure, snap/hooks/install
This is a backport of the work in https://github.com/ubuntu/microk8s/pull/608
=> Allow users to be in the microk8s group - 1.14 changes

snapcraft.yaml
Should fix https://github.com/ubuntu/microk8s/issues/612
=> Patching the curl binary to use in snap libs

microk8s-resources/wrappers/microk8s-reset.wrapper, snap/hooks/remove, tests/test-addons.py
This got broken accidentally as mentioned here https://github.com/ubuntu/microk8s/commit/8173dce3189d376bd0267b9f2d62ef11193d5ada#r34854580
=> Fix the reset wrapper - do a proper reset

microk8s-resources/default-args/kube-apiserver
Closing insecure port, for real!
=> Close port 8080 on apiserver

microk8s-resources/actions/dashboard.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/666
=> Upgrading the dashboard for 1.16

scripts/inspect.sh
Skip firewall check if ufw not present.
Fixes: https://github.com/ubuntu/microk8s/issues/631
=> In inspect skip ufw check if binary not present

snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/669
=> Add openssl in the snap

microk8s-resources/wrappers/microk8s-status.wrapper
Sorts addons on status. Fixes: https://github.com/ubuntu/microk8s/issues/687
=> Sort addons in status

README.md
Remove the dangling double quotes from this command line: sudo usermod -a -G microk8s <username>" .
=> Remove dangling double quotes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/cluster/join.py
Fixes: https://github.com/ubuntu/microk8s/issues/669
=> Set LD_LIBRARY_PATH before calling python3

microk8s-resources/actions/enable.dashboard.sh
Fixes: https://github.com/ubuntu/microk8s/issues/708
=> Updating link to user creation doc

microk8s-resources/actions/disable.jaeger.sh, microk8s-resources/actions/enable.jaeger.sh, microk8s-resources/actions/jaeger/crds/jaegertracing_v1_jaeger_crd.yaml, microk8s-resources/actions/jaeger/operator.yaml, microk8s-resources/actions/jaeger/role.yaml, microk8s-resources/actions/jaeger/role_binding.yaml, microk8s-resources/actions/jaeger/service_account.yaml, microk8s-resources/actions/jaeger/simplest.yaml, microk8s-resources/wrappers/microk8s-disable.wrapper
The previous files used for enabling jaeger were outdated and started
failing like in issue #698. The files have now been updated and
should fix those issues.
=> Update Jaeger installation files

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/microk8s-cilium.wrapper, microk8s-resources/wrappers/microk8s-ctr.wrapper, microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-helm.wrapper, microk8s-resources/wrappers/microk8s-istioctl.wrapper, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-linkerd.wrapper, microk8s-resources/wrappers/microk8s-remove-node.wrapper, microk8s-resources/wrappers/microk8s-status.wrapper, microk8s-resources/wrappers/run-cluster-agent-with-args, microk8s-resources/wrappers/run-containerd-with-args, microk8s-resources/wrappers/run-etcd-with-args, microk8s-resources/wrappers/run-flanneld-with-args, microk8s-resources/wrappers/run-with-config-args, snap/hooks/install
Fixes: https://github.com/ubuntu/microk8s/issues/720
=> Use the right path for libs

microk8s-resources/actions/enable.helm.sh
Addresses issue# https://github.com/ubuntu/microk8s/issues/695
=> Upgrade helm to v2.15.0

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kube-apiserver, snap/hooks/configure
See https://github.com/ubuntu/microk8s/issues/721
=> Separate apiserver and front proxy CAs

scripts/cluster/distributed_op.py
`addons` state can only be one of "enable" or "disable" and thus it should handle for any other value.
=> Added exception handling in setting addons state.

microk8s-resources/actions/common/utils.sh
Fixes https://github.com/ubuntu/microk8s/issues/741
I have taken your second suggestion of not reacting to cni0 changes. What do you think? Could you give it a test drive to see if it works for you? Thanks.
=> Do not reconfigure apiserver certs on changes of cni0

microk8s-resources/actions/dashboard.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/730
=> Updating dashboard to work in v1.16 (arm64 fix)

microk8s-resources/actions/enable.helm.sh
Upgrading helm due to 2.15.1 regression on 1.16 branch
=> Upgrading helm to 2.15.1

microk8s-resources/wrappers/run-with-config-args, scripts/inspect.sh, snap/hooks/remove, snapcraft.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/766
=> Handle iptable forward rules

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.cilium.sh, microk8s-resources/actions/disable.gpu.sh, microk8s-resources/actions/disable.istio.sh, microk8s-resources/actions/disable.linkerd.sh, microk8s-resources/actions/disable.rbac.sh, microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/enable.cilium.sh, microk8s-resources/actions/enable.helm.sh, microk8s-resources/actions/enable.istio.sh, microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/actions/enable.rbac.sh, microk8s-resources/wrappers/microk8s-ctr.wrapper, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/configure
Fixes: https://github.com/ubuntu/microk8s/issues/769, fixes: https://github.com/ubuntu/microk8s/issues/671
Make sure when we call the host's sudo we do not use libs from the snap.
=> Use the right libs when calling the hosts sudo.

microk8s-resources/wrappers/microk8s-status.wrapper
Fixes: https://github.com/ubuntu/microk8s/issues/777
=> Status to report kubeflow and juju addons

microk8s-resources/actions/enable.juju.sh, microk8s-resources/wrappers/microk8s-juju.wrapper, snap/hooks/configure, snapcraft.yaml
Fixes https://github.com/ubuntu/microk8s/issues/792
=> Get juju not to need sudo

microk8s-resources/actions/enable.kubeflow.sh
Requires an HTTPS connection, which means we have to use an ingress instead of just connecting to the pod itself.
=> Add support for kubeflow 0.6 dashboard

tests/test-addons.py
@knkski I am disabling the kf test so we can push this to beta/candidate without stressing you
=> Disable kf testing

scripts/cluster/agent.py, scripts/cluster/join.py
Fixes https://github.com/ubuntu/microk8s/issues/800
=> Handle proxy override for kubeproxy

scripts/cluster/agent.py, scripts/cluster/join.py
* Handle proxy override for kubeproxy
* Set_args to also add argument
=> Handle proxy override for kubeproxy (#807)

microk8s-resources/actions/disable.metallb.sh, microk8s-resources/actions/enable.metallb.sh, microk8s-resources/actions/metallb.yaml
This patch is to add support for MetalLB. So you can install it by:
`microk8s.enable metallb`
=> <feat>Add support for microk8s.enable metallb

microk8s-resources/actions/enable.kubeflow.sh
A one-size-fits-all timeout won't work for everyone, so just remove it. Also print out login username/password on successful enablement.
Fixes #817
=> Remove timeout when enabling Kubeflow

snapcraft.yaml
Add a slot using `content` interface to notify Juju to pre-fetch Juju related images when `microk8s` is installed;
=> Add content interface slot for Juju to plug to;

scripts/cluster/agent.py
Have nodes register correctly so they are not affected by RBAC
Fixes: https://github.com/ubuntu/microk8s/issues/814
=> Correct the group and username of nodes

microk8s-resources/actions/enable.kubeflow.sh
When deploying behind a restrictive proxy, this allows one to specify internal addresses that should not be proxied.
Fixes #753
=> Add no proxy option for enabling Kubeflow

scripts/inspect.sh
Should allow us to get a better view on the user firewall.
=> Get iptable chain rules when inspecting

microk8s-resources/actions/enable.juju.sh
Also allow overriding the version used with an environment variable.
=> Switch to stable Juju 2.7 by default for addon

microk8s-resources/actions/coredns.yaml
keeping cluster components fresh.  upgrading to coredns 1.6.6.
=> upgrade coredns to 1.6.6

microk8s-resources/actions/disable.juju.sh, microk8s-resources/actions/disable.kubeflow.sh, microk8s-resources/actions/enable.juju.sh, microk8s-resources/actions/enable.kubeflow.sh
Otherwise, if someone attempts to change the Juju version, they'll be stuck with the old version unexpectedly.
=> Add Juju disable script

snap/hooks/configure
Does not restart the apiserver upon configure.
=> Do not restart the apiserver on configure

.travis.yml, build-scripts/fetch-other-binaries.sh, build-scripts/set-env-variables.sh, docs/build.md, installer/requirements.txt, microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.registry.sh, microk8s-resources/actions/disable.storage.sh, microk8s-resources/actions/enable.cilium.sh, microk8s-resources/default-args/etcd, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/run-flanneld-with-args, snap/hooks/configure, tests/test-addons.py
Just had to pin setuptools version for MacOS builds.  Need to check this doesn't subsequently break Windows builds before releasing the PR.
=> MacOS builds for MicroK8s

appveyor.yml
Get MacOS artifacts from AppVeyor.
=> Add MacOS builds to appveyor

installer/cli/microk8s.py, installer/common/definitions.py
This is make testing easier for us and scripted installs easier for everyone else.  Tested in all expected conditions.
=> Add `--assume-yes` flag to `micok8s install`

microk8s-resources/actions/enable.kubeflow.sh
Allows setting a hostname during `microk8s.enable kubeflow`, in case a user wants something other than localhost, and also manually creates an Ingress vs using `juju expose`, due to issue with cluster restart (issue mentioned in #817).
=> Fix Kubeflow ingress issues

installer/cli/microk8s.py, installer/microk8s.spec
Put the `-y` flag on `--assume-yes` and refect this in the docstring.
Format pyinstaller spec file and add hidden import to fix https://github.com/pypa/setuptools/issues/1963
=> Add `--assume-yes` to doc and fix PyInstaller issue on Linux

microk8s-resources/wrappers/microk8s-enable.wrapper
Don't re-enable addons if already enabled
=> Don't re-enable addons if already enabled

microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/run-cluster-agent-with-args
Fixes https://github.com/ubuntu/microk8s/issues/978
=> Load openssl conf from the right localtion

microk8s-resources/actions/storage.yaml
=> Add required RBAC rules for storage

.travis.yml, scripts/cluster/agent.py, scripts/cluster/distributed_op.py, scripts/cluster/join.py
Python in xenial (core16) is on 3.5.
=> Variable annotation syntax is only supported in Python 3.6+

microk8s-resources/actions/enable.kubeflow.sh
Needs to be merged after the bundle is moved to stable.
Also blocked on https://github.com/juju-solutions/bundle-kubeflow/pull/180
=> Update kubeflow addon deployment for upstream's 1.0

installer/setup.py
This is mostly to allow brew Formula automation.
=> Adding setup.py to installer

microk8s-resources/actions/enable.kubeflow.sh
Fixes issues related to accidentally relying on `juju-kubectl` plugin, and runs code through `black` for better formatting.
=> Fix 1.0 kubeflow enablement

CODEOWNERS
For automatic assigning of PR reviewers
=> Add @joedborg as code owner for installer directory

microk8s-resources/wrappers/addon-lists.yaml
Kubeflow is not available on arm64
Fixes: https://github.com/ubuntu/microk8s/issues/1091
=> Kubeflow not for ARM64

microk8s-resources/actions/enable.kubeflow.sh
As a workaround for #1097, specifically waits for enabled addons to finish setting up before proceeding to bootstrapping Juju.
Also runs black formatter over kubeflow enable script and fixes lints
=> Better addon handling in Kubeflow addon

microk8s-resources/actions/enable.kubeflow.sh
As a workaround for #1097, specifically waits for enabled addons to finish setting up before proceeding to bootstrapping Juju.
Also runs black formatter over kubeflow enable script and fixes lints
=> Better addon handling in Kubeflow addon [1.18 backport]

microk8s-resources/actions/enable.kubeflow.sh
Adds a minimum recommended amount of memory that will get checked against total system memory before enabling kubeflow. Allows overriding the check with an environment variable.
=> Check total memory before enabling kubeflow

scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py
Cluster agent can configure and connect a dqlite node.
=> Cluster agent configuring dqlite

.github/workflows/build-snap.yml, _config.yml
Getting GH actions to build the project so we get the proposed snap.
Thank you @joedborg for this work.
=> Introduce GH action

installer/setup.py, installer/windows/microk8s.iss
Bump version to reflect recent additions.
=> Installer 1.0.2 release

.gitignore, installer/cli/microk8s.py, installer/common/auxillary.py
Check MacOS disk space remaining.
=> MacOS disk space check

installer/vm_providers/_multipass/_windows.py
=> Multipass v1.2.0 release

microk8s-resources/actions/common/utils.sh
Tested locally to check flags are valid.
=> Extend CA certs to last 10 years

docs/community.md
Hello, I've been playing with MicroK8s on a Raspberry Pi. Its surprising that it works as well as it does!
=> Addition to MicroK8s in the Wild for MicroK8s on Raspberry Pi.

installer/common/definitions.py, microk8s-resources/wrappers/microk8s-refresh-certs.wrapper, scripts/inspect.sh, snapcraft.yaml
This PR adds a refresh-certs command that would refresh the CA certs. The options given in refresh-certs are:
-u, --undo          Revert the last refresh performed
-c, --check         Check the expiration time of the installed CA
-i, --install       Install new CA certificates
Mitigates https://github.com/ubuntu/microk8s/issues/1150
=> Refresh certs command

installer/common/definitions.py, microk8s-resources/wrappers/microk8s-refresh-certs.wrapper, scripts/inspect.sh, snapcraft.yaml
* Refresh certs command
* Add refresh-certs to the definitions
Co-authored-by: Joe Borg <joseph.borg@canonical.com>
=> Refresh certs command (#1159)

snapcraft.yaml
Change the slot name to microk8s to keep it consistent with Juju;
=> Change the slot name to microk8s to keep it consistent with Juju;

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/disable.cilium.sh, microk8s-resources/actions/disable.gpu.sh, microk8s-resources/actions/disable.rbac.sh, microk8s-resources/actions/enable.cilium.sh, microk8s-resources/actions/enable.fluentd.sh, microk8s-resources/actions/enable.gpu.sh, microk8s-resources/actions/enable.istio.sh, microk8s-resources/actions/enable.rbac.sh, microk8s-resources/containerd-profile, microk8s-resources/default-args/containerd-env, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-containerd-with-args, scripts/cluster/agent.py, scripts/cluster/join.py, scripts/inspect.sh, tests/patch-kube-proxy.sh, upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh, upgrade-scripts/001-switch-to-dqlite/commit-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-node.sh
This is a test PR to see if we can address https://github.com/ubuntu/microk8s/issues/1034
=> Try snapctl instead of systemctl

microk8s-resources/default-args/kube-apiserver, snap/hooks/install
This will cause new installations to use token auth and not basic auth for the admin user
=> New installations will use token auth and not basic auth

microk8s-resources/default-args/flanneld, microk8s-resources/default-args/kube-proxy, microk8s-resources/wrappers/run-with-config-args, snap/hooks/configure
@Cynerva this is the PR with the ip-masq fix. It seems to be working fine for me. Any reasons why we would not need to turn ip-masq n by default? Thanks.
Fixes https://github.com/ubuntu/microk8s/issues/1139
=> Set IP masq to true

microk8s-resources/actions/enable.istio.sh, microk8s-resources/wrappers/addon-lists.yaml, snap/hooks/configure, tests/test-addons.py
Updates `istio` to latest version.
Closes #819
=> Upgrade istio to v1.5.1.

microk8s-resources/actions/enable.helm.sh
Fixes: https://github.com/ubuntu/microk8s/issues/1203
=> Update helm to v2.16.7

docs/dqlite.md
This PR updates the dqlite patch with the fix for https://github.com/ubuntu/microk8s/issues/1197 and instructions for producing the patch.
=> Update the dqlite patch and add instructions on producing it

scripts/cluster/agent.py
Fix for the issue https://github.com/ubuntu/microk8s/issues/1224
=> fix the get_token to loop through each line in the file.

tests/test-cluster.py
This will test HA and we can extend it in the future.
We will need to have it called by `test-distro.sh` or call it directly from a Jenkins job.
=> Add a pytest for clustering

scripts/cluster/agent.py, scripts/cluster/join.py
This PR addresses two issues mentioned in https://github.com/ubuntu/microk8s/issues/1127
1. When forming the HA cluster we need to have a single admin user so we can switch master nodes
2. The server certificate should be issued on each node.
=> HA server cert issued on each node. Single admin in HA cluster.

.github/workflows/build-installer.yml
Need to do some work to support Multipass v1.3.0 installer.
=> Pull Multipass v1.3.0

microk8s-resources/actions/common/utils.sh, scripts/cluster/distributed_op.py, scripts/wrappers/common/utils.py, scripts/wrappers/status.py
Fixes: https://github.com/ubuntu/microk8s/issues/1292
=> Handle distribute an operation across nodes

microk8s-resources/actions/enable.kubeflow.sh
Attempts to contact the Juju store before enabling Kubeflow
=> Add connectivity check before enabling Kubeflow

snap/hooks/configure
Address issue https://github.com/ubuntu/microk8s/issues/1293
=> fix snap refresh to 1.18.3

microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml
Upgrade nginx-ingress to `v0.33.0`.
Fixes https://github.com/ubuntu/microk8s/issues/1257
=> use multi arch ingress images.

microk8s-resources/actions/dashboard.yaml
fixes https://github.com/ubuntu/microk8s/issues/601
=> dashboard set imagePullPolicy: IfNotPresent

microk8s-resources/actions/enable.linkerd.sh
New release -> https://linkerd.io/2020/06/09/announcing-linkerd-2.8/
Big feature, multi cluster extension to linkerd.
=> upgrade linkerd 2.8.0 - lots of new features

microk8s-resources/actions/enable.kubeflow.sh, snapcraft.yaml
So that we can update the stable bundle without breaking older versions of microk8s.
=> Pin kubeflow version

docs/build.md, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Increase log filter: from info to error (fix for #1334)
=> Change calico-node pods log level

installer/cli/microk8s.py
Fixes: https://github.com/ubuntu/microk8s/issues/1361
=> Do not display dashboard-proxy twice

microk8s-resources/actions/disable.rbac.sh, microk8s-resources/actions/enable.rbac.sh, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py
When enabling the RBAC addon we ensure we configure all API servers.
When we join a node we pass the authorization mode.
=> Configure RBAC on all HA nodes

microk8s-resources/wrappers/microk8s-refresh-certs.wrapper
Fixes: https://github.com/ubuntu/microk8s/issues/1391
=> Fix: Detect the admin token on refresh cert

microk8s-resources/actions/enable.metallb.sh, microk8s-resources/actions/metallb.yaml, tests/test-addons.py, tests/test-upgrade.py, tests/validators.py
=> Support for multiple IP Ranges in Metallb config

microk8s-resources/actions/enable.kubeflow.sh
Adds the ability to set `KUBEFLOW_BUNDLE` to one of `full`, `lite`, or `edge`. This will let people kick the tires on Kubeflow on their laptops, without having to have a beast of a laptop.
=> Add multiple bundle options for Kubeflow

microk8s-resources/actions/enable.kubeflow.sh
Updates it to match how other addons handle arguments, instead of environment variables. Keeps the environment variables around for now.
=> Regular Kubeflow argument handling

microk8s-resources/wrappers/microk8s-add-node.wrapper
=> Update wording for add-node

microk8s-resources/actions/enable.kubeflow.sh
Fixes issue where a user might specify a port, and the kubeflow enable script blindly appends another port, for something like `foo:123:456`.
=> Improve Kubeflow hostname handling

.travis.yml, build-scripts/set-env-variables.sh
Fixes: https://github.com/ubuntu/microk8s/issues/1440
=> Updating etcd to v3.3.7

microk8s-resources/actions/enable.kubeflow.sh
Ensures that api.jujucharms.com is available from within the Kubernetes cluster, instead of just available from within the host.
=> Add additional connectivity check when enabling Kubeflow

snap/hooks/configure
Unblock the release.
See https://github.com/ubuntu/microk8s/issues/1495
=> Do not re-enable multus on configure hook

microk8s-resources/actions/enable.metallb.sh
Fixes: https://github.com/ubuntu/microk8s/issues/1497
=> Set openssl conf path on metallb

docs/build.md, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Fixes: https://github.com/ubuntu/microk8s/issues/1511
=> Help calico autodetect routing paths

tests/test-addons.py
... until https://github.com/linkerd/linkerd2/issues/4918 is addressed. A linkerd update is needed.
=> Disabling linkerd testing

installer/cli/microk8s.py, installer/setup.py, installer/vm_providers/_base_provider.py, installer/vm_providers/_multipass/_instance_info.py, installer/vm_providers/_multipass/_multipass.py, installer/vm_providers/_multipass/_multipass_command.py, installer/vm_providers/errors.py, microk8s-resources/actions/enable.kubeflow.sh, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/distributed_op.py, scripts/wrappers/refresh-certs.py, tests/test-upgrade.py
Current formatting is causing CI to fail
=> Update formatting of files with black

.flake8, .github/workflows/check-formatting.yml, installer/cli/microk8s.py, installer/setup.py, installer/vm_providers/_multipass/_multipass.py, microk8s-resources/actions/enable.kubeflow.sh, scripts/cluster/agent.py, scripts/cluster/common/utils.py, scripts/cluster/join.py, scripts/wrappers/common/utils.py, scripts/wrappers/dbctl.py, scripts/wrappers/refresh-certs.py, scripts/wrappers/upgrade.py, tests/test-addons.py, tests/test-cluster.py, tests/test-live-addons.py, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py, tests/validators.py, tests/verify-branches.py
black doesn't catch some things such as unused variables or trailing spaces in docstrings, so add flake8 to the CI process.
=> Add flake8 to CI checks

microk8s-resources/actions/enable.cilium.sh, scripts/cluster/agent.py, scripts/wrappers/refresh-certs.py, upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh
Fixes: https://github.com/ubuntu/microk8s/issues/1432#issuecomment-684528046
=> Make sure we reconfigure containerd and kubelet when moving cni bins

.github/workflows/build-snap.yml, .travis.yml, tests/utils.py
This test is passing locally. I am making it to run first.
=> Move the upgrade-path-test to run first

.github/workflows/build-installer.yml
Tested on the dev laptop and sent to IS for signing.
=> Bump Multipass download to 1.4.0

microk8s-resources/actions/enable.storage.sh
Partially fixes https://github.com/ubuntu/microk8s/issues/1557
=> run_with_sudo in enabling storage

scripts/inspect.sh
Check if the hostname does not container capital letters or underscores.
=> Check machine hostname during inspection

microk8s-resources/actions/enable.kubeflow.sh
Disallows enabling Kubeflow as root, and also attempts to fix permissions issues caused by previously attempting to enable Kubeflow as root. If the permissions fix fails, prints out message instructing user how to do it themselves.
Fixes #1396
=> Check current UID and permissions before enabling Kubeflow

snap/snapcraft.yaml
This PR does as recommended to enable debug on both libraft and libdqlite https://github.com/ubuntu/microk8s/issues/1598#issuecomment-699479558
Please review.
=> libraft and libdqlite enable debug

microk8s-resources/actions/disable.kubeflow.sh, microk8s-resources/wrappers/microk8s-disable.wrapper
Taken the approach in https://github.com/ubuntu/microk8s/pull/1467/files#diff-dd95149ceb3dbc7c651119dc7ed10c08
=> Robust disabling of kubeflow

microk8s-resources/actions/enable.kubeflow.sh
Fixes: https://github.com/ubuntu/microk8s/issues/1613
Adds a retry in waiting for the pods to get into Running state.
=> Retry in waiting for pods to get running in kf addon

tests/templates/multus-networks.yaml
Trying to make the multus test more reliable
=> Use a more reliable network configuration for multus network

docs/build.md
Hi there, 
As title says: fixing 1 typo
Didier
=> build.md : just fixing a typo

docs/community.md
Hi there,
Add my repo to the list to show how microk8s can be analyzed with kube-bench through an automated Github workflow
Didier
=> community.md:  microk8s analyzed with kube-bench

scripts/inspect.sh
Adds Juju and Kubeflow info collection to `microk8s inspect`.
=> Expand microk8s inspect debugging

docs/dqlite.md
Hi there, as explained in title. Best, Didier
=> dqlite.md: fix inversion of [] & () in URLs

microk8s-resources/wrappers/apiservice-kicker, snap/hooks/configure
Fixes https://github.com/ubuntu/microk8s/issues/1623
=> Load CNI from api service kicker

installer/cli/microk8s.py
https://github.com/ubuntu/microk8s/issues/1681
https://github.com/ubuntu/microk8s/issues/1661
=> Don't auto start MicroK8s on commands

microk8s-resources/wrappers/run-flanneld-with-args
Fixes: https://github.com/ubuntu/microk8s/issues/1644 https://github.com/ubuntu/microk8s/issues/892 for 1.19
=> Get flannel to use libc from core

microk8s-resources/wrappers/run-flanneld-with-args
Backporting flanneld fix for 20.10
=> Get flannel to use libc from core (#1713)

docs/community.md
Hi there,
I propose to add this repo that shows how to implement Kata Containers with MicroK8s. It's v1 but subsequent improvements to come: see head of README.md
Thanks 
Didier
=> Community.md : adding KataContainer on MicroK8s

docs/build.md
Hi there, just fixing a typo.
Didier
=> build.md: fixing a typo

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml, snap/snapcraft.yaml, tests/test-addons.py
Back porting linkerd upgrade on 1.19.
=> upgrade linkerd 2.9.0 (#1734)

tests/test-upgrade-path.py
Try to address tests flakiness
=> Shorten the upgrade path test from 1.16 to now

docs/community.md
=> Adding repo link for Akri (MSFT) on MicroK8s

microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.cilium.sh
=> Revert "upgrade cilium to version 1.8.3"

microk8s-resources/actions/coredns.yaml, microk8s-resources/actions/enable.dns.sh, tests/test-addons.py, tests/validators.py
=> Add resolv.conf to forward list in coredns

microk8s-resources/actions/enable.kubeflow.sh
Ambassador is no longer used in the bundle
=> Fix Kubeflow hostname handling

.github/workflows/build-installer.yml
=> Bump Multipass to v1.5.0

snap/snapcraft.yaml
Fixes https://github.com/ubuntu/microk8s/issues/1859
=> dqlite patch for 1.20.1

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh, snap/snapcraft.yaml
Until Juju bug #1907860 is fixed, which prevents usage of Istio
=> Reverting Kubeflow bundle to older version

microk8s-resources/actions/enable.kubeflow.sh, snap/snapcraft.yaml
The latest version includes a fix for the issue leading to the reversion
=> Unrevert Kubeflow bundle and update to latest version

installer/vm_providers/_base_provider.py
Initially opening this to get the automated builds.
=> Install integrator snaps along side MicroK8s

.github/workflows/check-formatting.yml
https://github.com/codespell-project/codespell
```
./snap/hooks/configure:288: greate ==> greater, create, grate, great
./snap/hooks/configure:417: doesnt ==> doesn't, does not
./installer/common/auxillary.py:11: Auxillary ==> Auxiliary
./installer/common/auxillary.py:13: auxillary ==> auxiliary
./installer/common/auxillary.py:42: Auxillary ==> Auxiliary
./installer/common/auxillary.py:44: auxillary ==> auxiliary
./installer/common/auxillary.py:107: Auxillary ==> Auxiliary
./installer/common/auxillary.py:109: auxillary ==> auxiliary
./installer/cli/microk8s.py:10: auxillary ==> auxiliary
./upgrade-scripts/000-switch-to-calico/resources/calico.yaml:415: requried ==> required
./scripts/cluster/join.py:113: arguement ==> argument
./microk8s-resources/wrappers/run-apiserver-with-args:38: …
```
=> GitHub Actions: Find typos via codespell

microk8s-resources/default-args/kube-apiserver, snap/hooks/configure
Fixes: https://github.com/ubuntu/microk8s/issues/1877
=> Update only local apiserver args during 1.20 upgrade

installer/cli/microk8s.py, installer/common/auxiliary.py, microk8s-resources/actions/disable.knative.sh, microk8s-resources/actions/enable.kubeflow.sh, microk8s-resources/actions/prometheus/deprecated/grafana-dashboardDefinitions.yaml, microk8s-resources/actions/prometheus/deprecated/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, microk8s-resources/actions/prometheus/deprecated/setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml, microk8s-resources/actions/prometheus/deprecated/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml, microk8s-resources/actions/prometheus/deprecated/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml, microk8s-resources/wrappers/run-apiserver-with-args, microk8s-resources/wrappers/run-cluster-agent-with-args, microk8s-resources/wrappers/run-containerd-with-args, microk8s-resources/wrappers/run-etcd-with-args, microk8s-resources/wrappers/run-flanneld-with-args, microk8s-resources/wrappers/run-with-config-args, scripts/cluster/join.py, snap/hooks/configure, tests/test-upgrade-path.py, tests/utils.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
This is a followup to https://github.com/ubuntu/microk8s/pull/1875
Fix any typos codespell found.
=> Fix typos in the project

microk8s-resources/actions/traefik.yaml
Addmissing permissions for IngressClasses and a relevant API.
=> Update Traefik ClusterRole

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh
Also installs new packages in github actions for testing with pytest.
Also includes password fix.
=> Update Kubeflow bundles to latest stable

microk8s-resources/actions/enable.kubeflow.sh
Includes fixes for Jupyter notebook connections
=> Update Kubeflow bundle to latest stable

.github/workflows/check-formatting.yml
=> GitHub Actions: Make codespell a mandatory test

microk8s-resources/actions/enable.kubeflow.sh
Uses image with curl baked in, and prints out more troubleshooting information.
=> Better connectivity check

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/run-with-config-args, snap/hooks/remove, snap/snapcraft.yaml
Update iptables to v1.8.6 and try set iptable-nft rules for forwarding pod traffic.
========================================================================
=> Iptables-nft and update to v1.8.6

snap/snapcraft.yaml
Back porting python plugin hotfix, code by @joedborg
=> Hotfix for python plugin on core16

microk8s-resources/actions/enable.kubeflow.sh
Includes changes as recent as a637d1b9
=> Backporting Kubeflow addon from master to 1.20

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh, snapcraft.yaml
Includes changes as recent as a637d1b
=> Backporting Kubeflow addon from master to 1.18

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh, snap/snapcraft.yaml
Includes changes as recent as a637d1b
=> Backporting Kubeflow addon from master to 1.19

microk8s-resources/actions/enable.helm3.sh
Tested with https://github.com/ubuntu/microk8s/pull/1871
=> Update helm3 version to 3.5.0

build-scripts/build-k8s-binaries.sh, snap/snapcraft.yaml
As requested in https://github.com/ubuntu/microk8s/pull/1860 I have split the remote build parts
=> Support remote builds

.travis.yml
Xenial has issues pip installing packages
=> Use bionic for travis tests

scripts/inspect.sh
=> With kubelite do not inspect control-plane-kicker

snap/snapcraft.yaml
https://ubuntu.com/security/notices/USN-4728-1
=> Fix for USN-4728-1

.github/workflows/build-installer.yml
Multipass 1.6.1 release to build with the Windows installer.
=> Multipass v1.6.1

.github/workflows/build-snap.yml, .github/workflows/test-kubeflow.yaml
Trying to address recent failures in GHA.
=> Fix lxd install on Github Actions

scripts/cluster/agent.py
Partially addresses issue https://github.com/ubuntu/microk8s/issues/2016
=> Fix: in non-ha cluster etcd with kubelite

.github/PULL_REQUEST_TEMPLATE.md
The URL in the PR template was incorrect
=> Fix contributing.md link

.github/workflows/build-snap.yml, .github/workflows/test-kubeflow.yaml, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-reset.wrapper, snap/snapcraft.yaml, tests/test-addons.py, tests/test-upgrade-path.py
Rat requires libuv v1.18.0 so we need to build it into the snap.
=> Update libuv to v1.18.0

microk8s-resources/wrappers/microk8s-reset.wrapper, scripts/cluster/join.py, snap/snapcraft.yaml
=> Updating to core18

build-scripts/patches/0002-imporve-leader-departure.patch
This PR brings in the fixes in the two PRs:
- https://github.com/canonical/kine/pull/1
- https://github.com/canonical/kvsql-dqlite/pull/3
Fixes: https://github.com/ubuntu/microk8s/issues/1935
=> Improve leader departure

microk8s-resources/actions/enable.cilium.sh, microk8s-resources/actions/enable.helm.sh, microk8s-resources/actions/enable.helm3.sh, microk8s-resources/actions/enable.istio.sh, microk8s-resources/actions/enable.keda.sh, microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/actions/enable.prometheus.sh, microk8s-resources/wrappers/run-flanneld-with-args, scripts/inspect.sh, upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh, upgrade-scripts/001-switch-to-dqlite/commit-master.sh, upgrade-scripts/001-switch-to-dqlite/commit-node.sh, upgrade-scripts/001-switch-to-dqlite/rollback-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh
I meed those when moving to core18
=> Pull CA_CERTS from core18

microk8s-resources/actions/enable.keda.sh, microk8s-resources/wrappers/addon-lists.yaml
=> Update Addon KEDA to v2.1.0

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
=> Update Addon Linkerd v2.9.4

microk8s-resources/actions/enable.ingress.sh
=> Upgrade Addon Ingress Nginx to v0.44.0

build-scripts/pre-patches/0001-Kubelite-integration.patch, build-scripts/pre-patches/0002-Handle-disconnected-leader-in-three-node-cluster.patch
=> Update k8s patches to for building 1.21

.github/workflows/test-kubeflow.yaml
=> Lock Kubeflow tests to particular revision

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/disable.kubeflow.sh
Removes cluster-scoped resources during teardown
Followup to https://github.com/ubuntu/microk8s/issues/1439#issuecomment-795646403
=> Improve Kubeflow addon teardown

microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove, snap/snapcraft.yaml
Reverting until we can understand why containerd does not come back after cold restart.
=> Reverting daemon type back to simple for containerd

microk8s-resources/actions/enable.prometheus.sh
=> Use multi-arch images for prometheus

.github/workflows/cla-check.yml
=> add cla-check

build-scripts/pre-patches/0001-Kubelite-integration.patch
=> K8s patches update for 1.21.0-rc.0

microk8s-resources/actions/coredns.yaml, microk8s-resources/wrappers/addon-lists.yaml
=> update coredns to v1.8.0

microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/run-kubelite-with-args
Fixes: https://github.com/ubuntu/microk8s/issues/2161
=> microK8s start to clean the lock file

installer/windows/microk8s.nsi
Bumping the default track, in the Windows installer, to 1.21
=> Release 1.21 installer bump

microk8s-resources/actions/enable.kata.sh
After testing this with a host with and without KVM enabled, we should check to make sure.  Otherwise, Kata seems to enable correctly but, when you try and schedule anything using the Kata RuntimeClass, it will fail.
Also passed through Black formatter in order to pass tests.
=> Adding KVM check and formatting with Black

build-scripts/set-env-variables.sh
The dqlite did not apply properly to the 1.20.6 release.
=> Update dqlite patch for 1.20.6

scripts/wrappers/status.py
=> Fix yaml output of microk8s.status if not running

scripts/wrappers/status.py
Fix #2147
Signed-off-by: Karl-Philipp Richter <krichter@posteo.de>
=> Fix yaml output of microk8s.status if not running - 1.19 (#2148)

installer/cli/echo.py, tests/testnode/executors.py
=> Style fixes in installer comments

tests/templates/ingress.yaml, tests/validators.py
=> Do not use xip.io for 1.18

installer/cli/echo.py, microk8s-resources/wrappers/microk8s-reset.wrapper, tests/templates/ingress.yaml, tests/validators.py
=> Do not use xip.io on 1.20 branch

tests/validators.py
=> Fix Ambassador tests for xip

microk8s-resources/containerd-profile
Update the apparmor profile kubelite instead of kubelet.
Just a note.  even without the change, there is no visible issue in MicroK8s, so I am not sure if this is something of importance.
=> change apparmor profile from kubelet to kubelite.

microk8s-resources/actions/common/utils.sh, scripts/cluster/agent.py, tests/test-addons.py, tests/validators.py, tox.ini
Fixes: https://github.com/ubuntu/microk8s/issues/2265
=> In lxc detect boot from /proc/1 stats

microk8s-resources/wrappers/run-containerd-with-args
=> Get containerd confined

microk8s-resources/actions/enable.kubeflow.sh
These new bundles contain several important bug fixes.
More information [here](https://github.com/canonical/bundle-kubeflow/pull/362)
=> 1.20 - Update Kubeflow Revisions

microk8s-resources/actions/enable.kubeflow.sh
These new bundles contain several important bug fixes.
More information [here](https://github.com/canonical/bundle-kubeflow/pull/362)
=> Update Kubeflow Revisions

snap/snapcraft.yaml
=> Include libz4 for dqlite snapshot compression

microk8s-resources/actions/dashboard.yaml
=> Migrate from Kubernetes Dashboard v2.0.0 to v2.2.0

.github/workflows/build-snap.yml, .github/workflows/check-formatting.yml, snap/snapcraft.yaml
=> Backport dqlite and lint fixes 1.21

.github/workflows/check-formatting.yml
Add --fix-missing to tox install to see if it fixes the current build failures.
=> Tox Fix Missing

microk8s-resources/actions/fluentd/es-statefulset.yaml, microk8s-resources/actions/fluentd/kibana-deployment.yaml
Resolves #2373 
Upgrading to the latest available versions
=> Elasticsearch and Kibana 7.10

microk8s-resources/actions/disable.openebs.sh
Opened for review.
This is a script for deleting the helm chart along with cStor (legacy), jiva (legacy) components.
=> refact(disable.openebs): Add finalizer removal and BD cleanup to script

installer/requirements.txt, installer/setup.py
=> Update liburl and requests in installer

.github/workflows/build-snap.yml, snap/snapcraft.yaml
Fixes the following error:
```
dqlite: symbol lookup error: /snap/microk8s/2291/bin/dqlite: undefined symbol: sqlite3_system_errno 
```
=> Use libsqlite-dev from the sqlite build

build-scripts/patches/runc/0001-apparmor-change-profile-immediately-not-on-exec.patch, build-scripts/patches/runc/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/patches/runc/0003-standard_init_linux-change-AppArmor-profile-as-late-.patch, microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.dns.sh, snap/snapcraft.yaml
This is a partial revert of a previous commit, and bring in a change to runc.
=> Invert aa nnp order

microk8s-resources/actions/enable.openfaas.sh
=> Fix "Error: unknown flag" in enable.openfaas.sh

microk8s-resources/actions/enable.cilium.sh
Upgrade Cilium to 1.10, needed for v1.22 release.
=> Upgrade cilium to 1.10

microk8s-resources/actions/disable.knative.sh, microk8s-resources/actions/enable.knative.sh
Updating knative version from 0.21 to 0.24. Tested the version and it seems to be working fine  
=> Knative version update

.github/workflows/test-kubeflow.yaml, microk8s-resources/actions/enable.kubeflow.sh
Follow-up to https://github.com/canonical/bundle-kubeflow/pull/380, bumping microk8s revision of kubeflow bundle to match
=> Bump Kubeflow addon to latest revisions

microk8s-resources/wrappers/addon-lists.yaml
We seem to have updated the addons but forgot to update their version numbers.
=> Update addon versions reported by the status command

microk8s-resources/wrappers/run-kubelite-with-args, scripts/inspect.sh
Adds:
* UFW rules for network devices when UFW is detected to make networking work out of the box on systems using UFW
* Warning about missing UFW rules in `microk8s inspect` when rules are missing 
Closes #2418
=> Add config and tips for use with UFW

README.md, build-scripts/patches/0001-Kubelite-integration.patch, build-scripts/patches/0002-Handle-disconnected-leader-in-three-node-cluster.patch
=> Prepare for 1.22 build

microk8s-resources/actions/enable.openebs.sh, tests/test-addons.py
Disabling this addon due to https://github.com/ubuntu/microk8s/issues/2498
=> Disable openebs addon until is fixed for v1.22

microk8s-resources/wrappers/run-kubelite-with-args
Handles the case where UFW is failing for some reason. See https://github.com/ubuntu/microk8s/issues/2488#issuecomment-896827686
=> Fail gracefully in setting ufw rules

snap/snapcraft.yaml
=> Bump Juju version

snap/snapcraft.yaml
Use the snap_microk8s group and update the microk8s slot.
=> Add snap_microk8s group and missing slot

microk8s-resources/actions/common/utils.sh, snap/hooks/configure, snap/snapcraft.yaml
This is to prepare the transition to the strict snap where we have the new group snap_microk8s
=> Copy users to the new snap_microk8s group

installer/common/definitions.py, installer/windows/microk8s.nsi
For the Windows and MacOS installer.
=> Bump installer to 1.22 default channel

microk8s-resources/actions/enable.ingress.sh
Await build test passes before merging.
=> Bump ingress version

.github/workflows/build-snap.yml
Upload any AppArmor denials post strict tests.
=> Upload AppArmor denials post tests

microk8s-resources/actions/enable.openebs.sh
Fixes a typo introduced in #2607
=> Fix typo in helm install command

microk8s-resources/actions/enable.openebs.sh
This modifies the helm install command for the OpenEBS addon, and pins v2.x.x to microk8s v1.22
=> Helm install command pinning openebs v2.x.x to microk8s v1.22

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/actions/enable.kubeflow.sh, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/microk8s-dashboard-proxy.wrapper, microk8s-resources/wrappers/microk8s-dbctl.wrapper, microk8s-resources/wrappers/microk8s-disable.wrapper, microk8s-resources/wrappers/microk8s-enable.wrapper, microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-refresh-certs.wrapper, microk8s-resources/wrappers/microk8s-remove-node.wrapper, microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper, scripts/cluster/common/utils.py, snap/hooks/configure, snap/snapcraft.yaml, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh
This PR would better be reviewed and merged after snapd 2.52 lands.
=> Initial work on snap_microk8s group

.github/workflows/build-installer.yml
=> Change method of setting PATH

installer/windows/microk8s.nsi
Bumping release version to include new EnVar library to fix https://github.com/ubuntu/microk8s/issues/2639
=> Installer 2.2.1 release

tests/utils.py
=> [1.18 Backport] Fix yaml loading in tests (#2698)

tests/utils.py
=> [1.19 Backport] Fix yaml loading in tests (#2698)

tests/test-addons.py, tests/utils.py
=> [1.20 Backport] Fix yaml loading in tests (#2698)

tests/test-addons.py, tests/utils.py
=> [1.21 Backport] Fix yaml loading in tests

tests/test-addons.py, tests/utils.py
=> [1.22 Backport] Fix yaml loading in tests

microk8s-resources/actions/disable.portainer.sh
disabled deletion of pvc during add-on disabling
=> updated portainer disable script

microk8s-resources/actions/enable.ingress.sh
To address https://github.com/kubernetes/ingress-nginx/issues/7837
=> Bump ingress to v1.0.5

microk8s-resources/actions/enable.linkerd.sh, microk8s-resources/wrappers/addon-lists.yaml
=> Upgrade linkerd to version 2.11.1

installer/cli/microk8s.py
This PR fixes #2508 https://github.com/ubuntu/microk8s/issues/2739
=> Pull inspection tarball out of the multipass VM

microk8s-resources/actions/jaeger/operator.yaml
Upgrade jaeger operator to `v1.28.0`
* [X ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
=> upgrade jaeger operator

snap/hooks/configure
=> Fix typo in configure hook script

microk8s-resources/default-args/kube-apiserver, snap/hooks/configure
This argument will either way be removed on v1.24 and has currently no effect.
=> Remove the --insecure-port argument

installer/cli/microk8s.py
Changed `Would you like to do that it now?` to `Would you like to do that now?` in installer.
=> Fixed a typo

snap/hooks/configure
Fixes: https://github.com/ubuntu/microk8s/issues/2788
=> Remove insecure-port only from local config

microk8s-resources/actions/fluentd/es-statefulset.yaml
https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/Log4Shell
=> Hotfix ElasticSearch for Log4Shell

.github/workflows/build-installer.yml, installer/windows/microk8s.nsi
Multipass 1.8.0
Track 1.23/stable
=> Bump Multipass and default track

microk8s-resources/actions/dashboard.yaml, microk8s-resources/wrappers/addon-lists.yaml
=> Upgrade dashboard to v2.3.0 to fix ingress API 404

microk8s-resources/actions/dashboard.yaml, microk8s-resources/wrappers/addon-lists.yaml
Backport fix of https://github.com/ubuntu/microk8s/issues/2791 to 1.22
=> upgrade dashboard to v2.3.0 to fix ingress API 404 (#2792)

scripts/cluster/agent.py
Replaces #2835. 
When the hostname of the joining node does not resolve, outright refuse to join in the cluster. This is because DNS resolution is required for most kubectl commands, which fail otherwise.
=> Reject joins when the hostname cannot be resolved

.github/workflows/build-snap.yml, build-scripts/set-env-variables.sh
=> Create the 1.23 branch

.github/workflows/strict-common.yml
A very quick test, that we can build upon, to test for common strict branch merge issues.
=> Check strict common mistakes

scripts/inspect.sh
Remove sudo from inspection script.
=> Fix inspect in strict

microk8s-resources/actions/storage.yaml
=> 1.21 Backport: Update hostpath-provisioner version to 1.1.0

microk8s-resources/actions/storage.yaml
=> 1.22/Backport #2853: Upgrade hostpath-provisioner image to 1.1.0

microk8s-resources/actions/storage.yaml
=> 1.23/Backport #2853: Upgrade hostpath-provisioner image to 1.1.0

upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh
Backporting https://github.com/ubuntu/microk8s/pull/2864
=> Remove the dqlite related argument from the API server when disabling HA

build-scripts/set-env-variables.sh
Update k8s-dqlite version to include Kine fix https://github.com/canonical/kine/pull/7
Merge after https://github.com/canonical/kine/pull/7 and https://github.com/canonical/k8s-dqlite/pull/18 are merged.
=> Update k8s-dqlite to v1.0.3

build-scripts/set-env-variables.sh
Backport #2872 to 1.23 branch.
=> 1.23 Backport - Update k8s-dqlite version to 1.0.3

microk8s-resources/actions/storage.yaml
=> Backport 1.23 - Fix RBAC rules for hostpath-storage

microk8s-resources/actions/storage.yaml
=> Backport 1.22 Fix RBAC rules for hostpath-storage

microk8s-resources/actions/storage.yaml
=> Backport 1.21 Fix RBAC rules for hostpath-provisioner

microk8s-resources/actions/storage.yaml
=> Backport 1.21 Fix error retrieving resource lock

microk8s-resources/actions/storage.yaml
=> Backport 1.22 Fix error retrieving resource lock

microk8s-resources/actions/storage.yaml
=> Backport 1.23 Fix error retrieving resource lock

build-scripts/set-env-variables.sh
=> Backport 1.23: Upgrade containerd to 1.5.9 and runc to 1.0.3

scripts/wrappers/common/utils.py
=> Silence dqlite errors in microk8s status

snap/snapcraft.yaml
Fixes https://github.com/ubuntu/microk8s/issues/2921
=> Delete addons dir if already created on previous build

microk8s-resources/wrappers/run-kubelite-with-args
Closes https://github.com/ubuntu/microk8s/issues/2920
See https://github.com/ubuntu/microk8s/issues/2920#issuecomment-1040272348
=> Fix host-access IP on kubelite restart

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/build.md, docs/s390x.md, installer/setup.py, microk8s-resources/wrappers/run-kubelite-with-args, snap/hooks/configure, tests/verify-branches.py
Update references to ubuntu repo.
=> Remove references to ubuntu repository

microk8s-resources/actions/common/utils.sh
=> Properly resolve host IP with multiple default routes

tests/lxc/microk8s-zfs.profile, tests/lxc/microk8s.profile
=> lxc: update /dev/kmsg type to unix-char (#2946)

microk8s-resources/actions/common/utils.sh
Two changes:
- Run_with_sudo to work everywhere.
- Basic functions for strict only
Work towards closing the gap between strict and classic.
=> Update utils.sh to allow basic functionality on classic and strict

scripts/cluster/agent.py, scripts/cluster/join.py
Fixes: https://github.com/canonical/microk8s/issues/2952
=> Pass the authz configuration of the master node to the joining ones

scripts/cluster/agent.py, scripts/cluster/join.py
=> Pass the authz configuration of the master node to the joining ones (#2977)

snap/snapcraft.yaml
=> Add SQLITE_ENABLE_DBSTAT_VTAB=1 to enable this virtual table

pyproject.toml, scripts/cluster/common/utils.py, scripts/cluster/join.py, scripts/wrappers/addons.py, scripts/wrappers/disable.py, scripts/wrappers/enable.py, scripts/wrappers/reset.py, scripts/wrappers/status.py, tox.ini
Pin click to 8.0.4 so black is not broken.
Get flake8 to run by:
- addressing errors and
- ignoring "Too complex" methods and variable naming issues.
=> Pin click version and get flake8 running

tox.ini
Backport parts of #3014 to 1.21 branch
=> Pin click to 8.0.4 to fix Black

build-scripts/set-env-variables.sh
=> Backport 1.23: Update containerd to v1.5.11

snap/snapcraft.yaml
=> Backport 1.23 Fix containerd build

build-scripts/set-env-variables.sh
=> Backport 1.22 Update containerd to 1.5.11

scripts/cluster/join.py
=> Do not ignore --skip-verify flag in microk8s join

microk8s-resources/wrappers/apiservice-kicker, scripts/cluster/add_token.py
=> Do not show traceback when cluster agent restart fails

scripts/cluster/join.py
=> [Backport 1.23] Honor --skip-verify flag in microk8s join

scripts/cluster/join.py
=> [Backport 1.22] Honor --skip-verify flag in microk8s join (#3055)

scripts/cluster/join.py
=> [Backport 1.21] Honor --skip-verify flag in microk8s join (#3055)

microk8s-resources/actions/common/utils.sh
=> Fix ip counter in render csr template function (#3059)

build-scripts/set-env-variables.sh
This PR has to be merged after https://github.com/canonical/microk8s-community-addons/pull/38
=> Build community addons for strict from main

snap/snapcraft.yaml
Fixes: https://github.com/canonical/microk8s/issues/3085
=> Include kernel module utils in the snap

snap/snapcraft.yaml
Back porting https://github.com/canonical/microk8s/pull/3102 to 1.21
=> Package kernel module utils in the snap - 1.21

scripts/inspect.sh
=> do not get dqlite info and service when it is running without HA

scripts/wrappers/dashboard_proxy.py
Kubernetes 1.24 feature flag `LegacyServiceAccountTokenNoAutoGeneration` is enabled by default, breaking the `microk8s dashboard-proxy` command.
Update the command to create a secret for the default service account, then retrieve that token.
References https://kubernetes.slack.com/archives/CAUNWQ85V/p1652119910618009
=> do not use default-token for accessing dashboard

scripts/wrappers/reset.py
This PR adds statefulsets as resources to be removed when `microk8s reset` is issued
=> Delete statefulsets on reset

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.yml, .github/PULL_REQUEST_TEMPLATE.md
Add new issue and pull request templates.
=> Update issue and pull request templates

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.21] improve handling for br_netfilter module

scripts/wrappers/status.py
Possibly fixes https://github.com/canonical/microk8s/issues/3150
=> Fix disabled repos status

.github/workflows/build-installer.yml, installer/cli/microk8s.py, installer/common/auxiliary.py, installer/common/definitions.py, installer/requirements.txt, installer/tests/integration/test_cli.py, installer/tests/unit/test_auxiliary.py, installer/tests/unit/test_cli.py
This PR aims to fix https://github.com/canonical/microk8s/issues/2915
Essentially, it adds a some validations on windows installer cli arguments.
=> Validate installer arguments

scripts/wrappers/addons.py, snap/snapcraft.yaml, tests/requirements.txt, tests/unit/test_addons.py, tox.ini
This PR adds some validation checks when adding addon repositories:
- Check that addons.yaml files is correct (according to [the addons docs](https://microk8s.io/docs/howto-addons))
- Check that enable and disable hooks are present and have the right permissions.
=> Validate newly added addon repositories

.flake8, tox.ini
Fixes: https://github.com/canonical/microk8s/issues/3177
=> Fix lint inconsistencies

microk8s-resources/wrappers/run-containerd-with-args
Added strict checks and combined logic into apparmor confinement and containerd boot detection
Added `is_strict` strict checks and combined strict/classic logic to apparmor confinement and containerd boot detection
=> Added strict checks and combined logic into run-containerd wrapper

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-add-node.wrapper
Added `is_strict` checks and combined logic to add-node and fixed a typo in `exit_if_not_root`. 
Added `is_strict` checks and combined strict/classic logic to add-node and fixed a typo in `exit_if_not_root`.
Added conditional install message output for the command based on if strictly confined
=> Added strict checks to add-node and fixed a typo in utils

microk8s-resources/wrappers/microk8s-addons.wrapper, microk8s-resources/wrappers/microk8s-ctr.wrapper, microk8s-resources/wrappers/microk8s-dashboard-proxy.wrapper
Added strict checks and combined logic to addons, ctr and dashboard-proxy commands
Added `is_strict` check and `LANG` exports based on if strictly confined
Added `is_strict` check, combined strict/classic logic and `exit_if_not_root` to `ctr` command
Added `exit_if_not_root` to `dashboard-proxy` commands
Existing test should cover the changes.
=> Added strict checks and combined logic to addons, ctr and dashboard-proxy commands

microk8s-resources/wrappers/microk8s-join.wrapper, microk8s-resources/wrappers/microk8s-leave.wrapper, microk8s-resources/wrappers/microk8s-refresh-certs.wrapper
Added strict checks, combined classic/strict logic and LANG settings for join, leave and refresh-certs
Added `is_strict` checks, combined classic/strict logic and added LANG settings for join, leave and refresh-certs
=> Added strict checks, combined classic/strict logic and LANG settings for join, leave and refresh-certs

microk8s-resources/wrappers/microk8s-reset.wrapper, microk8s-resources/wrappers/microk8s-start.wrapper, microk8s-resources/wrappers/microk8s-stop.wrapper
Added strict checks, LANG exports and combined strict/classic logic for reset, stop, start
Added `LANG` and `LC_ALL` exports for `reset` command
Added `is_strict` checks and combined strict/classic logic for `stop` `start`
=> Added strict checks, LANG exports and combined strict/classic logic for reset, stop, start

microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s.wrapper
Add strict checks, combined strict/classic logic to apiservice-kicker and microk8s.wrapper
Changed `sudo` call in `microk8s.wrapper` for inspection to `run_with_sudo preserve_env`.
Added strict checks and combined restart logic for classic/strict in `apiservice-kicker`
=> Add strict checks, combined strict/classic logic to apiservice-kicker and microk8s.wrapper

microk8s-resources/wrappers/run-flanneld-with-args, microk8s-resources/wrappers/run-kubelite-with-args
Added strict checks and combined logic to flanneld and kubelite
Added strict checks and combined logic to flanneld and kubelite
=> Added strict checks and combined logic to flanneld and kubelite

snap/hooks/configure, snap/hooks/install
Added strict checks and combined strict/classic logic to install hook
Added strict checks and combined strict/classic logic to install hook
=> Added strict checks and combined strict/classic logic to install hook

snap/hooks/remove
Added strict checks and combined strict/classic logic to remove hook
Added strict checks and combined strict/classic logic to remove hook
=> Added strict checks and combined strict/classic logic to remove hook

snap/hooks/connect-plug-account-control, snap/hooks/connect-plug-cifs-mount, snap/hooks/connect-plug-docker-privileged, snap/hooks/connect-plug-docker-support, snap/hooks/connect-plug-dot-config-helm, snap/hooks/connect-plug-dot-kube, snap/hooks/connect-plug-firewall-control, snap/hooks/connect-plug-fuse-support, snap/hooks/connect-plug-hardware-observe, snap/hooks/connect-plug-home, snap/hooks/connect-plug-home-read-all, snap/hooks/connect-plug-k8s-journald, snap/hooks/connect-plug-k8s-kubelet, snap/hooks/connect-plug-k8s-kubeproxy, snap/hooks/connect-plug-kernel-crypto-api, snap/hooks/connect-plug-kernel-module-observe, snap/hooks/connect-plug-kubernetes-support, snap/hooks/connect-plug-log-observe, snap/hooks/connect-plug-login-session-observe, snap/hooks/connect-plug-mount-observe, snap/hooks/connect-plug-network, snap/hooks/connect-plug-network-bind, snap/hooks/connect-plug-network-control, snap/hooks/connect-plug-network-observe, snap/hooks/connect-plug-opengl, snap/hooks/connect-plug-process-control, snap/hooks/connect-plug-system-observe, snap/hooks/disconnect-plug-network-control
Added interface plug hooks for strict confinement
Added interface plug hooks for strict confinement
=> Added interface plug hooks for strict confinement

scripts/cluster/common/utils.py, scripts/wrappers/addons.py, scripts/wrappers/common/utils.py, tests/unit/test_addons.py
Added dynamic group determination and strict check to py utils and addons
Added dynamic group determination and strict check to py utils and addons
=> Added dynamic group determination and strict check to py utils and addons

scripts/inspect.sh
Get PVCs from all namespaces in the inspect script
None
=> Retrieve PVCs from all namespaces in the introspection report script

scripts/wrappers/common/utils.py
Backport of #3176 to 1.21 branch
=> [Backport 1.21] Make sure to use microk8s-kubectl.wrapper (#3176)

microk8s-resources/actions/enable.gpu.sh
Backport https://github.com/canonical/microk8s-core-addons/pull/44 to 1.22 branch
=> [Backport 1.22] update GPU operator 

microk8s-resources/actions/enable.gpu.sh
Backport https://github.com/canonical/microk8s-core-addons/pull/44 to 1.23 branch
=> [Backport 1.23] update GPU operator

upgrade-scripts/000-switch-to-calico/commit-master.sh, upgrade-scripts/000-switch-to-calico/commit-node.sh, upgrade-scripts/000-switch-to-calico/rollback-master.sh, upgrade-scripts/000-switch-to-calico/rollback-node.sh, upgrade-scripts/001-switch-to-dqlite/commit-master.sh, upgrade-scripts/001-switch-to-dqlite/commit-node.sh, upgrade-scripts/001-switch-to-dqlite/rollback-master.sh, upgrade-scripts/001-switch-to-dqlite/rollback-node.sh, upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh, upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh
Added strict checks and dynamic group determination to upgrade scripts
Added strict checks and dynamic group determination to upgrade scripts
=> Added strict checks and dynamic group determination to upgrade scripts

microk8s-resources/wrappers/microk8s.wrapper, scripts/inspect.sh, snap/snapcraft.yaml
With this PR the inspect script should work as is in both stric and classic. There are a few "if is_strict" branches in the inspect script and minor fixes in the wrappers calling the inspection script. Also there should not be any denials thrown anymore.
- "if is_strict" branches in the inspect script
- updates in the wrappers calling the inspection script.
Manual testing. Build the strict and classic snap, install it and call the inspection command.
=> Inspect command to work on both strict and classic

scripts/cluster/join.py
References #2402
Closes #3184 
- Make sure to set the `--node-ip` kubelet flag properly when joining a cluster where the flag is set.
1. Install MicroK8s on a node, then configure `--node-ip` kubelet argument
2a. Install MicroK8s on a second node, then join as a control plane or worker-only node
2b. Install MicroK8s on a second node, disable HA-cluster, join node.
In all cases, the `--node-ip` of the joining node should be updated and set to the correct IP address. 
This only affects clusters where the `--node-ip` argument has been explicitly set by the administrator. It does not have implications by default.
This needs to be backported to all supported tracks
=> ensure kubelet --node-ip is set correctly when joining a cluster

scripts/cluster/join.py
Backport https://github.com/canonical/microk8s/pull/3216 to 1.23 branch.
=> [Backport 1.23] ensure kubelet --node-ip is set correctly when joining a cluster (#3216)

scripts/cluster/join.py
Backport #3216 to 1.24 branch.
=> [Backport 1.24] ensure kubelet --node-ip is set correctly when joining a cluster (#3216)

.github/workflows/build-snap.yml
Run our test on GH with snapd from candidate this way we will be catching potentially breaking changes originating from snapd.
Update the gh actions spec.
In the actions of this PR
=> Install latest candidate snapd to run our tests on GH

build-scripts/set-env-variables.sh
Upgrade containerd to 1.5.13
https://github.com/containerd/containerd/releases/tag/v1.5.13
=> [1.24] Upgrade containerd to 1.5.13

build-scripts/set-env-variables.sh
=> [1.23] upgrade containerd to 1.5.13

scripts/cluster/join.py
Backport parts of #3216 to 1.22 branch.
=> [Backport 1.22] ensure kubelet --node-ip is set correctly when joining a cluster (#3216)

scripts/cluster/images.py
Small follow up fix that was missed in #3187
=> fix missing image name in export command

snap/snapcraft.yaml, tests/test-cluster.py, tests/test-distro.sh, tests/utils.py
Closes the gap between strict an master branches and make sure the test-cluster.py runs on strict.
=> Fixes in strict cluster testing

tests/validators.py
Backport of https://github.com/canonical/microk8s-core-addons/pull/53 to 1.23
=> Fix stray kubectl in forward test

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.24] Check the correct file for AppArmor confinement. (#3172)

build-scripts/update-images.sh
Add update-images.sh script to the 1.23 branch (requirement for https://github.com/canonical/microk8s/pull/3294)
=> [1.23] add update-images.sh script

build-scripts/update-images.sh
Add update-images.sh script to the 1.22 branch (requirement for https://github.com/canonical/microk8s/pull/3294)
=> [1.22] add update-images.sh script

build-scripts/update-images.sh
Add `update-images.sh` script to the 1.24 branch (requirement for #3294)
=> [1.24] add update-images.sh script

.github/workflows/update-images.yml
Follow up for #3294, fixing the event triggers
=> fix github action event triggers

microk8s-resources/wrappers/apiservice-kicker, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Backporting the offloading fix of https://github.com/canonical/microk8s/pull/3306
=> Let calico handle offloading

build-scripts/set-env-variables.sh
Build the cluster-agent from the 1.24 branch
=> build cluster-agent from 1.24 branch

build-scripts/components/etcd/build.sh
Fixes build failures for etcd 3.4.3 on arm64
Follow up PR from #3324
=> fix etcd build for arm64

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-add-node.wrapper, microk8s-resources/wrappers/microk8s-cilium.wrapper, microk8s-resources/wrappers/run-cluster-agent-with-args, microk8s-resources/wrappers/run-containerd-with-args, microk8s-resources/wrappers/run-etcd-with-args, scripts/inspect.sh, scripts/wrappers/dbctl.py, scripts/wrappers/join.py, snap/hooks/install, upgrade-scripts/000-switch-to-calico/resources/calico.yaml, upgrade-scripts/001-switch-to-dqlite/commit-master.sh
Fix some hardcoded paths in a few places, use `$SNAP` and `$SNAP_DATA` instead.
=> Clean up some hardcoded Snap paths

scripts/wrappers/join.py
Fix race condition when adding node
Do not restart kubelite multiple times
=> Do not needlessly restart services when joining workers

scripts/cluster/join.py
Backport https://github.com/canonical/microk8s/pull/3350 to 1.24
=> Do not needlessly restart services when joining workers - 1.24

scripts/cluster/join.py
Backporting of https://github.com/canonical/microk8s/pull/3350 to 1.23
=> Do not needlessly restart services when joining workers - 1.23

scripts/wrappers/refresh_certs.py
This improves/fixes the output of the refresh-certs command
=> Improve the output of refresh certs

microk8s-resources/actions/common/utils.sh
Enhanced the grep search for kubelet token by specifying additional criteria for the search string
Closes #3329 
Added additional criteria on search string for searching kubelet-0
=> fix grep search for kubelet token

microk8s-resources/actions/common/utils.sh, scripts/wrappers/addons.py, scripts/wrappers/common/utils.py
Initial support for ppc64le
Sibling PRs:
- https://github.com/canonical/microk8s-core-addons/pull/79
- https://github.com/canonical/microk8s-community-addons/pull/76
=> Add ppc64le support

scripts/wrappers/addons.py, scripts/wrappers/common/utils.py, tox.ini
Back porting https://github.com/canonical/microk8s/pull/3394
=> Handle brnaches that changed names for local repos (#3394) for 1.24

microk8s-resources/wrappers/microk8s-helm.wrapper, microk8s-resources/wrappers/microk8s-helm3.wrapper, scripts/calico/upgrade.py, scripts/inspect.sh, scripts/wrappers/join.py
Improvements in worker node UX.
Closes https://github.com/canonical/microk8s/issues/3408
- if the cni-loaded file is missing do not delete it again during calico upgrades
- do not report dqlite service failing on worker nodes
- print usage message in worker nodes
- helm command "guards"
=> UX imporvements for worker nodes

scripts/wrappers/join.py
Followup for #3434, ensure that all join scenarios are handled
=> Ignore --hostname-override for control plane and etcd nodes

snap/snapcraft.yaml, tests/test_distros.py, tox.ini
Fix build failure https://launchpadlibrarian.net/623293580/buildlog_snap_ubuntu_bionic_s390x_microk8s-1.22_BUILDING.txt.gz
```
+ rm actions/gpu.yaml
rm: cannot remove 'actions/gpu.yaml': No such file or directory
```
=> Fix s390x build

build-scripts/components/etcd/version.sh
=> (1.25) Update etcd to version 3.4.21

tests/test-cluster.py
On some ubuntu versions ip is under /sbin/
=> Search for ip on the right location in cluster testing

scripts/wrappers/common/utils.py
Backport #2918 to 1.23 branch
Closes #3479
=> [Backport 1.23] Silence dqlite errors in microk8s status (#2918)

scripts/wrappers/common/utils.py, scripts/wrappers/dbctl.py
Taking over the automated PR #3494 
The patch essentially checks to see if all tarfile members will be extracted safely and throws an exception otherwise. 
Manually tested by calling the command this change has effected.
=> Patch for CVE-2007-4559

upgrade-scripts/000-switch-to-calico/resources/calico.yaml
=> [1.25] Remove unused bpf mounts on Calico pods

tests/test-distro.sh
Update detection of eksd tests
Update detection of eksd tests
=> Update detection of eksd tests

.github/workflows/check-unit-tests.yml, tests/test-distro.sh
Porting eksd tests to main branch
Eksd integration tests
Ran jobs on jenkins to verify.
=> EKS-D integration tests to main

tests/test-distro.sh
Integration tests for 1.23-eksd
Integration tests for 1.23-eksd
Ran jenkins jobs to verify
=> Integration tests for 1.23-eksd

build-scripts/components/containerd/version.sh, build-scripts/components/runc/version.sh
This MR updates `containerd` to v1.6.9, the latest release at the time of writing.
It includes a updated version of `continuity`, which should fix the issue I reported at https://github.com/canonical/microk8s/issues/3499.
Update of `containerd` from v1.6.6 to v1.6.9.
=> Update containerd to v1.6.9

.github/workflows/check-unit-tests.yml
Backporting pinning pytest version on github actions
=> [Backport 1.25] Pin pytest version on actions

upgrade-scripts/000-switch-to-calico/resources/calico.yaml
=> [Backport 1.25] Upgrade to Calico 3.23.5

build-scripts/components/containerd/version.sh, build-scripts/components/runc/version.sh
=> [Backport 1.25] Update containerd to v1.6.9

.github/workflows/update-images.yml
Add update images job for all stable branches, strict and eksd.
=> Update build-scripts/images.txt for all active branches

.github/workflows/check-unit-tests.yml
=> Pin pytest version on actions

installer/cli/microk8s.py
=> Fixes: microk8s dashboard-proxy no longer use default-token

scripts/wrappers/join.py, snap/hooks/configure
=> [Backport 1.25] fix kubeconfig for worker node services

.github/workflows/check-unit-tests.yml, scripts/wrappers/join.py, snap/hooks/configure
Back porting https://github.com/canonical/microk8s/pull/3554
=> Fix kubeconfig for worker node services 1.22-eksd

.github/workflows/check-unit-tests.yml, scripts/wrappers/join.py, snap/hooks/configure
Back porting https://github.com/canonical/microk8s/pull/3554
=> fix kubeconfig for worker node services on 1.25-strict 

snap/snapcraft.yaml
Set the license so that `snap info microk8s` reports it.
=> Set license in snapcraft.yaml

build-scripts/addons/repositories.sh
Pin community and eksd addons to specific branches
Pinned the addons repositores for community and eksd to `1.22-eksd`
=> [1.22-eksd] Pin community and eksd addons to specific branches

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-provider-id-update, snap/hooks/configure
Backport [#3561] Provider id detection to 1.22-eksd
=> [Backport 1.22-eksd] Added auto add for provider id on eksd

build-scripts/components/k8s-dqlite/version.sh
Bump k8s-dqlite to include https://github.com/canonical/kine/pull/11
Merge after https://github.com/canonical/k8s-dqlite/pull/33
=> Bump k8s-dqlite to 1.1.0

tox.ini
Update click version in tox
Update click version in tox
=> [1.22-eksd] Update click version in tox

tox.ini
Update click version in tox
Update click version in tox
=> [1.23-eksd] Update click version in tox

.github/workflows/build-snap.yml, build-scripts/components/cluster-agent/version.sh, snap/hooks/configure, tests/test-upgrade-path.py
Fix cluster agent version and remove rebasing artifact
Updated the cluster agent version from `1.24` to `1.25`
Removed a rebasing artifact in `configure` hook (the functionality is already implemented check line 598)
Manually tested on LXD.
=> [1.24-eksd] Fix cluster agent version and remove rebasing artifact

.github/workflows/build-snap.yml, build-scripts/addons/repositories.sh, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh
As part of branching the 1.26 code.
=> Branch 1.26

.github/workflows/build-snap.yml, build-scripts/addons/repositories.sh, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh
As part of branching the 1.26 code.
=> Branch 1.26 strict

tests/test-distro.sh
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Manually tested by running `test-distro.sh` with required parameters.
=> [main] Added the cloud formation template and updated tests

tests/test-distro.sh
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Manually tested by running `test-distro.sh` with required parameters.
=> [1.24-eksd] Added the cloud formation template and updated tests

tests/test-distro.sh
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Manually tested by running `test-distro.sh` with required parameters.
=> [1.22-eksd] Added the cloud formation template and updated tests

tests/test-distro.sh
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Added a cloudformation template so that required resources for EKSD testing are handled uniformly and cleanly. 
Manually tested by running `test-distro.sh` with required parameters.
=> [1.23-eksd] Added the cloud formation template and updated tests

installer/common/definitions.py
=> #Fixes 3628 Update microk8s version to 1.26 for homebrew formula

build-scripts/components/containerd/version.sh
Bumping containerd to version 1.6.15
=> Bump containerd to 1.6.15

build-scripts/components/python/requirements.txt, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-flanneld-with-args, snap/snapcraft.yaml, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_22.04, tests/test-airgap.sh
Fixed python packaging, switched missing libraries and updated yaml bits
* Switch from core18 to core20
* Replaced btrfs-tools with btrfs-progs and libbtrfs-dev
* Upgraded libssl1.0.0 to libssl1.1
* Changed python packaging to work with core20
Snapped, installed and tested manually on 18.04, 20.04, 22.04 with workloads.
Initial assessment seems like the changed packages do not cause a problem, there might be things that hasn't come up yet.
=> Upgrade from core18 to core20

tests/test-distro.sh
Close the gap between test-upgrade-path in strict
Close the gap between test-upgrade-path in strict
Manually tested.
=> [strict] Close the gap between test-upgrade-path in strict

snap/snapcraft.yaml
Removed ufw-init from layouts
Removed ufw-init from layouts
Manually tested by installing the snap.
=> Removed ufw-init from layouts

microk8s-resources/actions/enable.ingress.sh, microk8s-resources/actions/ingress.yaml
Backport [ingress addon fix to v1.5.1]( https://github.com/canonical/microk8s-core-addons/pull/132) to 1.23
=> Backport ingress bump v1.5.1 to 1.23

tests/test-distro.sh
Run the GPU tests on the host since all tests are run in lxc containers
This work is in test-distro.sh
Manual
=> Run GPU tests on 1.25

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Add a function for all the services to remove deprecated arguments.
Included a new util function for argument sanitization. Used this function in all the desired services.
=> Add arguments sanitisation when starting services

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, tox.ini
Add a function for all the services to remove deprecated arguments. Backporting https://github.com/canonical/microk8s/pull/3690 to 1.24
=> Add arguments sanitisation when starting services (#3690) - 1.24

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Add a function for all the services to remove deprecated arguments. Backporting https://github.com/canonical/microk8s/pull/3690 to 1.24-eksd
=> Add arguments sanitisation when starting services (#3690) - 1.24-eksd

snap/hooks/install
quick fix for regression introduced while rebasing #3719
=> Fixup install hook

build-scripts/components/cni/build.sh
Reverted to 1.1.2 flannel plugin since 1.2.0 was retracted
Reverted to 1.1.2 flannel plugin since 1.2.0 was retracted
Manually tested by building and installing.
=> [1.24-eksd] Reverted to 1.1.2 flannel plugin since 1.2.0 was retracted

.github/workflows/build-snap.yml, tests/test-distro.sh
This is a follow up PR for [microk8s-community-addons#120](https://github.com/canonical/microk8s-community-addons/pull/120).
Updated tests so pytest targets a folder instead of the `test-addons.py`.
=> Update community tests to point to a folder

build-scripts/components/dqlite/build.sh, build-scripts/components/raft/build.sh
As discussed on Mattermost with @ktsakalozos.
Signed-off-by: Cole Miller <cole.miller@canonical.com>
=> Build libdqlite and libraft with debuginfo

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Backport #3725, #3717, #3705, #3731, #3740
=> [1.26] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Backport #3725, #3717, #3705, #3731, #3740
=> [1.25] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/cluster/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, tests/unit/test_refresh_certs.py
=> [1.24] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/cluster/join.py, scripts/wrappers/refresh-certs.py, snap/hooks/configure, snap/hooks/install, tests/test-addons.py
=> [1.23] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/cluster/join.py, scripts/wrappers/refresh-certs.py, snap/hooks/configure, snap/hooks/install, tests/test-addons.py
=> [1.22] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Backport #3685, #3725, #3717, #3705, #3731, #3740
=> [1.24-eksd] Backport bugfixes

microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Backport #3685, #3725, #3717, #3705, #3731, #3740
=> [1.23-eksd] Backport bugfixes

snap/hooks/install
Fail installation on LXD if profiles are missing
Fail installation on LXD if profiles are missing on the install hook.
Manually tested in a LXC container.
=> Fail installation on LXD if profiles are missing

.github/workflows/build-snap.yml, tests/libs/addons.sh, tests/test-cluster-agent.py
Added cluster agent healthcheck to GitHub Actions
Added cluster agent healthcheck to GitHub Actions
Tested locally.
=> Added cluster agent healthcheck to GitHub Actions

scripts/wrappers/common/utils.py
Added deprecation warning for chained operations
Added deprecation warning for chained operations
Manually tested.
=> Added deprecation warning for chained operations

.github/workflows/build-snap.yml, build-scripts/components/containerd/version.sh, build-scripts/components/runc/version.sh, build-scripts/images.txt, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Merge branch '1.25' into '1.25-strict' to update the strict branch with the latest fixes on the classic channel.
Creating as a draft PR to see if it works well for us as a process for keeping the strict branch in-line with classic.
=> Merge 1.25 to 1.25-strict

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, .github/workflows/check-formatting.yml, .github/workflows/check-unit-tests.yml, .github/workflows/update-images.yml, build-scripts/components/containerd/version.sh, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/reconcile.d/10-cni-restart, microk8s-resources/default-hooks/reconcile.d/90-calico-apply, microk8s-resources/wrappers/microk8s-join.wrapper, scripts/wrappers/join.py, scripts/wrappers/refresh_certs.py, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, tests/test-distro.sh, tests/unit/test_refresh_certs.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
Merge 1.26 into 1.26-strict to get latest fixes.
=> Merge 1.26 into 1.26-strict

microk8s-resources/actions/common/utils.sh, tests/libs/airgap.sh
Added is_ec2_instance to utils and public.ecr.aws to airgap tests
=> Added is_ec2_instance to utils and public.ecr.aws to airgap tests

README.md
Updated readme to replace chained addons operations
=> Updated readme to replace chained addons operations

scripts/wrappers/common/utils.py
=> set permissions for addons lockfile

.github/workflows/backport.yml
Added the backport workflow to help with backports and team velocity.
=> Added backport workflow

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.26
=> Backport leave node error fix (#3793) to 1.26

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.26-strict
=> Backport leave node error fix (#3793) to 1.26-strict

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.25
=> Backport leave node error fix (#3793) to 1.25

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.25-strict
=> Backport leave node error fix (#3793) to 1.25-strict

scripts/cluster/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.24
=> Backport leave node error fix (#3793) to 1.24

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.24-eksd
=> Backport leave node error fix (#3793) to 1.24-eksd

scripts/cluster/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.23
=> Backport leave node error fix (#3793) to 1.23

tests/test-cluster.py
Fix for node leave error for the latest branch and some tests in test-cluster.py
Created a snap locally and tested using `test-cluster.py`
=> Fix remove-node error

scripts/wrappers/join.py, tests/test-cluster.py
Backport leave node error fix (#3793) to 1.23-eksd
=> Backport leave node error fix (#3793) to 1.23-eksd

microk8s-resources/actions/metallb.yaml
Pull metallb images from quay.io
=> [1.22] Pull metallb images from quay.io

build-scripts/components/k8s-dqlite/build.sh
=> Fix arm64 builds

build-scripts/components/k8s-dqlite/version.sh
Update k8s-dqlite to use the the latest kine that includes a few SQL optimizations https://github.com/canonical/k8s-dqlite/releases/tag/v1.1.3 
Automated tests at the level of kine and the manual tests in the context of microk8s 
The new kine changes the SQL queries and indexes used but not the schema of the database. Deployments that upgrade will not see the benefits of the newly introduced indexes.
=> Update k8s-dqlite to use the latest kine opts

tests/test-cluster.py
=> [1.26-strict] Worker node leave fix

tests/test-cluster.py
=> [1.26] Worker node leave fix

tests/test-cluster.py
=> [1.25] Worker node leave fix

tests/test-cluster.py
=> [1.24-eksd] Worker node leave fix

tests/test-cluster.py
=> [1.24] Worker node leave fix

build-scripts/components/k8s-dqlite/version.sh
Update the k8s-dqlite service to include the table/index migration we have been working in in kine.
k8s-dqlite version increase
Testing was done in the level of kine.
=> Update k8s-dqlite to include table migration

README.md
Updating the README for the 1.27 release
=> Update README for 1.27

scripts/wrappers/common/utils.py
Fixes: https://github.com/canonical/microk8s/issues/3918
=> Use a location with the right permissions for the microk8s-addons-lock

build-scripts/components/cluster-agent/version.sh
Merge after https://github.com/canonical/microk8s-cluster-agent/pull/31
=> [1.25] Use cluster-agent 1.25 branch 

build-scripts/components/cluster-agent/version.sh
Requires https://github.com/canonical/microk8s-cluster-agent/pull/31
=> [1.25-strict] Use cluster-agent 1.25 branch

build-scripts/components/cluster-agent/version.sh
Requires https://github.com/canonical/microk8s-cluster-agent/pull/32
=> [1.26] Use cluster-agent 1.26 branch

build-scripts/components/cluster-agent/version.sh
Requires https://github.com/canonical/microk8s-cluster-agent/pull/32
=> [1.26-strict] Use cluster-agent 1.26 branch

.github/workflows/build-snap.yml, build-scripts/addons/repositories.sh, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh
=> Initialize 1.27 branch

.github/workflows/build-snap.yml, snap/hooks/configure
Follow up fix from https://github.com/canonical/microk8s/pull/3962/files
=> Only set containerd on local config

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-args/kubelet, snap/hooks/configure
Porting two fixes to 1.27-strict:
- the observability fix
- the gh actions trigger
=> Observability fix 1.27 strict

tests/libs/airgap.sh
ensure snapd and core20 install without issues on airgap
=> ensure snapd and core20 install without issues on airgap

.github/workflows/build-snap.yml
Adding a GH test to scan for vulnerabilities, CVEs:
- the repo
- the snap
- the images we have under `build-scripts/images.txt`
=> Add repo scanning with trivy

scripts/wrappers/remove_node.py
If a node in a HA cluster becomes unavailable, we can force remove it using `microk8s remove-node <node> --force`. But internally we use the hostname to remove the node from the k8s cluster. If for some reason the IP of the node is provided instead of the hostname, the node is removed from the dqlite cluster but not from the k8s cluster. We now handle the case when node is given as an IP address and remove it from both dqlite and k8s cluster.
**Testing**
Tested locally on a 3 node cluster
**Related issues**
Closes #3694
=> Fix node removal when node ip is provided instead of node name

upgrade-scripts/000-switch-to-calico/resources/calico.yaml
=> Update calico to 3.25.1

microk8s-resources/actions/common/utils.sh, snap/hooks/install
=> ensure $SNAP_DATA/credentials exists during init configuration

build-scripts/components/containerd/patches/0001-microk8s-sideload-images-plugin.patch
=> [Backport 1.27] import images for default platform only (#4074)

scripts/inspect.sh
Added collection of fs.aio-max-nr and fs.aio-nr to the `microk8s` inspect command.
=> Added collection of fs.aio-max-nr and fs.aio-nr

build-scripts/components/cluster-agent/version.sh
Fix mistake from merging https://github.com/canonical/microk8s/pull/4099
=> Use main from the cluster agent repo

microk8s-resources/actions/common/utils.sh, scripts/wrappers/join.py
Have non-HA nodes join in a cluster.
Requires: https://github.com/canonical/microk8s-cluster-agent/pull/42
Introduce an execution path to handle the non-HA clustering with certs
Manual
=> Adding cert based authn in the non-HA cluster setup

build-scripts/components/cluster-agent/version.sh, scripts/generate-cni.sh, scripts/wrappers/join.py
Now that microk8s supports dual-stack, it is also possible to add-nodes using IPv6 addresses,
Fixes #1751
=> add-node using IPv6 address

README.md, build-scripts/components/kubernetes/patches/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/patches/0001-Set-log-reapply-handling-to-ignore-unchanged.patch
Update README for 1.28 and k8s patches
=> Prepare for 1.28: Readme and k8s patches

tests/test-cluster.py, tests/test-upgrade.py
We do not have an nginx dual stack image.
=> Skip dualstack test on ARM64

snap/hooks/configure, snap/hooks/install, snap/hooks/remove
=> [Backport 1.23] symlink /var/lib/calico (#4149)

.github/workflows/build-snap.yml, build-scripts/addons/repositories.sh, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh
Branch the 1.28 code. Use the 1.28 branches from the respective branches.
=> Initialize 1.28 branch

.github/workflows/build-snap.yml, build-scripts/addons/repositories.sh, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh
=> Initialize 1.28-strict branch

build-scripts/components/k8s-dqlite/version.sh
k8s-dqlite is in active development on the master. Switch to building microk8s master from there.
=> Build from k8s-dqlite master

build-scripts/components/sqlite/version.sh
Bumped the sqlite version to latest, everything seems to run fine after limited manual testing.
=> Bumped sqlite to latest version

microk8s-resources/actions/common/utils.sh
Changed executables to use full path while being called in utils.sh
=> Change executables to use full-paths in utils.sh

microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Minor typo fix, affects recent CI
=> fix typo: sanatise -> sanitize

scripts/wrappers/distributed_op.py
Fixes https://github.com/canonical/microk8s/issues/4253
- Retry listing the cluster nodes until success instead of waiting for a node with status == Ready
=> Fix microk8s import images for offline clusters

microk8s-resources/actions/common/utils.sh
References https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/issues/82
By default, pick the address and port from the apiserver-proxy configuration file when generating kubeconfig files. Otherwise, it will fallback to the `--secure-port` value, which is not the right one for worker nodes.
=> Default to apiserver-proxy port for worker kubeconfigs

CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
=> [Backport 1.24] fix typos and CI

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
Backport #4273 to 1.25-strict branch
=> [Backport 1.25-strict] Fix microk8s import images for offline clusters (#4273)

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
=> [Backport 1.25] Fix microk8s import images for offline clusters (#4273)

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
Backport #4273 to 1.26-strict branch
=> [Backport 1.26-strict] Fix microk8s import images for offline clusters (#4273)

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
=> [Backport 1.26] Fix microk8s import images for offline clusters (#4273)

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args, scripts/wrappers/distributed_op.py
=> [Backport 1.27] Fix microk8s import images for offline clusters (#4273)

tests/templates/dual-stack.yaml, tests/test-cluster.py
Built dual stack image for arm64 and changed the image in template
=> Enable dual stack tests for arm64

.github/workflows/build-snap.yml, CONTRIBUTING.md, microk8s-resources/actions/common/utils.sh, microk8s-resources/wrappers/run-kubelite-with-args
Backport #4265 #4253 to 1.28 branch
=> [Backport 1.28] CI and tooling fixes to make 1.28 branch usable

scripts/wrappers/distributed_op.py
=> [Backport 1.28] Fix microk8s import images for offline clusters (#4273)

installer/vm_providers/_base_provider.py
Change internet connectivity check to use HTTPS, previous check was for ICMP which may not be possible and doesn't confirm whether further steps will work correctly
Closes #3978 
Change internet connectivity check to use HTTPS
Tested code in isolation
=> Use https url to perform connectivity check

installer/cli/microk8s.py
Closes https://github.com/canonical/microk8s/issues/4295
Use a simpler way to create a dashboard token, no need for an external secret.
=> Simplify dashboard token creation

scripts/wrappers/join.py
Backport #4360 to 1.28-strict branch
=> [Backport 1.28-strict] Do not set --hostname-override on kube-proxy (#4360)

scripts/wrappers/join.py
=> [Backport 1.28] Do not set --hostname-override on kube-proxy (#4360)

tests/test-cluster.py
Reduce flakiness in testing of setup_old_versioned_cluster
=> Retries in the nodes check in setup_old_versioned_cluster

scripts/wrappers/common/cluster/utils.py
Fix regression introduced by accident in #4397
=> use ipaddress.ip_address() to check if address is valid

scripts/wrappers/common/cluster/utils.py
Further follow up fix for #4397
=> fix int checks ranges

.github/workflows/update-images.yml
Followup fix on #4519, as YAML is fun https://github.com/canonical/microk8s/actions/runs/9030605859/job/24815231281
=> Fixup 1.30 branch images.txt update

tests/libs/addons.sh, tests/test-upgrade-path.py
Add optional skip to community addons, bump upgrade path starting version
=> Add optional skip to community addons, bump upgrade path starting version

tests/test-cluster-agent.py, upgrade-scripts/000-switch-to-calico/resources/calico.yaml
=> Fix spelling/linting issues for codespell

build-scripts/components/kubernetes/patches/v1.31.0/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/patches/v1.31.0/0001-Set-log-reapply-handling-to-ignore-unchanged.patch
The kubelite patch we had from 1.28 does not apply cleanly on 1.31.
=> Update the kubelite patch for 1.31

tests/libs/addons.sh
Backporting https://github.com/canonical/microk8s/pull/4623
=> Stop testing on the host as this causes problems on our CI

tests/libs/addons.sh
Backporting https://github.com/canonical/microk8s/pull/4623
=> Stop host testing 1.30

build-scripts/components/k8s-dqlite/version.sh
This PR pins the k8s-dqlite version on the strict branch.
=> Pin k8s dqlite version on the strict branch

build-scripts/components/k8s-dqlite/version.sh
This PR pins the k8s-dqlite version on the master branch.
=> Pin k8s-dqlite version

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.29] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.30-strict] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.31] Prioritize SNAP_CURRENT in containerd paths (#4710)

microk8s-resources/wrappers/run-containerd-with-args
=> [Backport 1.31-strict] Prioritize SNAP_CURRENT in containerd paths (#4710)

build-scripts/components/containerd/version.sh, build-scripts/components/runc/version.sh
Bumps runc to `v1.1.15`
Bumps containerd to `v1.6.36`
=> Bump runc to `v1.1.15` and containerd to `v1.6.36`

build-scripts/components/helm/version.sh
=> Bump helm to v3.16.3

build-scripts/components/kubernetes/patches/v1.32.0/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/patches/v1.32.0/0001-Set-log-reapply-handling-to-ignore-unchanged.patch
=> Add patches for 1.32

scripts/kill-host-pods.py
Backports https://github.com/canonical/microk8s/pull/4835
=> [Backport 1.31] scripts: Fix kill-host-pods script

scripts/kill-host-pods.py
Backports https://github.com/canonical/microk8s/pull/4835
=> [Backport 1.29] scripts: Fix kill-host-pods script

scripts/kill-host-pods.py
Backports https://github.com/canonical/microk8s/pull/4840
=> [Backport 1.29] scripts: Fix kill-host-pods script (#4835)

scripts/kill-host-pods.py
Backports https://github.com/canonical/microk8s/pull/4840
=> [Backport 1.30] scripts: Fix kill-host-pods script

build-scripts/components/k8s-dqlite/version.sh
See memory leak fix: https://github.com/canonical/k8s-dqlite/pull/240
=> bug: fix memory leak k8s-dqlite v1.4.1

build-scripts/components/k8s-dqlite/version.sh
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
=> bug: [back-port 1.32] fix memory leak k8s-dqlite v1.3.1

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
=> Bug: [backport v1.2 for 1.31] memory leak fix k8s-dqlite 

.github/workflows/build-installer.yml, .github/workflows/build-snap.yml, build-scripts/components/k8s-dqlite/version.sh
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
=> backport: [1.30] memory leak k8s-dqlite v1.1.12

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/remove.d/90-containers, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove, tests/libs/utils.sh, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/requirements.txt, tests/test-simple.py, tests/test-upgrade.py, tests/utils.py
=> [Backport 1.31] Cleans up containers and shims on microk8s stop and snap removal

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/remove.d/90-containers, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove, tests/libs/utils.sh, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/requirements.txt, tests/test-simple.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/4755 https://github.com/canonical/microk8s/pull/4782
=> [Backport 1.31-strict] Cleans up containers and shims on microk8s stop and snap removal

.github/workflows/build-snap.yml, microk8s-resources/actions/common/utils.sh, microk8s-resources/default-hooks/remove.d/90-containers, microk8s-resources/wrappers/apiservice-kicker, microk8s-resources/wrappers/microk8s-stop.wrapper, snap/hooks/remove, tests/libs/utils.sh, tests/lxc/install-deps/images_almalinux-8, tests/lxc/install-deps/images_centos-7, tests/lxc/install-deps/images_centos-8-Stream, tests/lxc/install-deps/images_debian-10, tests/lxc/install-deps/images_debian-11, tests/lxc/install-deps/images_debian-12, tests/lxc/install-deps/images_fedora-37, tests/lxc/install-deps/images_fedora-38, tests/lxc/install-deps/images_rockylinux-8, tests/lxc/install-deps/ubuntu_18.04, tests/lxc/install-deps/ubuntu_20.04, tests/lxc/install-deps/ubuntu_22.04, tests/requirements.txt, tests/test-simple.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/4755 https://github.com/canonical/microk8s/pull/4782
=> [Backport 1.30-strict] Cleans up containers and shims on microk8s stop and snap removal

build-scripts/addons/repositories.sh
=> fix: use 1.32 addons

README.md
Reduces maintenance effort of README shields
=> Update shields to some thing that does not need maintenance

snap/hooks/configure
=> fix: update configure hook to add a newline before adding watchlist flag

snap/hooks/configure
=> [Backport 1.32] fix: update configure hook to add a newline before adding watchlist flag

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh, snap/hooks/configure, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports #5008 #5009 #5011 #5026
=> [1.32] Backport CI fixes from main

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, build-scripts/components/cluster-agent/version.sh, build-scripts/components/kubernetes/version.sh, snap/hooks/configure, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports #5008 #5009 #5011 #5026
=> [1.32-strict] Backport CI fixes from main

build-scripts/components/runc/strict-patches/v1.2.6/0001-apparmor-change-profile-immediately-not-on-exec.patch, build-scripts/components/runc/strict-patches/v1.2.6/0002-setns_init_linux-set-the-NNP-flag-after-changing-the.patch, build-scripts/components/runc/strict-patches/v1.2.6/0003-standard_init_linux-change-AppArmor-profile-as-late-.patch
Updates strict patches for runc v1.2.6
=> fix: update strict patches for runc 1.2.6

.github/workflows/build-snap.yml
=> [1.32] fix: camel case UNDER_TIME_PRESSURE value

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/5008 https://github.com/canonical/microk8s/pull/5009 https://github.com/canonical/microk8s/pull/5011
=> [1.31] Backport CI fixes from main 

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/5008 https://github.com/canonical/microk8s/pull/5009 https://github.com/canonical/microk8s/pull/5011
=> [1.31-strict] Backport CI fixes from main

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/5008 https://github.com/canonical/microk8s/pull/5009 https://github.com/canonical/microk8s/pull/5011
=> [1.30] Backport CI fixes from main

.github/actions/test-prep/action.yaml, .github/workflows/build-snap.yml, tests/requirements.txt, tests/test-upgrade-path.py, tests/test-upgrade.py, tests/utils.py
Backports https://github.com/canonical/microk8s/pull/5008 https://github.com/canonical/microk8s/pull/5009 https://github.com/canonical/microk8s/pull/5011
=> [1.30-strict] Backport CI fixes from main

microk8s-resources/actions/common/utils.sh
(cherry picked from commit 21337652187ba4b30d4ad0c3180cc847fd3c4128)
=> [1.32] fix: run iptables as sudo on microk8s stop (#5021)

microk8s-resources/actions/common/utils.sh
(cherry picked from commit 21337652187ba4b30d4ad0c3180cc847fd3c4128)
=> [1.31-strict] fix: run iptables as sudo on microk8s stop (#5021)

microk8s-resources/actions/common/utils.sh
(cherry picked from commit 21337652187ba4b30d4ad0c3180cc847fd3c4128)
=> [1.30] fix: run iptables as sudo on microk8s stop (#5021)

build-scripts/components/kubernetes/patches/v1.33.0/0000-Kubelite-integration.patch, build-scripts/components/kubernetes/patches/v1.33.0/0001-Set-log-reapply-handling-to-ignore-unchanged.patch
adds updated patches for kubernetes v1.33
=> chore: add updated patches for kubernetes v1.33
